# Generated by Django 6.0.3 on 2026-03-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='reference_id',
            field=models.CharField(max_length=100),
        ),
    ]
