# Generated by Django 6.0.3 on 2026-08-27 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def convertir_vers_cles_etrangeres(apps, schema_editor):
    """
    (type, reference_id) → clé étrangère.

    Un match est désigné par son `external_id`, une recette et une bière par
    leur clé primaire. Les lignes dont la cible n'existe pas — références
    mortes, ou favoris de type « equipe » que le validateur refusait déjà —
    sont supprimées : la contrainte posée juste après les interdirait.
    """
    Modele = apps.get_model('favorites', 'Favorite')
    Match = apps.get_model('matches', 'Match')
    Recipe = apps.get_model('recipes', 'Recipe')
    Beer = apps.get_model('beers', 'Beer')

    par_external_id = dict(Match.objects.values_list('external_id', 'pk'))
    recettes = set(Recipe.objects.values_list('pk', flat=True))
    bieres = set(Beer.objects.values_list('pk', flat=True))

    a_mettre_a_jour, orphelins = [], []

    for objet in Modele.objects.all().iterator():
        ref = (objet.reference_id or '').strip()

        if objet.type == 'match':
            objet.match_id = par_external_id.get(ref)
            rattache = objet.match_id is not None
        elif objet.type == 'recette':
            objet.recette_id = int(ref) if ref.isdigit() and int(ref) in recettes else None
            rattache = objet.recette_id is not None
        elif objet.type == 'biere':
            objet.biere_id = int(ref) if ref.isdigit() and int(ref) in bieres else None
            rattache = objet.biere_id is not None
        else:
            rattache = False

        (a_mettre_a_jour if rattache else orphelins).append(objet)

    if a_mettre_a_jour:
        Modele.objects.bulk_update(
            a_mettre_a_jour, ['match', 'recette', 'biere'], batch_size=500)

    if orphelins:
        Modele.objects.filter(pk__in=[o.pk for o in orphelins]).delete()


def revenir_aux_references_textuelles(apps, schema_editor):
    """Chemin inverse, pour que la migration reste réversible."""
    Modele = apps.get_model('favorites', 'Favorite')

    a_mettre_a_jour = []
    for objet in Modele.objects.select_related('match').iterator():
        if objet.match_id:
            objet.type, objet.reference_id = 'match', objet.match.external_id
        elif objet.recette_id:
            objet.type, objet.reference_id = 'recette', str(objet.recette_id)
        elif objet.biere_id:
            objet.type, objet.reference_id = 'biere', str(objet.biere_id)
        else:
            continue
        a_mettre_a_jour.append(objet)

    if a_mettre_a_jour:
        Modele.objects.bulk_update(
            a_mettre_a_jour, ['type', 'reference_id'], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0005_beer_utilisateurs_favoris_beer_utilisateurs_notes'),
        ('favorites', '0003_alter_favorite_reference_id'),
        ('matches', '0004_remove_watch_url_delivery_url'),
        ('recipes', '0006_recipe_type_plat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Favori', 'verbose_name_plural': 'Favoris'},
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favorite',
            name='biere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='beers.beer'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='matches.match'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='recette',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='recipes.recipe'),
        ),
        # Une valeur par défaut sur les anciennes colonnes : sans elle, un
        # retour arrière tenterait de les recréer NOT NULL sur une table déjà
        # peuplée — `ADD COLUMN type ... NOT NULL` sans défaut échoue.
        migrations.AlterField(
            model_name='favorite',
            name='type',
            field=models.CharField(default='recette', max_length=10),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='reference_id',
            field=models.CharField(default='', max_length=100),
        ),
        # Les données existantes doivent être converties avant que la
        # contrainte « exactement une cible » ne soit posée.
        migrations.RunPython(
            convertir_vers_cles_etrangeres,
            revenir_aux_references_textuelles,
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('biere__isnull', True), ('match__isnull', False), ('recette__isnull', True)), models.Q(('biere__isnull', True), ('match__isnull', True), ('recette__isnull', False)), models.Q(('biere__isnull', False), ('match__isnull', True), ('recette__isnull', True)), _connector='OR'), name='favori_cible_unique'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'match'), name='favori_unique_par_match'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recette'), name='favori_unique_par_recette'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'biere'), name='favori_unique_par_biere'),
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='reference_id',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='type',
        ),
    ]
