const FLAG_CODES: Record<string, string> = {
  // Europe occidentale
  france:                   'fr',
  england:                  'gb-eng',
  scotland:                 'gb-sct',
  wales:                    'gb-wls',
  'northern ireland':       'gb-nir',
  germany:                  'de',
  spain:                    'es',
  italy:                    'it',
  portugal:                 'pt',
  netherlands:              'nl',
  'the netherlands':        'nl',
  belgium:                  'be',
  austria:                  'at',
  switzerland:              'ch',
  denmark:                  'dk',
  sweden:                   'se',
  norway:                   'no',
  finland:                  'fi',
  ireland:                  'ie',
  luxembourg:               'lu',
  monaco:                   'mc',
  iceland:                  'is',
  andorra:                  'ad',
  'san marino':             'sm',
  liechtenstein:            'li',
  malta:                    'mt',
  gibraltar:                'gi',
  'faroe islands':          'fo',
  // Europe centre/est
  czechia:                  'cz',
  'czech republic':         'cz',
  slovakia:                 'sk',
  poland:                   'pl',
  hungary:                  'hu',
  romania:                  'ro',
  bulgaria:                 'bg',
  slovenia:                 'si',
  croatia:                  'hr',
  serbia:                   'rs',
  'bosnia and herzegovina': 'ba',
  'north macedonia':        'mk',
  macedonia:                'mk',
  montenegro:               'me',
  albania:                  'al',
  kosovo:                   'xk',
  ukraine:                  'ua',
  moldova:                  'md',
  belarus:                  'by',
  russia:                   'ru',
  latvia:                   'lv',
  lithuania:                'lt',
  estonia:                  'ee',
  cyprus:                   'cy',
  greece:                   'gr',
  turkey:                   'tr',
  israel:                   'il',
  azerbaijan:               'az',
  armenia:                  'am',
  georgia:                  'ge',
  kazakhstan:               'kz',
  // Amériques
  usa:                      'us',
  'united states':          'us',
  canada:                   'ca',
  brazil:                   'br',
  argentina:                'ar',
  mexico:                   'mx',
  colombia:                 'co',
  chile:                    'cl',
  uruguay:                  'uy',
  ecuador:                  'ec',
  venezuela:                've',
  peru:                     'pe',
  panama:                   'pa',
  'costa rica':             'cr',
  honduras:                 'hn',
  jamaica:                  'jm',
  'el salvador':            'sv',
  paraguay:                 'py',
  bolivia:                  'bo',
  'trinidad and tobago':    'tt',
  // Afrique
  morocco:                  'ma',
  senegal:                  'sn',
  nigeria:                  'ng',
  ghana:                    'gh',
  egypt:                    'eg',
  "ivory coast":            'ci',
  "côte d'ivoire":          'ci',
  cameroon:                 'cm',
  'south africa':           'za',
  algeria:                  'dz',
  tunisia:                  'tn',
  mali:                     'ml',
  'dr congo':               'cd',
  congo:                    'cg',
  ethiopia:                 'et',
  // Asie / Océanie
  japan:                    'jp',
  'south korea':            'kr',
  'korea republic':         'kr',
  china:                    'cn',
  australia:                'au',
  'saudi arabia':           'sa',
  iran:                     'ir',
  'ir iran':                'ir',
  qatar:                    'qa',
  'united arab emirates':   'ae',
  uzbekistan:               'uz',
  jordan:                   'jo',
  indonesia:                'id',
  'new zealand':            'nz',
  iraq:                     'iq',
  syria:                    'sy',
  // Divers
  europe:                   'eu',
  world:                    'un',
};

export function flagUrl(pays: string): string {
  if (!pays) return '';
  const code = FLAG_CODES[pays.toLowerCase()] ?? pays.toLowerCase();
  return `https://flagcdn.com/w40/${code}.png`;
}
