# Generated by Django 6.0.3 on 2026-03-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('pays', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('temps_preparation', models.PositiveIntegerField(help_text='En minutes')),
                ('image_url', models.URLField(blank=True)),
                ('source_url', models.URLField(blank=True)),
            ],
        ),
    ]
