# Generated by Django 6.0.3 on 2026-03-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='source_url',
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulte',
            field=models.CharField(default='Facile', max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='etapes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='recipe',
            name='nb_personnes',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='recipe',
            name='temps_cuisson',
            field=models.PositiveIntegerField(default=0, help_text='En minutes'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pays',
            field=models.CharField(max_length=50),
        ),
    ]
