# Generated by Django 6.0.3 on 2026-04-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_image_url_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='generated_by',
            field=models.CharField(choices=[('ia', 'IA'), ('manual', 'Manuel')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='times_served',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
