# Generated by Django 6.0.3 on 2026-04-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_region_generated_by_times_served'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='equipe',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
