# Generated by Django 6.0.3 on 2026-04-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_equipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='type_plat',
            field=models.CharField(choices=[('salé', 'Salé'), ('sucré', 'Sucré')], default='salé', max_length=10),
        ),
    ]
