# Generated by Django 6.0.3 on 2026-08-27 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0004_alter_favorite_options_and_more'),
        ('ratings', '0004_alter_rating_options_alter_rating_unique_together_and_more'),
        ('recipes', '0006_recipe_type_plat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='utilisateurs_favoris',
            field=models.ManyToManyField(blank=True, related_name='recettes_favorites', through='favorites.Favorite', through_fields=('recette', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='utilisateurs_notes',
            field=models.ManyToManyField(blank=True, related_name='recettes_notees', through='ratings.Rating', through_fields=('recette', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
