# Generated by Django 6.0.8 on 2026-08-29 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_utilisateurs_favoris_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Recette', 'verbose_name_plural': 'Recettes'},
        ),
    ]
