# Generated by Django 6.0.3 on 2026-06-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('brasserie', models.CharField(max_length=200)),
                ('pays', models.CharField(db_index=True, max_length=50)),
                ('style', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('degre_alcool', models.DecimalField(decimal_places=1, max_digits=4)),
                ('ibu', models.PositiveIntegerField(blank=True, help_text='International Bitterness Units (amertume)', null=True)),
                ('volume', models.PositiveIntegerField(blank=True, help_text='Volume en mL (ex: 330)', null=True)),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Bière',
                'verbose_name_plural': 'Bières',
                'ordering': ['pays', 'nom'],
            },
        ),
    ]
