# Generated by Django 6.0.3 on 2026-04-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('brasserie', models.CharField(blank=True, max_length=200)),
                ('pays', models.CharField(max_length=50)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('equipe', models.CharField(blank=True, max_length=150)),
                ('style', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('degre_alcool', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('generated_by', models.CharField(choices=[('ia', 'IA'), ('manual', 'Manuel')], default='manual', max_length=10)),
                ('times_served', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
