# Generated by Django 6.0.3 on 2026-06-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='equipe',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='beer',
            name='generated_by',
            field=models.CharField(blank=True, default='ia', max_length=50),
        ),
        migrations.AddField(
            model_name='beer',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='beer',
            name='times_served',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
