# Generated by Django 6.0.3 on 2026-06-23 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0002_remove_beer_ibu_remove_beer_volume_beer_equipe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='ibu',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='volume',
        ),
    ]
