# Generated by Django 6.0.3 on 2026-06-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0003_beer_pays_db_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='degre_alcool',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
