# Generated by Django 6.0.3 on 2026-08-27 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0004_degre_alcool_nullable'),
        ('favorites', '0003_alter_favorite_reference_id'),
        ('ratings', '0003_alter_rating_reference_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='utilisateurs_favoris',
            field=models.ManyToManyField(blank=True, related_name='bieres_favorites', through='favorites.Favorite', through_fields=('biere', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beer',
            name='utilisateurs_notes',
            field=models.ManyToManyField(blank=True, related_name='bieres_notees', through='ratings.Rating', through_fields=('biere', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
