# Generated by Django 6.0.3 on 2026-03-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('football', 'Football'), ('rugby', 'Rugby'), ('basketball', 'Basketball')], default='football', max_length=50)),
                ('competition', models.CharField(max_length=100)),
                ('equipe_a', models.CharField(max_length=100)),
                ('equipe_b', models.CharField(max_length=100)),
                ('pays_a', models.CharField(max_length=10)),
                ('pays_b', models.CharField(max_length=10)),
                ('date_heure', models.DateTimeField()),
                ('watch_url', models.URLField(blank=True)),
                ('delivery_url', models.URLField(blank=True)),
            ],
        ),
    ]
