# Generated by Django 6.0.3 on 2026-03-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('TRUNCATE TABLE matches_match RESTART IDENTITY CASCADE;'),
        migrations.AddField(
            model_name='match',
            name='external_id',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='logo_a',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='match',
            name='logo_b',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='match',
            name='score_a',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='score_b',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='statut',
            field=models.CharField(default='NS', max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='pays_a',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='match',
            name='pays_b',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
