# Generated by Django 6.0.3 on 2026-04-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_external_id_match_logo_a_match_logo_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='league_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='thumb_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='match',
            name='sport',
            field=models.CharField(default='football', max_length=50),
        ),
    ]
