# Generated by Django 6.0.3 on 2026-08-27 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0004_alter_favorite_options_and_more'),
        ('matches', '0004_remove_watch_url_delivery_url'),
        ('ratings', '0003_alter_rating_reference_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='utilisateurs_favoris',
            field=models.ManyToManyField(blank=True, related_name='matchs_favoris', through='favorites.Favorite', through_fields=('match', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='utilisateurs_notes',
            field=models.ManyToManyField(blank=True, related_name='matchs_notes', through='ratings.Rating', through_fields=('match', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
