# Generated by Django 6.0.8 on 2026-08-29 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_match_utilisateurs_favoris_match_utilisateurs_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Match', 'verbose_name_plural': 'Matchs'},
        ),
    ]
