from django.core.management.base import BaseCommand
from apps.recipes.models import Recipe

RECIPES = [
    # ── FRANCE ──────────────────────────────────────────────────────────────
    {
        'titre': 'Bœuf Bourguignon',
        'pays': 'france',
        'description': 'Le grand classique de la cuisine française : un bœuf mijoté lentement dans un vin de Bourgogne avec lardons, champignons et carottes.',
        'temps_preparation': 30,
        'temps_cuisson': 180,
        'nb_personnes': 6,
        'difficulte': 'Moyen',
        'ingredients': [
            '1,2 kg de bœuf (paleron ou macreuse)', '200 g de lardons fumés',
            '1 bouteille de vin rouge de Bourgogne', '300 g de champignons de Paris',
            '3 carottes', '2 oignons', '2 gousses d\'ail', 'Thym, laurier',
            'Farine, beurre, huile', 'Sel, poivre',
        ],
        'etapes': [
            'Couper le bœuf en gros cubes et les fariner légèrement.',
            'Faire dorer les cubes dans une cocotte avec huile et beurre. Réserver.',
            'Faire revenir lardons, oignons émincés et ail dans la même cocotte.',
            'Remettre la viande, ajouter le vin rouge, les carottes en rondelles, thym et laurier.',
            'Couvrir et mijoter à feu doux 2h30 à 3h.',
            'Ajouter les champignons 30 min avant la fin de cuisson.',
            'Rectifier l\'assaisonnement et servir avec des pommes de terre vapeur.',
        ],
        'tags': ['Mijoté', 'Comfort food', 'Hiver', 'Traditionnel'],
        'image_url': 'https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=800&q=80',
    },
    {
        'titre': 'Ratatouille Provençale',
        'pays': 'france',
        'description': 'Un ragoût de légumes d\'été du soleil provençal, parfumé aux herbes de Provence.',
        'temps_preparation': 25,
        'temps_cuisson': 45,
        'nb_personnes': 4,
        'difficulte': 'Facile',
        'ingredients': [
            '2 courgettes', '1 aubergine', '3 tomates', '2 poivrons (rouge et jaune)',
            '1 oignon', '3 gousses d\'ail', 'Herbes de Provence', 'Huile d\'olive',
            'Sel, poivre',
        ],
        'etapes': [
            'Couper tous les légumes en dés de taille similaire.',
            'Faire revenir l\'oignon et l\'ail dans l\'huile d\'olive.',
            'Ajouter les poivrons et faire revenir 5 min.',
            'Ajouter l\'aubergine, puis les courgettes, puis les tomates.',
            'Assaisonner avec les herbes de Provence, sel et poivre.',
            'Couvrir et mijoter 40 min à feu doux.',
        ],
        'tags': ['Végétarien', 'Légumes', 'Été', 'Provence'],
        'image_url': 'https://images.unsplash.com/photo-1572453800999-e8d2d1589b7c?w=800&q=80',
    },
    {
        'titre': 'Crêpes Bretonnes',
        'pays': 'france',
        'description': 'Les fines crêpes de Bretagne, à décliner sucrées au caramel beurre salé ou salées au jambon et fromage.',
        'temps_preparation': 10,
        'temps_cuisson': 20,
        'nb_personnes': 4,
        'difficulte': 'Facile',
        'ingredients': [
            '250 g de farine de blé', '3 œufs', '500 ml de lait', '50 g de beurre fondu',
            '1 pincée de sel', '1 c. à soupe de sucre', 'Beurre pour la poêle',
        ],
        'etapes': [
            'Mélanger farine, œufs, sel et sucre dans un bol.',
            'Ajouter le lait progressivement en fouettant pour éviter les grumeaux.',
            'Incorporer le beurre fondu. Laisser reposer 30 min.',
            'Faire chauffer une poêle beurrée à feu moyen.',
            'Verser une louche de pâte, incliner la poêle pour répartir.',
            'Cuire 1 min de chaque côté jusqu\'à dorure.',
        ],
        'tags': ['Brunch', 'Dessert', 'Bretagne', 'Rapide'],
        'image_url': 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=800&q=80',
    },

    # ── ENGLAND ─────────────────────────────────────────────────────────────
    {
        'titre': 'Fish & Chips',
        'pays': 'england',
        'description': 'Le plat national anglais : cabillaud en beignet croustillant et frites épaisses, servi avec du vinaigre de malt.',
        'temps_preparation': 20,
        'temps_cuisson': 25,
        'nb_personnes': 4,
        'difficulte': 'Moyen',
        'ingredients': [
            '4 filets de cabillaud (150 g chacun)', '200 g de farine', '300 ml de bière blonde',
            '1 kg de pommes de terre', 'Huile de friture', 'Sel, vinaigre de malt',
            '1 c. à café de levure chimique',
        ],
        'etapes': [
            'Éplucher et couper les pommes de terre en frites épaisses.',
            'Précuire les frites 5 min à 150°C, égoutter et réserver.',
            'Préparer la pâte à beignet : mélanger farine, levure, bière et sel.',
            'Tremper les filets de cabillaud dans la pâte.',
            'Frire le poisson 4 à 5 min à 180°C jusqu\'à dorure.',
            'Remonter les frites à 180°C pour 3 min de finition.',
            'Servir avec sel et vinaigre de malt.',
        ],
        'tags': ['Frit', 'Poisson', 'Traditionnel', 'Pub food'],
        'image_url': 'https://images.unsplash.com/photo-1584949091598-c31daaaa4aa9?w=800&q=80',
    },
    {
        'titre': 'Chicken Tikka Masala',
        'pays': 'england',
        'description': 'Le curry préféré des Britanniques : poulet mariné au yaourt et épices, mijoté dans une sauce tomate crémeuse.',
        'temps_preparation': 30,
        'temps_cuisson': 30,
        'nb_personnes': 4,
        'difficulte': 'Moyen',
        'ingredients': [
            '600 g de poulet', '200 ml de yaourt nature', '400 ml de crème de coco',
            '400 g de tomates concassées', '2 oignons', '3 gousses d\'ail', '2 cm de gingembre',
            'Garam masala, cumin, coriandre, paprika fumé', 'Huile, sel',
        ],
        'etapes': [
            'Mariner le poulet coupé en dés dans le yaourt et les épices 2h minimum.',
            'Griller le poulet mariné au four à 200°C 15 min.',
            'Faire revenir oignons, ail et gingembre dans l\'huile.',
            'Ajouter les épices et les tomates concassées.',
            'Incorporer la crème de coco, mijoter 15 min.',
            'Ajouter le poulet grillé et cuire encore 10 min.',
            'Servir avec du riz basmati.',
        ],
        'tags': ['Curry', 'Épicé', 'Comfort food', 'Populaire'],
        'image_url': 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&q=80',
    },
    {
        'titre': 'Beef Wellington',
        'pays': 'england',
        'description': 'Le rôti de bœuf enveloppé dans une duxelles de champignons et une pâte feuilletée dorée — le plat des grandes occasions.',
        'temps_preparation': 45,
        'temps_cuisson': 30,
        'nb_personnes': 6,
        'difficulte': 'Difficile',
        'ingredients': [
            '800 g de filet de bœuf', '300 g de champignons de Paris', '6 tranches de jambon de Parme',
            '1 rouleau de pâte feuilletée', '2 c. à soupe de moutarde de Dijon',
            '2 jaunes d\'œuf', 'Sel, poivre, huile',
        ],
        'etapes': [
            'Saisir le filet de bœuf sur toutes ses faces dans une poêle très chaude.',
            'Badigeonner de moutarde et laisser refroidir.',
            'Mixer les champignons et faire sécher à la poêle (duxelles).',
            'Étaler le jambon de Parme, y répartir la duxelles, poser le filet et rouler.',
            'Envelopper dans la pâte feuilletée, souder les bords.',
            'Dorer à l\'œuf et enfourner 25 min à 200°C (rosé à cœur).',
            'Laisser reposer 10 min avant de trancher.',
        ],
        'tags': ['Festif', 'Bœuf', 'Élégant', 'Dimanche'],
        'image_url': 'https://images.unsplash.com/photo-1546833998-877b37c2e5c6?w=800&q=80',
    },

    # ── GERMANY ─────────────────────────────────────────────────────────────
    {
        'titre': 'Bratwurst & Choucroute',
        'pays': 'germany',
        'description': 'Saucisses de porc grillées accompagnées de choucroute mijotée à la bière et aux baies de genièvre.',
        'temps_preparation': 10,
        'temps_cuisson': 30,
        'nb_personnes': 4,
        'difficulte': 'Facile',
        'ingredients': [
            '8 bratwurst (saucisses allemandes)', '800 g de choucroute cuite',
            '1 oignon', '200 ml de bière blonde', '5 baies de genièvre',
            'Moutarde à l\'ancienne', 'Beurre', 'Sel, poivre',
        ],
        'etapes': [
            'Faire revenir l\'oignon émincé dans le beurre.',
            'Ajouter la choucroute, la bière et les baies de genièvre.',
            'Mijoter 20 min à feu doux.',
            'Griller les bratwurst à la poêle ou au barbecue 8 min en les retournant.',
            'Servir les saucisses sur la choucroute avec la moutarde.',
        ],
        'tags': ['Traditionnel', 'Bière', 'Grill', 'Bavière'],
        'image_url': 'https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=800&q=80',
    },
    {
        'titre': 'Pretzels Maison',
        'pays': 'germany',
        'description': 'Les bretzels moelleux à croûte dorée, saupoudrés de gros sel — le snack incontournable des brasseries bavaroises.',
        'temps_preparation': 30,
        'temps_cuisson': 15,
        'nb_personnes': 8,
        'difficulte': 'Moyen',
        'ingredients': [
            '500 g de farine T55', '7 g de levure sèche', '300 ml d\'eau tiède',
            '10 g de sel', '20 g de beurre', '50 g de bicarbonate de soude',
            'Gros sel pour saupoudrer',
        ],
        'etapes': [
            'Dissoudre la levure dans l\'eau tiède.',
            'Pétrir farine, sel, beurre et eau levurée 10 min jusqu\'à pâte lisse.',
            'Laisser lever 1h à température ambiante.',
            'Former des boudins de 60 cm et plier en forme de bretzel.',
            'Tremper 30 secondes dans de l\'eau bouillante bicarbonatée.',
            'Saupoudrer de gros sel et enfourner 12-15 min à 220°C.',
        ],
        'tags': ['Snack', 'Boulangerie', 'Apéro', 'Bière'],
        'image_url': 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&q=80',
    },
    {
        'titre': 'Sauerbraten',
        'pays': 'germany',
        'description': 'Rôti de bœuf mariné plusieurs jours dans du vinaigre et des épices, mijoté dans une sauce aigre-douce au pain d\'épices.',
        'temps_preparation': 20,
        'temps_cuisson': 120,
        'nb_personnes': 6,
        'difficulte': 'Difficile',
        'ingredients': [
            '1,5 kg de bœuf (gîte ou paleron)', '500 ml de vinaigre de vin rouge',
            '500 ml d\'eau', '2 oignons', '2 carottes', 'Clous de girofle, baies de genièvre',
            'Thym, laurier', '2 tranches de pain d\'épices', 'Crème fraîche', 'Sel, poivre',
        ],
        'etapes': [
            'Faire bouillir la marinade (vinaigre, eau, légumes, épices), laisser refroidir.',
            'Mariner le bœuf 3 jours au réfrigérateur dans la marinade froide.',
            'Égoutter et sécher la viande, la saisir dans une cocotte.',
            'Ajouter les légumes de la marinade filtrée et couvrir.',
            'Mijoter 2h à feu doux.',
            'Émietter le pain d\'épices dans la sauce et lier avec la crème fraîche.',
        ],
        'tags': ['Marinade', 'Mijoté', 'Bœuf', 'Traditionnel'],
        'image_url': 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80',
    },

    # ── SPAIN ────────────────────────────────────────────────────────────────
    {
        'titre': 'Paella Valenciana',
        'pays': 'spain',
        'description': 'Le riz safranné au poulet et lapin de Valence, cuit dans une poêle à paella sur feu de bois.',
        'temps_preparation': 25,
        'temps_cuisson': 40,
        'nb_personnes': 6,
        'difficulte': 'Moyen',
        'ingredients': [
            '500 g de riz à paella (Bomba)', '600 g de poulet', '300 g de lapin',
            '200 g de haricots verts', '150 g de haricots plats', '1 tomate',
            '1 g de safran', '1,5 L de bouillon de poulet', 'Huile d\'olive', 'Sel, paprika doux',
        ],
        'etapes': [
            'Faire dorer les morceaux de poulet et lapin dans l\'huile d\'olive.',
            'Ajouter la tomate et le paprika, faire revenir 2 min.',
            'Verser le bouillon chaud et le safran. Porter à ébullition.',
            'Ajouter les haricots et laisser cuire 10 min.',
            'Verser le riz en pluie et ne plus remuer.',
            'Cuire 18 min à feu vif puis laisser reposer 5 min recouvert.',
        ],
        'tags': ['Riz', 'Valence', 'Safran', 'Festif'],
        'image_url': 'https://images.unsplash.com/photo-1534080564583-6be75777b70a?w=800&q=80',
    },
    {
        'titre': 'Patatas Bravas',
        'pays': 'spain',
        'description': 'La tapas emblématique : pommes de terre frites croustillantes nappées d\'une sauce épicée et d\'aïoli.',
        'temps_preparation': 15,
        'temps_cuisson': 20,
        'nb_personnes': 4,
        'difficulte': 'Facile',
        'ingredients': [
            '800 g de pommes de terre', 'Huile de friture',
            '200 ml de tomates concassées', '1 c. à café de paprika fumé',
            '1 pincée de piment de Cayenne', '1 gousse d\'ail',
            'Mayonnaise pour l\'aïoli',
        ],
        'etapes': [
            'Éplucher et couper les pommes de terre en gros cubes.',
            'Frire à 180°C 8-10 min jusqu\'à dorure. Égoutter et saler.',
            'Faire la sauce bravas : revenir ail, ajouter tomates, paprika et piment. Mixer.',
            'Faire l\'aïoli : mixer mayonnaise avec une gousse d\'ail.',
            'Servir les pommes de terre nappées des deux sauces.',
        ],
        'tags': ['Tapas', 'Apéro', 'Frit', 'Épicé'],
        'image_url': 'https://images.unsplash.com/photo-1580476262798-bddd9f4b7369?w=800&q=80',
    },
    {
        'titre': 'Gazpacho Andalou',
        'pays': 'spain',
        'description': 'La soupe froide d\'Andalousie : tomates, concombre et poivron mixés avec de l\'huile d\'olive et du vinaigre de Jerez.',
        'temps_preparation': 15,
        'temps_cuisson': 0,
        'nb_personnes': 4,
        'difficulte': 'Facile',
        'ingredients': [
            '800 g de tomates bien mûres', '1 concombre', '1 poivron rouge',
            '1 gousse d\'ail', '50 ml d\'huile d\'olive extra vierge',
            '2 c. à soupe de vinaigre de Jerez', 'Sel, eau froide',
        ],
        'etapes': [
            'Éplucher et couper grossièrement tous les légumes.',
            'Mixer l\'ensemble avec l\'huile, le vinaigre et l\'ail.',
            'Ajouter de l\'eau froide pour ajuster la texture.',
            'Filtrer au chinois pour un résultat lisse.',
            'Réfrigérer au moins 2h avant de servir bien frais.',
        ],
        'tags': ['Soupe froide', 'Végétarien', 'Été', 'Andalousie'],
        'image_url': 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80',
    },

    # ── ITALY ────────────────────────────────────────────────────────────────
    {
        'titre': 'Risotto alla Milanese',
        'pays': 'italy',
        'description': 'Le risotto crémeux de Milan au safran et parmesan, accompagnement traditionnel de l\'osso buco.',
        'temps_preparation': 10,
        'temps_cuisson': 25,
        'nb_personnes': 4,
        'difficulte': 'Moyen',
        'ingredients': [
            '320 g de riz Carnaroli', '1 g de safran en filaments',
            '1,2 L de bouillon de bœuf chaud', '1 oignon', '150 ml de vin blanc sec',
            '80 g de parmesan râpé', '60 g de beurre', 'Sel, poivre',
        ],
        'etapes': [
            'Dissoudre le safran dans un peu de bouillon chaud.',
            'Faire revenir l\'oignon émincé dans la moitié du beurre.',
            'Ajouter le riz et le nacrer 2 min.',
            'Déglacer au vin blanc, laisser absorber.',
            'Ajouter le bouillon louche par louche en remuant constamment.',
            'À mi-cuisson, ajouter le safran dissous.',
            'Mantecatura finale : hors du feu, incorporer beurre froid et parmesan.',
        ],
        'tags': ['Riz', 'Milan', 'Crémeux', 'Safran'],
        'image_url': 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800&q=80',
    },
    {
        'titre': 'Pizza Napoletana Margherita',
        'pays': 'italy',
        'description': 'La pizza napolitaine authentique : pâte à la farine 00, tomates San Marzano, mozzarella di bufala et basilic frais.',
        'temps_preparation': 30,
        'temps_cuisson': 10,
        'nb_personnes': 4,
        'difficulte': 'Moyen',
        'ingredients': [
            '500 g de farine 00', '7 g de levure sèche', '325 ml d\'eau',
            '10 g de sel', '400 g de tomates San Marzano', '250 g de mozzarella di bufala',
            'Basilic frais', 'Huile d\'olive extra vierge',
        ],
        'etapes': [
            'Dissoudre levure dans l\'eau, ajouter farine et sel. Pétrir 10 min.',
            'Laisser lever 6h à température ambiante ou 24h au frigo.',
            'Former 4 patons, laisser lever encore 30 min.',
            'Étaler à la main en disques fins de 30 cm.',
            'Garnir de tomates écrasées, mozzarella déchirée, filet d\'huile.',
            'Cuire 8-10 min au four à 280°C (ou pierre réfractaire).',
            'Ajouter le basilic frais à la sortie du four.',
        ],
        'tags': ['Pizza', 'Naples', 'Végétarien', 'Classique'],
        'image_url': 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&q=80',
    },
    {
        'titre': 'Tiramisu',
        'pays': 'italy',
        'description': 'Le dessert italien le plus célèbre : biscuits imbibés de café, mascarpone et cacao. Littéralement "remonte-moi".',
        'temps_preparation': 25,
        'temps_cuisson': 0,
        'nb_personnes': 8,
        'difficulte': 'Facile',
        'ingredients': [
            '500 g de mascarpone', '4 œufs', '100 g de sucre',
            '300 ml de café expresso fort refroidi', '24 biscuits Savoiardi (boudoirs)',
            'Cacao amer en poudre', '2 c. à soupe de Marsala (optionnel)',
        ],
        'etapes': [
            'Séparer blancs et jaunes d\'œufs.',
            'Fouetter jaunes et sucre jusqu\'à blanchissement.',
            'Incorporer le mascarpone au mélange jaunes-sucre.',
            'Monter les blancs en neige ferme et les incorporer délicatement.',
            'Tremper rapidement les biscuits dans le café (+ Marsala).',
            'Alterner couche de biscuits et couche de crème dans un plat.',
            'Réfrigérer 6h minimum. Saupoudrer de cacao avant de servir.',
        ],
        'tags': ['Dessert', 'Café', 'Sans cuisson', 'Classique'],
        'image_url': 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800&q=80',
    },

    # ── PORTUGAL ─────────────────────────────────────────────────────────────
    {
        'titre': 'Bacalhau à Brás',
        'pays': 'portugal',
        'description': 'Morue effilochée sautée avec des pommes de terre paille et des œufs brouillés. Le plat portugais par excellence.',
        'temps_preparation': 30,
        'temps_cuisson': 20,
        'nb_personnes': 4,
        'difficulte': 'Moyen',
        'ingredients': [
            '600 g de morue dessalée', '400 g de pommes de terre paille (surgelées ok)',
            '4 œufs', '2 oignons', '3 gousses d\'ail', 'Olives noires',
            'Persil frais', 'Huile d\'olive', 'Sel, poivre',
        ],
        'etapes': [
            'Effilocher la morue dessalée en petits morceaux.',
            'Faire dorer les pommes de terre paille à l\'huile. Réserver.',
            'Faire revenir oignons et ail dans l\'huile d\'olive.',
            'Ajouter la morue effilochée et faire revenir 3 min.',
            'Ajouter les pommes de terre paille et les œufs battus.',
            'Mélanger délicatement à feu doux jusqu\'à œufs légèrement pris.',
            'Servir avec olives noires et persil ciselé.',
        ],
        'tags': ['Morue', 'Traditionnel', 'Rapide', 'Porto'],
        'image_url': 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80',
    },
    {
        'titre': 'Pastéis de Nata',
        'pays': 'portugal',
        'description': 'Les petits flans crémeux à la pâte feuilletée de Lisbonne, saupoudrés de cannelle et de sucre glace.',
        'temps_preparation': 20,
        'temps_cuisson': 20,
        'nb_personnes': 12,
        'difficulte': 'Moyen',
        'ingredients': [
            '1 rouleau de pâte feuilletée', '500 ml de lait entier', '6 jaunes d\'œuf',
            '150 g de sucre', '40 g de farine', '1 bâton de cannelle', '1 écorce de citron',
            'Cannelle et sucre glace pour servir',
        ],
        'etapes': [
            'Chauffer lait avec cannelle et zeste de citron. Laisser infuser.',
            'Fouetter jaunes, sucre et farine. Verser le lait chaud filtré.',
            'Remettre sur feu doux et remuer jusqu\'à épaississement.',
            'Foncer des moules à tartelettes beurrés avec la pâte feuilletée.',
            'Remplir de crème aux 3/4.',
            'Cuire 15-20 min à 250°C jusqu\'à caramélisation des bords.',
            'Saupoudrer de cannelle et sucre glace avant de servir.',
        ],
        'tags': ['Pâtisserie', 'Dessert', 'Lisbonne', 'Belém'],
        'image_url': 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    },
    {
        'titre': 'Caldo Verde',
        'pays': 'portugal',
        'description': 'La soupe verte nationale : velouté de pommes de terre au chou kale et rondelles de chouriço.',
        'temps_preparation': 15,
        'temps_cuisson': 30,
        'nb_personnes': 4,
        'difficulte': 'Facile',
        'ingredients': [
            '600 g de pommes de terre', '200 g de chou frisé (kale)', '1 chouriço (chorizo portugais)',
            '1 oignon', '3 gousses d\'ail', 'Huile d\'olive',
            '1,2 L d\'eau ou bouillon', 'Sel, poivre',
        ],
        'etapes': [
            'Faire revenir oignon et ail dans l\'huile d\'olive.',
            'Ajouter pommes de terre coupées et couvrir d\'eau. Cuire 20 min.',
            'Mixer finement pour obtenir un velouté lisse.',
            'Faire revenir les rondelles de chouriço séparément.',
            'Ciseler le kale en très fines lanières.',
            'Porter le velouté à ébullition, ajouter le kale et cuire 3 min.',
            'Servir avec les rondelles de chouriço et un filet d\'huile d\'olive.',
        ],
        'tags': ['Soupe', 'Végétal', 'Hivernal', 'Traditionnel'],
        'image_url': 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80',
    },

    # ── NETHERLANDS ──────────────────────────────────────────────────────────
    {
        'titre': 'Stamppot Boerenkool',
        'pays': 'netherlands',
        'description': 'Purée de pommes de terre mélangée au chou frisé, servie avec une rookworst (saucisse fumée) et de la moutarde.',
        'temps_preparation': 15,
        'temps_cuisson': 30,
        'nb_personnes': 4,
        'difficulte': 'Facile',
        'ingredients': [
            '1 kg de pommes de terre', '400 g de chou frisé (boerenkool)',
            '2 rookworst (ou saucisses fumées)', '100 ml de lait chaud',
            '50 g de beurre', 'Moutarde de Dijon', 'Sel, poivre, noix de muscade',
        ],
        'etapes': [
            'Cuire les pommes de terre épluchées dans l\'eau salée 20 min.',
            'Blanchir le chou frisé 5 min dans l\'eau bouillante.',
            'Réchauffer les saucisses fumées selon les instructions.',
            'Écraser les pommes de terre avec beurre et lait chaud.',
            'Incorporer le chou frisé haché à la purée.',
            'Assaisonner avec sel, poivre et noix de muscade.',
            'Servir avec la saucisse et une cuillère de moutarde.',
        ],
        'tags': ['Purée', 'Hiver', 'Réconfortant', 'Traditionnel'],
        'image_url': 'https://images.unsplash.com/photo-1585325701956-60dd9c8553bc?w=800&q=80',
    },
    {
        'titre': 'Haring (Hareng Hollandais)',
        'pays': 'netherlands',
        'description': 'Le hareng cru mariné à la hollandaise, servi avec oignons émincés et cornichons. Street food iconique d\'Amsterdam.',
        'temps_preparation': 10,
        'temps_cuisson': 0,
        'nb_personnes': 2,
        'difficulte': 'Facile',
        'ingredients': [
            '4 filets de hareng "Hollandse Nieuwe" (hareng mariné)',
            '2 oignons blancs finement émincés',
            '4 cornichons en tranches',
            'Pain blanc (optionnel)',
        ],
        'etapes': [
            'Sortir les filets de hareng de leur saumure et les égoutter.',
            'Émincer finement les oignons blancs.',
            'Trancher les cornichons.',
            'Servir le hareng tenu par la queue avec oignons et cornichons.',
            'On peut aussi le servir dans un petit pain blanc (broodje haring).',
        ],
        'tags': ['Street food', 'Poisson cru', 'Amsterdam', 'Rapide'],
        'image_url': 'https://images.unsplash.com/photo-1519864600265-abb23847ef2c?w=800&q=80',
    },
    {
        'titre': 'Poffertjes',
        'pays': 'netherlands',
        'description': 'Petites crêpes épaisses et moelleuses servies avec du beurre fondu et du sucre glace, typiques des marchés néerlandais.',
        'temps_preparation': 15,
        'temps_cuisson': 15,
        'nb_personnes': 4,
        'difficulte': 'Facile',
        'ingredients': [
            '250 g de farine', '7 g de levure sèche', '300 ml de lait tiède',
            '2 œufs', '1 pincée de sel', 'Beurre pour la poêle',
            'Beurre et sucre glace pour servir',
        ],
        'etapes': [
            'Dissoudre la levure dans le lait tiède.',
            'Mélanger farine, œufs, sel et lait levuré en pâte lisse.',
            'Laisser lever 30 min.',
            'Beurrer une poêle à poffertjes (ou une poêle à blinis).',
            'Remplir chaque creux aux 2/3 et cuire 1 min, retourner.',
            'Servir immédiatement avec noix de beurre et abondant sucre glace.',
        ],
        'tags': ['Dessert', 'Street food', 'Rapide', 'Sucré'],
        'image_url': 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&q=80',
    },

    # ── BELGIUM ──────────────────────────────────────────────────────────────
    {
        'titre': 'Moules-Frites à la Bière',
        'pays': 'belgium',
        'description': 'Les moules cuites à la bière blonde belge avec céleri et échalotes, accompagnées de frites croustillantes maison.',
        'temps_preparation': 20,
        'temps_cuisson': 15,
        'nb_personnes': 4,
        'difficulte': 'Facile',
        'ingredients': [
            '2 kg de moules de bouchot', '1 bière blonde belge (25 cl)',
            '4 échalotes', '2 branches de céleri', '2 gousses d\'ail',
            '50 g de beurre', '1 kg de pommes de terre à frites', 'Persil frais',
        ],
        'etapes': [
            'Brosser et gratter les moules, éliminer celles ouvertes.',
            'Faire revenir échalotes, céleri et ail dans le beurre.',
            'Ajouter les moules et la bière. Couvrir à feu vif.',
            'Cuire 5-6 min en remuant, jusqu\'à ouverture complète.',
            'Pendant ce temps, faire les frites : 2 bains de friture (160°C puis 180°C).',
            'Parsemer de persil ciselé et servir avec les frites.',
        ],
        'tags': ['Moules', 'Bière', 'Plat national', 'Fruits de mer'],
        'image_url': 'https://images.unsplash.com/photo-1559742811-822873691df8?w=800&q=80',
    },
    {
        'titre': 'Carbonnade Flamande',
        'pays': 'belgium',
        'description': 'Ragoût de bœuf mijoté à la bière brune et au pain d\'épices, le plat emblématique de la Flandre.',
        'temps_preparation': 20,
        'temps_cuisson': 150,
        'nb_personnes': 6,
        'difficulte': 'Moyen',
        'ingredients': [
            '1,2 kg de bœuf (paleron)', '500 ml de bière brune belge (Leffe Brune)',
            '3 oignons', '2 tranches de pain d\'épices avec moutarde',
            'Thym, laurier', 'Beurre, farine', 'Sel, poivre',
        ],
        'etapes': [
            'Couper et faire revenir le bœuf par petites quantités.',
            'Faire revenir les oignons dans le beurre jusqu\'à caramélisation.',
            'Alterner couches de viande et d\'oignons dans la cocotte.',
            'Verser la bière, ajouter thym et laurier.',
            'Poser les tranches de pain d\'épices (côté moutarde vers le bas) sur le dessus.',
            'Mijoter à couvert 2h30 à feu très doux.',
            'Écraser le pain d\'épices fondu dans la sauce pour la lier.',
        ],
        'tags': ['Mijoté', 'Bière', 'Flandre', 'Hiver'],
        'image_url': 'https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=800&q=80',
    },
    {
        'titre': 'Gaufres de Liège',
        'pays': 'belgium',
        'description': 'Les gaufres caramélisées de Liège avec leur sucre perlé qui croque sous la dent — bien différentes des gaufres de Bruxelles.',
        'temps_preparation': 20,
        'temps_cuisson': 20,
        'nb_personnes': 8,
        'difficulte': 'Moyen',
        'ingredients': [
            '500 g de farine', '200 g de beurre mou', '2 œufs', '150 ml de lait tiède',
            '7 g de levure sèche', '1 sachet de sucre vanillé', '200 g de sucre perlé', 'Sel',
        ],
        'etapes': [
            'Dissoudre la levure dans le lait tiède.',
            'Mélanger farine, œufs, beurre, sucre vanillé, sel et lait levuré.',
            'Pétrir jusqu\'à pâte élastique.',
            'Laisser lever 1h.',
            'Incorporer délicatement le sucre perlé à la pâte.',
            'Former des boules de 80g et cuire au fer à gaufres 4-5 min.',
        ],
        'tags': ['Gaufre', 'Liège', 'Sucré', 'Street food'],
        'image_url': 'https://images.unsplash.com/photo-1562376552-0d160a2f238d?w=800&q=80',
    },

    # ── NORWAY ───────────────────────────────────────────────────────────────
    {
        'titre': 'Gravlax Nordique',
        'pays': 'norway',
        'description': 'Saumon cru mariné au sel, sucre et aneth — une spécialité scandinave fraîche et délicate.',
        'temps_preparation': 20,
        'temps_cuisson': 0,
        'nb_personnes': 8,
        'difficulte': 'Facile',
        'ingredients': [
            '1 kg de filet de saumon frais (sans arêtes)', '100 g de gros sel',
            '80 g de sucre', '1 gros bouquet d\'aneth frais', 'Poivre blanc concassé',
            'Moutarde douce et aneth pour la sauce',
        ],
        'etapes': [
            'Mélanger sel, sucre et poivre blanc.',
            'Parsemer le tiers du mélange dans un plat, poser le saumon côté peau.',
            'Couvrir généreusement d\'aneth frais haché.',
            'Recouvrir du reste du mélange sel-sucre.',
            'Filmer et placer au réfrigérateur 48h en retournant toutes les 12h.',
            'Rincer, sécher et trancher très finement en biseau.',
            'Servir avec sauce moutarde-aneth et pain de seigle.',
        ],
        'tags': ['Poisson cru', 'Scandinave', 'Sans cuisson', 'Festif'],
        'image_url': 'https://images.unsplash.com/photo-1519864600265-abb23847ef2c?w=800&q=80',
    },
    {
        'titre': 'Kjøttkaker (Boulettes de Viande Norvégiennes)',
        'pays': 'norway',
        'description': 'Les boulettes de bœuf et porc épicées à la muscade, servies avec une sauce brune, des pommes de terre et des airelles.',
        'temps_preparation': 20,
        'temps_cuisson': 25,
        'nb_personnes': 4,
        'difficulte': 'Facile',
        'ingredients': [
            '500 g de viande hachée (bœuf + porc)', '1 œuf', '100 ml de lait',
            '4 c. à soupe de chapelure', 'Muscade, poivre noir', 'Sel',
            '500 ml de bouillon de bœuf', 'Maïzena', 'Confiture d\'airelles (lingon)',
        ],
        'etapes': [
            'Mélanger viande hachée, œuf, lait, chapelure, muscade, sel et poivre.',
            'Former des boulettes rondes de 4 cm de diamètre.',
            'Faire dorer les boulettes dans une poêle huilée sur toutes faces.',
            'Retirer les boulettes. Faire la sauce : déglacer avec le bouillon.',
            'Lier la sauce avec la maïzena, rectifier l\'assaisonnement.',
            'Remettre les boulettes dans la sauce, mijoter 10 min.',
            'Servir avec pommes de terre et confiture d\'airelles.',
        ],
        'tags': ['Boulettes', 'Comfort food', 'Traditionnel', 'Hivernal'],
        'image_url': 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=800&q=80',
    },
    {
        'titre': 'Fiskesuppe (Soupe de Poisson Norvégienne)',
        'pays': 'norway',
        'description': 'Une soupe crémeuse aux fruits de mer et poissons blancs, parfumée à l\'aneth et au céleri-rave.',
        'temps_preparation': 20,
        'temps_cuisson': 25,
        'nb_personnes': 4,
        'difficulte': 'Facile',
        'ingredients': [
            '400 g de saumon', '300 g de cabillaud', '200 g de crevettes décortiquées',
            '2 carottes', '1 céleri-rave (200g)', '1 poireau',
            '300 ml de crème fraîche', '1 L de fumet de poisson', 'Aneth frais', 'Sel, poivre',
        ],
        'etapes': [
            'Couper les légumes en petits dés.',
            'Faire revenir poireau et carottes dans le beurre.',
            'Ajouter le fumet de poisson et le céleri-rave. Cuire 10 min.',
            'Ajouter la crème fraîche et porter à frémissement.',
            'Ajouter les poissons coupés en cubes et cuire 5 min.',
            'Ajouter les crevettes en fin de cuisson.',
            'Parsemer d\'aneth frais et servir avec du pain de seigle.',
        ],
        'tags': ['Soupe', 'Fruits de mer', 'Crémeux', 'Nordique'],
        'image_url': 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80',
    },

    # ── AUSTRIA ──────────────────────────────────────────────────────────────
    {
        'titre': 'Wiener Schnitzel',
        'pays': 'austria',
        'description': 'L\'escalope de veau panée de Vienne, croustillante et légère. Servie avec du citron et des pommes de terre sautées.',
        'temps_preparation': 20,
        'temps_cuisson': 10,
        'nb_personnes': 4,
        'difficulte': 'Moyen',
        'ingredients': [
            '4 escalopes de veau (150 g chacune)', '2 œufs', '100 g de chapelure fine',
            '80 g de farine', 'Beurre clarifié ou huile', 'Sel, poivre',
            '1 citron', 'Persil pour garnir',
        ],
        'etapes': [
            'Aplatir les escalopes à 4mm d\'épaisseur avec un rouleau.',
            'Saler et poivrer.',
            'Passer dans la farine, puis l\'œuf battu, puis la chapelure.',
            'Faire chauffer le beurre clarifié à feu moyen.',
            'Faire dorer les escalopes 3 min de chaque côté en arrosant de beurre.',
            'Égoutter sur papier absorbant.',
            'Servir immédiatement avec quartier de citron.',
        ],
        'tags': ['Veau', 'Pané', 'Vienne', 'Classique'],
        'image_url': 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=800&q=80',
    },
    {
        'titre': 'Tafelspitz',
        'pays': 'austria',
        'description': 'Le plat de fête viennois : pièce de bœuf pochée dans un bouillon de légumes, servie avec sauce raifort et épinards à la crème.',
        'temps_preparation': 20,
        'temps_cuisson': 180,
        'nb_personnes': 6,
        'difficulte': 'Moyen',
        'ingredients': [
            '1,5 kg de pièce de bœuf (tende de tranche)', '2 carottes', '1 céleri-branche',
            '2 oignons coupés en deux et rôtis', '1 poireau', 'Bouquet garni',
            'Raifort râpé', '200 ml de crème fraîche', 'Épinards frais', 'Sel',
        ],
        'etapes': [
            'Porter 3L d\'eau salée à ébullition avec les légumes et le bouquet garni.',
            'Plonger le bœuf et mijoter à frémissement 2h30 à 3h.',
            'Rôtir les demi-oignons à sec pour caraméliser et parfumer.',
            'Préparer la sauce raifort : mélanger raifort et crème fraîche, assaisonner.',
            'Faire revenir les épinards avec ail et crème fraîche.',
            'Trancher le bœuf et servir avec le bouillon chaud, la sauce et les épinards.',
        ],
        'tags': ['Bœuf poché', 'Vienne', 'Gastronomique', 'Traditionnel'],
        'image_url': 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80',
    },
    {
        'titre': 'Apfelstrudel',
        'pays': 'austria',
        'description': 'Le strudel aux pommes autrichien : pâte étirée ultra-fine enroulée autour des pommes à la cannelle et aux raisins secs.',
        'temps_preparation': 45,
        'temps_cuisson': 35,
        'nb_personnes': 8,
        'difficulte': 'Difficile',
        'ingredients': [
            '300 g de farine', '150 ml d\'eau tiède', '3 c. à soupe d\'huile',
            '1 kg de pommes acidulées (Granny Smith)', '100 g de sucre', '1 c. à café de cannelle',
            '80 g de raisins secs', '80 g de chapelure dorée au beurre',
            '60 g de beurre fondu', 'Sucre glace',
        ],
        'etapes': [
            'Pétrir farine, eau et huile en pâte lisse. Laisser reposer 30 min.',
            'Éplucher et trancher finement les pommes. Mélanger avec sucre, cannelle et raisins.',
            'Étaler la pâte sur un linge fariné, puis tirer délicatement à la main jusqu\'à transparence.',
            'Badigeonner de beurre fondu, parsemer de chapelure.',
            'Disposer la garniture pommes sur 1/3 de la pâte.',
            'Rouler à l\'aide du linge. Badigeonner à nouveau de beurre.',
            'Enfourner 30-35 min à 180°C. Saupoudrer de sucre glace.',
        ],
        'tags': ['Dessert', 'Pommes', 'Pâtisserie', 'Vienne'],
        'image_url': 'https://images.unsplash.com/photo-1586985289906-406988974504?w=800&q=80',
    },

    # ── SCOTLAND ─────────────────────────────────────────────────────────────
    {
        'titre': 'Haggis, Neeps & Tatties',
        'pays': 'scotland',
        'description': 'Le plat national écossais : haggis aux abats d\'agneau avec purée de navet (neeps) et pommes de terre (tatties).',
        'temps_preparation': 20,
        'temps_cuisson': 30,
        'nb_personnes': 4,
        'difficulte': 'Facile',
        'ingredients': [
            '1 haggis (400g — disponible en conserve)', '500 g de rutabaga (navet jaune)',
            '600 g de pommes de terre', '50 g de beurre', '50 ml de crème fraîche',
            'Whisky (pour déglacer)', 'Sel, poivre, muscade',
        ],
        'etapes': [
            'Cuire le haggis en conserve au bain-marie 30 min (ou pocher en baudruche).',
            'Cuire rutabaga et pommes de terre séparément à l\'eau salée.',
            'Écraser le rutabaga avec beurre, sel, poivre et muscade.',
            'Écraser les pommes de terre avec beurre et crème fraîche.',
            'Ouvrir le haggis et servir au centre de l\'assiette.',
            'Accompagner d\'une sauce au whisky (déglacage avec le jus de cuisson).',
        ],
        'tags': ['Burns Night', 'Traditionnel', 'Abats', 'Écossais'],
        'image_url': 'https://images.unsplash.com/photo-1585325701956-60dd9c8553bc?w=800&q=80',
    },
    {
        'titre': 'Cullen Skink',
        'pays': 'scotland',
        'description': 'Soupe crémeuse au haddock fumé et pommes de terre, originaire du village de Cullen sur la côte écossaise.',
        'temps_preparation': 15,
        'temps_cuisson': 25,
        'nb_personnes': 4,
        'difficulte': 'Facile',
        'ingredients': [
            '400 g de haddock fumé', '400 g de pommes de terre', '1 oignon',
            '500 ml de lait entier', '200 ml de crème fraîche', 'Beurre',
            'Persil frais', 'Sel, poivre',
        ],
        'etapes': [
            'Pocher le haddock dans le lait 10 min. Récupérer le lait et émietter le poisson.',
            'Faire revenir l\'oignon émincé dans le beurre.',
            'Ajouter les pommes de terre en dés et le lait de pochage.',
            'Cuire 15 min jusqu\'à tendreté des pommes de terre.',
            'Écraser légèrement quelques pommes de terre pour épaissir.',
            'Ajouter la crème et le haddock émietté. Chauffer sans bouillir.',
            'Parsemer de persil ciselé.',
        ],
        'tags': ['Soupe', 'Poisson fumé', 'Crémeux', 'Côte écossaise'],
        'image_url': 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80',
    },
    {
        'titre': 'Cranachan',
        'pays': 'scotland',
        'description': 'Dessert écossais traditionnel : crème fouettée au whisky et miel sur des framboises et de l\'avoine grillée.',
        'temps_preparation': 15,
        'temps_cuisson': 5,
        'nb_personnes': 4,
        'difficulte': 'Facile',
        'ingredients': [
            '300 ml de crème fraîche épaisse', '400 g de framboises fraîches',
            '100 g de flocons d\'avoine', '4 c. à soupe de miel de bruyère',
            '4 c. à soupe de whisky écossais',
        ],
        'etapes': [
            'Faire griller les flocons d\'avoine à sec dans une poêle jusqu\'à coloration.',
            'Fouetter la crème fraîche en chantilly.',
            'Incorporer délicatement le miel et le whisky à la crème.',
            'Dans des verres, alterner framboises, crème et avoine grillée.',
            'Terminer par une framboise et un filet de miel.',
            'Servir immédiatement ou réfrigérer 30 min.',
        ],
        'tags': ['Dessert', 'Whisky', 'Framboises', 'Burns Night'],
        'image_url': 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80',
    },

    # ── CZECHIA ──────────────────────────────────────────────────────────────
    {
        'titre': 'Svíčková na Smetaně',
        'pays': 'czechia',
        'description': 'Filet de bœuf braisé dans une sauce crémeuse aux légumes et épices, servi avec des knedlíky (quenelles de pain).',
        'temps_preparation': 30,
        'temps_cuisson': 120,
        'nb_personnes': 4,
        'difficulte': 'Difficile',
        'ingredients': [
            '800 g de filet de bœuf', '2 carottes', '1 céleri-rave', '2 oignons',
            '300 ml de crème fraîche', '200 ml de bouillon de bœuf',
            'Thym, laurier, graines de moutarde', 'Vinaigre de vin blanc',
            'Confiture d\'airelles', 'Knedlíky (quenelles tchèques)',
        ],
        'etapes': [
            'Faire revenir le filet de bœuf sur toutes faces. Réserver.',
            'Faire revenir les légumes coupés en cubes dans la même cocotte.',
            'Remettre le bœuf, ajouter épices, bouillon et couvrir.',
            'Braiser 1h30 à 160°C au four.',
            'Sortir le bœuf, mixer la sauce aux légumes et crémer.',
            'Trancher la viande et la napper de sauce.',
            'Servir avec les knedlíky et de la confiture d\'airelles.',
        ],
        'tags': ['Bœuf braisé', 'Praguois', 'Festif', 'Traditionnel'],
        'image_url': 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80',
    },
    {
        'titre': 'Trdelník',
        'pays': 'czechia',
        'description': 'Le gâteau de cheminée tchèque : pâte enroulée autour d\'un bâton, grillée et roulée dans le sucre et la cannelle.',
        'temps_preparation': 30,
        'temps_cuisson': 15,
        'nb_personnes': 6,
        'difficulte': 'Moyen',
        'ingredients': [
            '400 g de farine', '200 ml de lait tiède', '7 g de levure sèche',
            '60 g de sucre', '1 œuf', '50 g de beurre mou',
            '100 g de sucre + 2 c. à café de cannelle (pour rouler)',
            'Noix concassées (optionnel)',
        ],
        'etapes': [
            'Préparer la pâte levée : mélanger tous les ingrédients, pétrir 10 min.',
            'Laisser lever 1h.',
            'Former de longs boudins de pâte.',
            'Enrouler en spirale serrée autour de rouleaux en bois beurrés.',
            'Griller au four ou sur braise en tournant régulièrement.',
            'Rouler immédiatement dans le mélange sucre-cannelle.',
        ],
        'tags': ['Street food', 'Dessert', 'Prague', 'Sucré'],
        'image_url': 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&q=80',
    },
    {
        'titre': 'Guláš Tchèque',
        'pays': 'czechia',
        'description': 'Le goulasch à la tchèque : bœuf mijoté au paprika et bière brune, servi avec des knedlíky pour tremper dans la sauce.',
        'temps_preparation': 20,
        'temps_cuisson': 120,
        'nb_personnes': 4,
        'difficulte': 'Facile',
        'ingredients': [
            '1 kg de paleron de bœuf', '4 oignons', '3 c. à soupe de paprika doux',
            '1 c. à café de paprika fort', '500 ml de bière brune tchèque',
            '2 gousses d\'ail', 'Saindoux ou beurre', 'Sel, poivre, cumin',
        ],
        'etapes': [
            'Faire fondre les oignons dans le saindoux jusqu\'à caramélisation.',
            'Ajouter le paprika, cumin et ail. Faire revenir 1 min.',
            'Ajouter le bœuf en cubes, faire revenir sur toutes faces.',
            'Verser la bière brune, saler et poivrer.',
            'Mijoter 1h30 à 2h à feu doux jusqu\'à sauce bien liée.',
            'Servir avec des knedlíky (ou pain de campagne).',
        ],
        'tags': ['Mijoté', 'Bière', 'Paprika', 'Plat national'],
        'image_url': 'https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=800&q=80',
    },

    # ── TURKEY ───────────────────────────────────────────────────────────────
    {
        'titre': 'Kebab Adana',
        'pays': 'turkey',
        'description': 'Brochette de viande hachée épicée à la piment rouge, spécialité de la ville d\'Adana dans le sud de la Turquie.',
        'temps_preparation': 20,
        'temps_cuisson': 15,
        'nb_personnes': 4,
        'difficulte': 'Moyen',
        'ingredients': [
            '600 g d\'agneau haché (ou bœuf-agneau)', '1 oignon râpé',
            '2 c. à café de piment rouge turc (pul biber)', '1 c. à café de cumin',
            'Persil frais haché', 'Sel', 'Brochettes larges plates',
            'Lavash (pain turc), tomates, persil, oignon pour servir',
        ],
        'etapes': [
            'Mélanger viande, oignon râpé, épices, persil et sel.',
            'Pétrir vigoureusement 5 min jusqu\'à texture collante.',
            'Réfrigérer 30 min.',
            'Humidifier les mains et former des boudins autour des brochettes.',
            'Griller au barbecue ou sous le grill 12-15 min en retournant.',
            'Servir enroulé dans le lavash avec tomates, persil et oignon.',
        ],
        'tags': ['Grill', 'Agneau', 'Épicé', 'Street food'],
        'image_url': 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=800&q=80',
    },
    {
        'titre': 'Manti (Raviolis Turcs)',
        'pays': 'turkey',
        'description': 'Minuscules raviolis à la viande nappés de yaourt à l\'ail et de beurre au piment — le plat des grandes occasions en Turquie.',
        'temps_preparation': 60,
        'temps_cuisson': 15,
        'nb_personnes': 4,
        'difficulte': 'Difficile',
        'ingredients': [
            '300 g de farine', '2 œufs', '80 ml d\'eau', 'Sel',
            '250 g de viande hachée d\'agneau', '1 oignon râpé',
            '500 g de yaourt grec', '3 gousses d\'ail',
            '50 g de beurre', '1 c. à café de paprika + piment',
        ],
        'etapes': [
            'Préparer la pâte : mélanger farine, œufs, eau et sel. Reposer 30 min.',
            'Faire la farce : mélanger viande, oignon, sel et poivre.',
            'Étaler la pâte très finement, découper en carrés de 3 cm.',
            'Déposer une noisette de farce et fermer en aumônière.',
            'Cuire à l\'eau bouillante salée 10-12 min.',
            'Mélanger yaourt et ail écrasé.',
            'Napper les manti de yaourt et de beurre fondu épicé.',
        ],
        'tags': ['Pâtes', 'Raviolis', 'Festif', 'Traditionnel'],
        'image_url': 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=800&q=80',
    },
    {
        'titre': 'Baklava',
        'pays': 'turkey',
        'description': 'Le dessert ottoman par excellence : feuilles de filo croustillantes, noix et pistaches, sirop de miel et eau de rose.',
        'temps_preparation': 40,
        'temps_cuisson': 40,
        'nb_personnes': 20,
        'difficulte': 'Moyen',
        'ingredients': [
            '500 g de feuilles de filo', '300 g de beurre clarifié',
            '300 g de pistaches non salées broyées', '200 g de noix broyées',
            '400 g de sucre', '300 ml d\'eau', '2 c. à soupe de miel',
            '1 c. à soupe d\'eau de rose',
        ],
        'etapes': [
            'Préparer le sirop : faire bouillir sucre et eau 15 min. Ajouter miel et eau de rose. Refroidir.',
            'Beurrer un plat, alterner 8 feuilles de filo beurrées.',
            'Déposer la couche de pistaches et noix mélangées.',
            'Couvrir de 8 autres feuilles de filo beurrées.',
            'Découper en losanges avant la cuisson.',
            'Enfourner 35-40 min à 170°C jusqu\'à dorure.',
            'Verser le sirop froid sur le baklava chaud. Laisser absorber 4h.',
        ],
        'tags': ['Dessert', 'Pistaches', 'Pâtisserie ottomane', 'Sucré'],
        'image_url': 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=800&q=80',
    },

    # ── UKRAINE ──────────────────────────────────────────────────────────────
    {
        'titre': 'Bortsch Ukrainien',
        'pays': 'ukraine',
        'description': 'La soupe à la betterave rouge emblématique de l\'Ukraine — rouge vif, acidulée et nourrie au chou et à la viande.',
        'temps_preparation': 30,
        'temps_cuisson': 90,
        'nb_personnes': 6,
        'difficulte': 'Moyen',
        'ingredients': [
            '500 g de bœuf (poitrine)', '3 betteraves moyennes', '300 g de chou blanc',
            '3 pommes de terre', '2 carottes', '2 oignons', '1 tomate',
            'Vinaigre de vin blanc', 'Crème fraîche', 'Aneth', 'Sel, poivre',
        ],
        'etapes': [
            'Faire un bouillon avec le bœuf 1h. Réserver la viande et le bouillon.',
            'Râper les betteraves et les faire revenir avec vinaigre et tomate.',
            'Ajouter oignons et carottes émincés dans le bouillon.',
            'Ajouter pommes de terre en dés et chou émincé.',
            'Incorporer les betteraves en fin de cuisson. Mijoter 20 min.',
            'Ajouter la viande effilochée. Rectifier l\'assaisonnement.',
            'Servir avec crème fraîche et aneth ciselé.',
        ],
        'tags': ['Soupe', 'Betterave', 'Plat national', 'Hivernal'],
        'image_url': 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80',
    },
    {
        'titre': 'Varenyky (Raviolis Ukrainiens)',
        'pays': 'ukraine',
        'description': 'Les raviolis farcis à la pomme de terre et fromage blanc, bouillis et sautés au beurre avec des oignons dorés.',
        'temps_preparation': 45,
        'temps_cuisson': 20,
        'nb_personnes': 4,
        'difficulte': 'Moyen',
        'ingredients': [
            '400 g de farine', '200 ml d\'eau tiède', '1 œuf', 'Sel',
            '600 g de pommes de terre', '200 g de fromage blanc', '1 oignon',
            'Beurre', 'Crème fraîche',
        ],
        'etapes': [
            'Préparer la pâte : mélanger farine, eau, œuf et sel. Laisser reposer 30 min.',
            'Cuire et écraser les pommes de terre avec fromage blanc, sel et poivre.',
            'Étaler la pâte finement, découper des ronds de 8 cm.',
            'Déposer une cuillère de farce et plier en demi-lune. Bien souder.',
            'Cuire à l\'eau bouillante salée 5 min.',
            'Faire dorer les oignons émincés dans le beurre.',
            'Faire sauter les varenyky dans le beurre aux oignons. Servir avec crème fraîche.',
        ],
        'tags': ['Pâtes', 'Comfort food', 'Végétarien', 'Traditionnel'],
        'image_url': 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=800&q=80',
    },
    {
        'titre': 'Chicken Kyiv',
        'pays': 'ukraine',
        'description': 'Suprême de poulet farci au beurre à l\'ail et aux herbes, pané et frit — un classique mondial né à Kiev.',
        'temps_preparation': 30,
        'temps_cuisson': 20,
        'nb_personnes': 4,
        'difficulte': 'Moyen',
        'ingredients': [
            '4 blancs de poulet', '150 g de beurre mou', '4 gousses d\'ail',
            'Persil et ciboulette frais', '2 œufs', '150 g de chapelure',
            '80 g de farine', 'Huile de friture', 'Sel, poivre',
        ],
        'etapes': [
            'Mélanger beurre, ail écrasé, herbes, sel et poivre. Former un boudin et congeler 30 min.',
            'Aplatir les blancs de poulet entre deux films alimentaires.',
            'Déposer un tronçon de beurre aux herbes au centre de chaque blanc.',
            'Rouler serré en enfermant le beurre. Ficeler ou maintenir au froid 1h.',
            'Passer dans farine, œuf battu, chapelure.',
            'Frire 4 min à 180°C puis finir 10 min au four à 180°C.',
        ],
        'tags': ['Poulet', 'Farci', 'Pané', 'Kiev'],
        'image_url': 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=800&q=80',
    },

    # ── DENMARK ──────────────────────────────────────────────────────────────
    {
        'titre': 'Smørrebrød au Hareng',
        'pays': 'denmark',
        'description': 'La tartine ouverte danoise : pain de seigle noir beurré garni de harengs marinés, œuf et ciboulette.',
        'temps_preparation': 15,
        'temps_cuisson': 0,
        'nb_personnes': 4,
        'difficulte': 'Facile',
        'ingredients': [
            '8 tranches de pain de seigle dense', '100 g de beurre doux',
            '200 g de harengs marinés (rollmops)', '4 œufs cuits dur',
            'Ciboulette fraîche', 'Câpres', 'Crème fraîche', 'Aneth',
        ],
        'etapes': [
            'Beurrer généreusement les tranches de pain de seigle.',
            'Disposer les filets de hareng mariné sur chaque tranche.',
            'Trancher les œufs durs et les répartir.',
            'Ajouter des câpres et une noisette de crème fraîche.',
            'Parsemer de ciboulette et aneth ciselés.',
            'Servir sans attendre comme plat principal ou entrée.',
        ],
        'tags': ['Tartine', 'Hareng', 'Danois', 'Sans cuisson'],
        'image_url': 'https://images.unsplash.com/photo-1519864600265-abb23847ef2c?w=800&q=80',
    },
    {
        'titre': 'Frikadeller (Boulettes Danoises)',
        'pays': 'denmark',
        'description': 'Les boulettes de viande plates danoises, mélange de porc et veau, frites au beurre — le plat comfort de chaque foyer.',
        'temps_preparation': 20,
        'temps_cuisson': 20,
        'nb_personnes': 4,
        'difficulte': 'Facile',
        'ingredients': [
            '400 g de porc haché', '200 g de veau haché', '1 oignon râpé',
            '1 œuf', '100 ml de lait', '4 c. à soupe de farine',
            'Beurre pour la cuisson', 'Sel, poivre, allspice (toutes épices)',
        ],
        'etapes': [
            'Mélanger viandes, oignon, œuf, farine, lait et épices.',
            'Laisser reposer 15 min au réfrigérateur.',
            'Avec une cuillère humide, former des quenelles ovales aplaties.',
            'Faire chauffer beurre dans une poêle à feu moyen.',
            'Cuire les frikadeller 4 min de chaque côté jusqu\'à dorure.',
            'Servir avec purée de pommes de terre et sauce brune ou cornichons.',
        ],
        'tags': ['Boulettes', 'Porc', 'Comfort food', 'Traditionnel'],
        'image_url': 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=800&q=80',
    },
    {
        'titre': 'Æbleskiver',
        'pays': 'denmark',
        'description': 'Les petites crêpes sphériques danoises de Noël, servies chaudes avec de la confiture de prune et du sucre glace.',
        'temps_preparation': 15,
        'temps_cuisson': 20,
        'nb_personnes': 6,
        'difficulte': 'Moyen',
        'ingredients': [
            '300 g de farine', '3 œufs', '450 ml de lait', '1 c. à café de levure',
            '1 c. à café de cardamome', '2 c. à soupe de sucre', 'Beurre',
            'Confiture de prune, sucre glace pour servir',
        ],
        'etapes': [
            'Séparer blancs et jaunes.',
            'Mélanger jaunes, farine, lait, sucre, cardamome et levure.',
            'Monter les blancs en neige et les incorporer délicatement.',
            'Chauffer la poêle à æbleskiver (ou poêle à blinis) avec un peu de beurre.',
            'Remplir chaque creux, laisser coaguler le fond.',
            'Retourner à l\'aide d\'une brochette pour former une sphère.',
            'Servir avec confiture de prune et sucre glace.',
        ],
        'tags': ['Dessert', 'Noël', 'Douceur', 'Traditionnel'],
        'image_url': 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&q=80',
    },

    # ── SWITZERLAND ──────────────────────────────────────────────────────────
    {
        'titre': 'Fondue au Fromage',
        'pays': 'switzerland',
        'description': 'La fondue classique moitié-moitié (Gruyère et Vacherin fribourgeois) au vin blanc et kirsch.',
        'temps_preparation': 15,
        'temps_cuisson': 20,
        'nb_personnes': 4,
        'difficulte': 'Facile',
        'ingredients': [
            '400 g de Gruyère râpé', '400 g de Vacherin fribourgeois râpé',
            '300 ml de vin blanc sec (Fendant)', '2 c. à soupe de kirsch',
            '1 gousse d\'ail', '1 c. à soupe de maïzena',
            'Poivre blanc, muscade', 'Pain blanc rassis en cubes',
        ],
        'etapes': [
            'Frotter le caquelon avec la gousse d\'ail coupée.',
            'Verser le vin blanc et chauffer à feu doux sans bouillir.',
            'Ajouter les fromages râpés progressivement en remuant en 8.',
            'Délayer la maïzena dans le kirsch et incorporer.',
            'Assaisonner de poivre blanc et muscade.',
            'Maintenir à frémissement et tremper les cubes de pain.',
        ],
        'tags': ['Fromage', 'Hivernal', 'Convivial', 'Alpes'],
        'image_url': 'https://images.unsplash.com/photo-1576867757603-05b134ebc379?w=800&q=80',
    },
    {
        'titre': 'Rösti Zurichois',
        'pays': 'switzerland',
        'description': 'La galette de pommes de terre grillée et croustillante de Zurich — le plat paysan suisse alémanique.',
        'temps_preparation': 20,
        'temps_cuisson': 25,
        'nb_personnes': 4,
        'difficulte': 'Facile',
        'ingredients': [
            '800 g de pommes de terre (cuites la veille)', '80 g de beurre',
            '1 oignon (optionnel)', 'Sel, poivre',
        ],
        'etapes': [
            'Éplucher et râper grossièrement les pommes de terre froides.',
            'Assaisonner avec sel et poivre. Mélanger avec oignon râpé si souhaité.',
            'Faire fondre la moitié du beurre dans une poêle à feu moyen.',
            'Verser les pommes de terre râpées et presser en galette compacte.',
            'Cuire 12 min jusqu\'à croûte dorée. Retourner à l\'aide d\'une assiette.',
            'Ajouter le reste du beurre et cuire 12 min de l\'autre côté.',
        ],
        'tags': ['Pomme de terre', 'Suisse alémanique', 'Accompagnement', 'Rapide'],
        'image_url': 'https://images.unsplash.com/photo-1585325701956-60dd9c8553bc?w=800&q=80',
    },
    {
        'titre': 'Zürcher Geschnetzeltes',
        'pays': 'switzerland',
        'description': 'Émincé de veau à la zurichoise : fines lanières de veau en sauce crémeuse au vin blanc et champignons.',
        'temps_preparation': 20,
        'temps_cuisson': 20,
        'nb_personnes': 4,
        'difficulte': 'Moyen',
        'ingredients': [
            '600 g de filet de veau', '300 g de champignons de Paris',
            '2 échalotes', '150 ml de vin blanc', '200 ml de crème fraîche',
            '50 ml de fond de veau', 'Beurre', 'Sel, poivre, persil',
        ],
        'etapes': [
            'Couper le veau en fines lanières.',
            'Faire sauter à feu vif dans le beurre par petites quantités. Réserver.',
            'Faire revenir échalotes et champignons dans le même beurre.',
            'Déglacer au vin blanc et réduire de moitié.',
            'Ajouter crème fraîche et fond de veau. Mijoter 5 min.',
            'Remettre le veau. Chauffer sans recuire.',
            'Parsemer de persil et servir avec du rösti.',
        ],
        'tags': ['Veau', 'Zurich', 'Crémeux', 'Gastronomique'],
        'image_url': 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80',
    },

    # ── MONACO ───────────────────────────────────────────────────────────────
    {
        'titre': 'Barbagiuan Monégasque',
        'pays': 'monaco',
        'description': 'Les beignets croustillants de Monaco farcis aux blettes, ricotta et parmesan — l\'en-cas typique de la principauté.',
        'temps_preparation': 40,
        'temps_cuisson': 15,
        'nb_personnes': 6,
        'difficulte': 'Moyen',
        'ingredients': [
            '300 g de farine', '1 œuf', '150 ml d\'eau', '50 ml d\'huile d\'olive',
            '400 g de blettes (feuilles uniquement)', '200 g de ricotta',
            '80 g de parmesan râpé', '1 oignon', 'Huile de friture', 'Sel, poivre',
        ],
        'etapes': [
            'Préparer la pâte : mélanger farine, œuf, eau et huile. Reposer 30 min.',
            'Blanchir les blettes 3 min, égoutter et hacher finement.',
            'Faire revenir l\'oignon, ajouter les blettes. Laisser refroidir.',
            'Mélanger blettes, ricotta, parmesan, sel et poivre.',
            'Étaler la pâte finement, découper des ronds de 8 cm.',
            'Garnir d\'une cuillerée de farce, plier et souder les bords.',
            'Frire à 180°C 3-4 min jusqu\'à dorure. Égoutter et servir chaud.',
        ],
        'tags': ['Beignets', 'Apéro', 'Monaco', 'Traditionnel'],
        'image_url': 'https://images.unsplash.com/photo-1572453800999-e8d2d1589b7c?w=800&q=80',
    },
    {
        'titre': 'Stocafi à la Monégasque',
        'pays': 'monaco',
        'description': 'Stockfisch (morue séchée) mijoté à la tomate avec olives, pignons et herbes — le plat de fête de Monaco.',
        'temps_preparation': 30,
        'temps_cuisson': 90,
        'nb_personnes': 6,
        'difficulte': 'Moyen',
        'ingredients': [
            '800 g de stockfisch dessalé et trempé 48h', '800 g de tomates concassées',
            '100 g d\'olives noires de Nice', '50 g de pignons de pin',
            '3 gousses d\'ail', '2 oignons', 'Basilic frais', 'Huile d\'olive',
            'Sel, poivre', 'Pommes de terre (optionnel)',
        ],
        'etapes': [
            'Couper le stockfisch en morceaux, bien égoutter.',
            'Faire revenir oignons et ail dans l\'huile d\'olive.',
            'Ajouter les tomates concassées et mijoter 10 min.',
            'Ajouter les morceaux de stockfisch, couvrir.',
            'Mijoter à feu très doux 1h en remuant délicatement.',
            'Ajouter olives et pignons 15 min avant la fin.',
            'Parsemer de basilic frais. Servir avec pommes de terre vapeur.',
        ],
        'tags': ['Poisson', 'Méditerranéen', 'Mijoté', 'Festif'],
        'image_url': 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80',
    },
    {
        'titre': 'Socca Niçoise',
        'pays': 'monaco',
        'description': 'La galette de farine de pois chiches cuite au four à bois, croustillante à l\'extérieur et moelleuse à l\'intérieur — street food de la Côte d\'Azur.',
        'temps_preparation': 10,
        'temps_cuisson': 15,
        'nb_personnes': 4,
        'difficulte': 'Facile',
        'ingredients': [
            '200 g de farine de pois chiches', '400 ml d\'eau',
            '4 c. à soupe d\'huile d\'olive', 'Sel, poivre noir',
            'Romarin frais (optionnel)',
        ],
        'etapes': [
            'Fouetter farine de pois chiches, eau et sel jusqu\'à pâte lisse.',
            'Ajouter 3 c. à soupe d\'huile d\'olive. Laisser reposer 30 min.',
            'Préchauffer le four à 250°C avec une plaque en fonte.',
            'Verser l\'huile restante sur la plaque brûlante, puis la pâte.',
            'Enfourner 10-12 min jusqu\'à bords grillés et surface dorée.',
            'Poivrer généreusement à la sortie et servir brûlant.',
        ],
        'tags': ['Végétarien', 'Gluten-free', 'Street food', 'Méditerranéen'],
        'image_url': 'https://images.unsplash.com/photo-1506354666786-959d6d497f1a?w=800&q=80',
    },

    # ── AZERBAIJAN ───────────────────────────────────────────────────────────
    {
        'titre': 'Plov Azerbaïdjanais',
        'pays': 'azerbaijan',
        'description': 'Le riz pilaf national d\'Azerbaïdjan : riz au safran sur une croûte de pain (gazmakh) avec agneau, fruits secs et épices.',
        'temps_preparation': 30,
        'temps_cuisson': 90,
        'nb_personnes': 6,
        'difficulte': 'Difficile',
        'ingredients': [
            '500 g de riz basmati', '600 g d\'agneau en cubes', '1 oignon',
            '100 g d\'abricots secs', '50 g de raisins secs', '50 g de prunes séchées',
            '0,5 g de safran', '150 g de beurre', '1 galette de lavash (pour le gazmakh)',
            'Cannelle, cumin, sel',
        ],
        'etapes': [
            'Faire tremper le riz 30 min. Cuire à l\'eau bouillante salée jusqu\'à mi-cuisson.',
            'Faire revenir l\'agneau et l\'oignon dans le beurre.',
            'Ajouter fruits secs, cannelle et cumin. Mijoter 30 min.',
            'Beurrer une casserole, tapisser le fond de lavash (gazmakh).',
            'Verser la moitié du riz, puis le mélange agneau-fruits, puis le reste du riz.',
            'Dissoudre le safran dans 2 c. d\'eau chaude, verser sur le riz.',
            'Cuire à feu très doux 40 min couvert d\'un torchon sous le couvercle.',
        ],
        'tags': ['Riz', 'Agneau', 'Safran', 'Festif'],
        'image_url': 'https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=800&q=80',
    },
    {
        'titre': 'Dolma à la Feuille de Vigne',
        'pays': 'azerbaijan',
        'description': 'Feuilles de vigne farcies au riz, agneau haché et herbes fraîches, cuites à la vapeur et servies avec du yaourt.',
        'temps_preparation': 45,
        'temps_cuisson': 45,
        'nb_personnes': 4,
        'difficulte': 'Moyen',
        'ingredients': [
            '30 feuilles de vigne (en saumure, rincées)', '300 g d\'agneau haché',
            '150 g de riz rond', '1 oignon', 'Menthe, persil, ciboulette',
            '1 c. à café de cannelle', '1 c. à café de cumin',
            'Beurre', 'Yaourt grec pour servir', 'Sel, poivre',
        ],
        'etapes': [
            'Mélanger agneau, riz cru, oignon râpé, herbes et épices.',
            'Déposer une cuillerée de farce au centre de chaque feuille de vigne.',
            'Rabattre les côtés et rouler serré.',
            'Tapisser le fond d\'une casserole de feuilles de vigne non farcies.',
            'Ranger les dolma bien serrés. Couvrir d\'eau chaude et d\'une assiette.',
            'Mijoter à feu doux 40-45 min.',
            'Servir chaud avec yaourt grec et menthe fraîche.',
        ],
        'tags': ['Farcis', 'Agneau', 'Végétal', 'Méditerranéen'],
        'image_url': 'https://images.unsplash.com/photo-1572453800999-e8d2d1589b7c?w=800&q=80',
    },
    {
        'titre': 'Dushbara (Soupe aux Petits Raviolis)',
        'pays': 'azerbaijan',
        'description': 'Une soupe légère au bouillon d\'agneau avec de minuscules raviolis farcis à la viande, typique des hivers azerbaïdjanais.',
        'temps_preparation': 60,
        'temps_cuisson': 30,
        'nb_personnes': 4,
        'difficulte': 'Difficile',
        'ingredients': [
            '200 g de farine', '1 œuf', '60 ml d\'eau froide',
            '250 g d\'agneau haché', '1 oignon haché',
            '1 L de bouillon d\'agneau clair', 'Menthe séchée',
            'Vinaigre de vin blanc', 'Sel, poivre',
        ],
        'etapes': [
            'Préparer la pâte ferme. Laisser reposer 30 min.',
            'Mélanger agneau, oignon, sel et poivre pour la farce.',
            'Étaler la pâte très finement (1 mm).',
            'Découper en minuscules carrés de 2 cm.',
            'Déposer une infime quantité de farce et fermer en triangle.',
            'Porter le bouillon à ébullition. Y cuire les dushbara 5 min.',
            'Servir avec menthe séchée et un filet de vinaigre.',
        ],
        'tags': ['Soupe', 'Raviolis', 'Hivernal', 'Traditionnel'],
        'image_url': 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80',
    },

    # ── CROATIA ──────────────────────────────────────────────────────────────
    {
        'titre': 'Peka (Agneau sous la Cloche)',
        'pays': 'croatia',
        'description': 'Agneau et légumes cuits lentement sous une cloche en fonte remplie de braises — la cuisson traditionnelle dalmato-croate.',
        'temps_preparation': 30,
        'temps_cuisson': 120,
        'nb_personnes': 6,
        'difficulte': 'Moyen',
        'ingredients': [
            '1,5 kg d\'agneau en morceaux', '600 g de pommes de terre',
            '3 carottes', '2 courgettes', '2 oignons', '6 gousses d\'ail',
            '200 ml de vin blanc', '100 ml d\'huile d\'olive',
            'Romarin, thym', 'Sel, poivre',
        ],
        'etapes': [
            'Disposer l\'agneau et les légumes grossièrement coupés dans le plat peka.',
            'Arroser d\'huile d\'olive et de vin blanc.',
            'Parsemer d\'ail entier, romarin et thym. Assaisonner.',
            'Couvrir de la cloche en fonte (ou couvercle hermétique).',
            'Cuire 2h à four doux (160°C) ou sur braises.',
            'Ouvrir en fin de cuisson pour caraméliser 15 min.',
        ],
        'tags': ['Agneau', 'Cuisson lente', 'Dalmatie', 'Festif'],
        'image_url': 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80',
    },
    {
        'titre': 'Brudet de Poisson Dalmate',
        'pays': 'croatia',
        'description': 'Ragoût de poissons mixtes à la tomate et au vin blanc, spécialité des pêcheurs de la côte dalmate.',
        'temps_preparation': 20,
        'temps_cuisson': 30,
        'nb_personnes': 4,
        'difficulte': 'Moyen',
        'ingredients': [
            '1 kg de poissons mixtes (loup, dorade, rouget)', '400 g de tomates concassées',
            '1 oignon', '4 gousses d\'ail', '200 ml de vin blanc',
            'Huile d\'olive', 'Persil frais', 'Sel, poivre',
        ],
        'etapes': [
            'Faire revenir l\'oignon et l\'ail dans l\'huile d\'olive.',
            'Ajouter les tomates et le vin blanc. Mijoter 10 min.',
            'Déposer les poissons entiers ou en gros morceaux dans la sauce.',
            'Couvrir et cuire à feu doux 20 min sans remuer (les poissons sont fragiles).',
            'Parsemer de persil ciselé.',
            'Servir avec polenta ou pain blanc pour tremper.',
        ],
        'tags': ['Poisson', 'Dalmatie', 'Méditerranéen', 'Côte'],
        'image_url': 'https://images.unsplash.com/photo-1519864600265-abb23847ef2c?w=800&q=80',
    },
    {
        'titre': 'Strukli Zagrébiote',
        'pays': 'croatia',
        'description': 'Pâte farcie au fromage blanc et crème fraîche, bouillie ou gratinée au four — le comfort food de Zagreb.',
        'temps_preparation': 40,
        'temps_cuisson': 30,
        'nb_personnes': 4,
        'difficulte': 'Moyen',
        'ingredients': [
            '400 g de farine', '2 œufs', '150 ml d\'eau tiède',
            '500 g de fromage blanc frais', '2 œufs (pour la farce)',
            '200 ml de crème fraîche', '50 g de beurre', 'Sel',
        ],
        'etapes': [
            'Pétrir farine, œufs et eau en pâte souple. Reposer 30 min.',
            'Mélanger fromage blanc, œufs et sel pour la farce.',
            'Étaler la pâte finement sur un linge fariné.',
            'Répartir la farce sur la surface, rouler en boudin.',
            'Cuire à l\'eau bouillante salée 20 min.',
            'Couper en tronçons, disposer dans un plat beurré.',
            'Napper de crème fraîche et gratiner 10 min à 200°C.',
        ],
        'tags': ['Pâtes', 'Fromage', 'Zagreb', 'Gratin'],
        'image_url': 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=800&q=80',
    },

    # ── SERBIA ───────────────────────────────────────────────────────────────
    {
        'titre': 'Ćevapčići',
        'pays': 'serbia',
        'description': 'Petites saucisses grillées sans boyau mélange bœuf-porc-agneau, servies avec kajmak, ajvar et oignons.',
        'temps_preparation': 20,
        'temps_cuisson': 15,
        'nb_personnes': 4,
        'difficulte': 'Facile',
        'ingredients': [
            '400 g de bœuf haché', '200 g de porc haché', '200 g d\'agneau haché',
            '1 oignon', '3 gousses d\'ail', '1 c. à café de paprika',
            '1 c. à café de bicarbonate', 'Sel, poivre',
            'Kajmak (crème épaisse), ajvar (caviar d\'aubergine), pain lepinja',
        ],
        'etapes': [
            'Mélanger les trois viandes avec oignon et ail finement hachés.',
            'Ajouter paprika, bicarbonate, sel et poivre.',
            'Pétrir vigoureusement 5 min.',
            'Réfrigérer 2h minimum.',
            'Former des petits cylindres de 7 cm avec les mains humides.',
            'Griller au barbecue ou à la poêle 3 min de chaque côté.',
            'Servir dans le lepinja avec kajmak, ajvar et oignons crus.',
        ],
        'tags': ['Grill', 'Balkans', 'Street food', 'Viande'],
        'image_url': 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=800&q=80',
    },
    {
        'titre': 'Pasulj (Soupe de Haricots)',
        'pays': 'serbia',
        'description': 'La soupe de haricots blancs fumée serbe avec saucisse et lard — le plat du dimanche dans chaque famille.',
        'temps_preparation': 20,
        'temps_cuisson': 120,
        'nb_personnes': 6,
        'difficulte': 'Facile',
        'ingredients': [
            '500 g de haricots blancs secs (trempés la veille)', '200 g de saucisse fumée',
            '150 g de lard fumé', '2 oignons', '3 gousses d\'ail',
            '2 c. à soupe de paprika doux', 'Huile', 'Sel, poivre, laurier',
        ],
        'etapes': [
            'Cuire les haricots trempés dans l\'eau froide 1h à 1h30.',
            'Faire revenir oignons et lard dans l\'huile.',
            'Ajouter paprika et ail. Verser dans la marmite de haricots.',
            'Ajouter la saucisse fumée en rondelles.',
            'Mijoter encore 30 min jusqu\'à haricots très fondants.',
            'Rectifier l\'assaisonnement. Servir avec du pain de campagne.',
        ],
        'tags': ['Soupe', 'Haricots', 'Fumé', 'Hivernal'],
        'image_url': 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80',
    },
    {
        'titre': 'Sarma (Chou Farci Serbe)',
        'pays': 'serbia',
        'description': 'Feuilles de chou fermenté farcies de viande hachée et riz, mijotées dans la choucroute — le plat de fête serbe.',
        'temps_preparation': 45,
        'temps_cuisson': 120,
        'nb_personnes': 8,
        'difficulte': 'Moyen',
        'ingredients': [
            '16 grandes feuilles de chou fermenté (kiseli kupus)', '500 g de viande hachée mixte',
            '200 g de riz', '1 oignon', '2 gousses d\'ail', '1 c. à café de paprika',
            '200 g de lard fumé', '400 g de choucroute (fond de cuve)',
            'Beurre, sel, poivre',
        ],
        'etapes': [
            'Mélanger viande, riz cru, oignon, ail, paprika, sel et poivre.',
            'Déposer 2 cuillères de farce sur chaque feuille de chou.',
            'Rouler en serrant bien et tucke les extrémités.',
            'Tapisser le fond d\'une grande cocotte de choucroute.',
            'Ranger les sarma bien serrés. Ajouter le lard fumé.',
            'Couvrir d\'eau, mijoter 1h30 à feu doux.',
        ],
        'tags': ['Chou farci', 'Festif', 'Hivernal', 'Traditionnel'],
        'image_url': 'https://images.unsplash.com/photo-1572453800999-e8d2d1589b7c?w=800&q=80',
    },

    # ── GREECE ───────────────────────────────────────────────────────────────
    {
        'titre': 'Moussaka',
        'pays': 'greece',
        'description': 'Le gratin grec à l\'aubergine : couches d\'aubergines grillées, viande hachée épicée et béchamel crémeuse.',
        'temps_preparation': 45,
        'temps_cuisson': 60,
        'nb_personnes': 6,
        'difficulte': 'Moyen',
        'ingredients': [
            '3 aubergines', '600 g de viande hachée d\'agneau', '2 oignons',
            '400 g de tomates concassées', 'Cannelle, allspice',
            '600 ml de béchamel (lait, beurre, farine)', '2 œufs',
            '100 g de parmesan râpé', 'Huile d\'olive', 'Sel, poivre',
        ],
        'etapes': [
            'Trancher et faire griller les aubergines à l\'huile. Égoutter.',
            'Faire revenir oignon et viande. Ajouter tomates, cannelle et allspice. Mijoter 20 min.',
            'Préparer une béchamel épaisse, incorporer les œufs hors du feu.',
            'Dans un plat beurré, alterner : couche d\'aubergines, couche de viande.',
            'Terminer par la béchamel, saupoudrer de parmesan.',
            'Enfourner 45 min à 180°C jusqu\'à dorure.',
            'Laisser reposer 15 min avant de servir.',
        ],
        'tags': ['Gratin', 'Aubergine', 'Agneau', 'Plat national'],
        'image_url': 'https://images.unsplash.com/photo-1572453800999-e8d2d1589b7c?w=800&q=80',
    },
    {
        'titre': 'Spanakopita',
        'pays': 'greece',
        'description': 'La tourte feuilletée aux épinards et feta, croustillante et dorée — l\'en-cas et mezze grec par excellence.',
        'temps_preparation': 30,
        'temps_cuisson': 40,
        'nb_personnes': 8,
        'difficulte': 'Moyen',
        'ingredients': [
            '10 feuilles de filo', '600 g d\'épinards frais', '300 g de feta',
            '3 œufs', '2 oignons', '1 botte d\'aneth', 'Huile d\'olive',
            '100 g de beurre fondu', 'Sel, poivre, noix de muscade',
        ],
        'etapes': [
            'Faire tomber les épinards à la poêle avec l\'oignon. Bien égoutter.',
            'Mélanger épinards, feta émiettée, œufs, aneth, sel, poivre et muscade.',
            'Beurrer un moule rectangulaire.',
            'Alterner 5 feuilles de filo (beurrées entre chaque) en faisant déborder.',
            'Étaler la farce épinards-feta.',
            'Rabattre les bords et couvrir de 5 feuilles de filo beurrées.',
            'Enfourner 35-40 min à 180°C jusqu\'à croûte bien dorée.',
        ],
        'tags': ['Filo', 'Épinards', 'Végétarien', 'Mezze'],
        'image_url': 'https://images.unsplash.com/photo-1586985289906-406988974504?w=800&q=80',
    },
    {
        'titre': 'Souvlaki',
        'pays': 'greece',
        'description': 'Brochettes de porc marinées au citron, origan et huile d\'olive, grillées et servies dans un pita avec tzatziki.',
        'temps_preparation': 20,
        'temps_cuisson': 15,
        'nb_personnes': 4,
        'difficulte': 'Facile',
        'ingredients': [
            '600 g de filet de porc', '4 c. à soupe d\'huile d\'olive',
            'Jus de 2 citrons', '2 c. à café d\'origan séché',
            '2 gousses d\'ail', 'Sel, poivre',
            '4 pitas', '200 g de tzatziki', 'Tomates, oignons, persil',
        ],
        'etapes': [
            'Couper le porc en cubes de 3 cm.',
            'Mariner dans huile, jus de citron, origan, ail, sel et poivre 2h.',
            'Embrocher et griller 12-15 min au barbecue en retournant.',
            'Chauffer les pitas quelques secondes sur le grill.',
            'Garnir les pitas de souvlaki, tzatziki, tomates et oignons.',
        ],
        'tags': ['Grill', 'Street food', 'Porc', 'Citron'],
        'image_url': 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=800&q=80',
    },
]


class Command(BaseCommand):
    help = 'Charge les recettes en base de données (3 recettes par pays)'

    def handle(self, *args, **options):
        Recipe.objects.all().delete()
        created = Recipe.objects.bulk_create([Recipe(**r) for r in RECIPES])
        countries = sorted(set(r['pays'] for r in RECIPES))
        self.stdout.write(self.style.SUCCESS(
            f'{len(created)} recettes chargées pour {len(countries)} pays : {", ".join(countries)}'
        ))
