from django.core.management.base import BaseCommand
from apps.recipes.models import Recipe

RECIPES = [
    # ── FRANCE ──────────────────────────────────────────────────────────────
    {
        'titre': 'Bœuf Bourguignon',
        'pays': 'france',
        'region': 'Bourgogne',
        'description': 'Grand classique bourguignon : bœuf mijoté dans le vin rouge avec lardons, champignons et carottes.',
        'temps_preparation': 30, 'temps_cuisson': 180, 'nb_personnes': 6, 'difficulte': 'Moyen',
        'ingredients': ['1,2 kg de bœuf (paleron)', '200 g de lardons', '1 bouteille vin rouge de Bourgogne',
                        '300 g de champignons', '3 carottes', '2 oignons', '2 gousses d\'ail', 'Thym, laurier'],
        'etapes': ['Fariner et dorer les cubes de bœuf dans une cocotte.',
                   'Faire revenir lardons, oignons et ail.',
                   'Remettre la viande, ajouter vin, carottes, thym et laurier.',
                   'Couvrir et mijoter 2h30 à feu doux.',
                   'Ajouter champignons 30 min avant la fin. Rectifier l\'assaisonnement.'],
        'tags': ['Mijoté', 'Bourgogne', 'Hiver', 'Traditionnel'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Beef-Bourguignon.jpg/800px-Beef-Bourguignon.jpg',
    },
    {
        'titre': 'Ratatouille Provençale',
        'pays': 'france',
        'region': 'Provence',
        'description': 'Ragoût de légumes d\'été du soleil provençal, parfumé aux herbes de Provence.',
        'temps_preparation': 25, 'temps_cuisson': 45, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['2 courgettes', '1 aubergine', '3 tomates', '2 poivrons', '1 oignon',
                        '3 gousses d\'ail', 'Herbes de Provence', 'Huile d\'olive'],
        'etapes': ['Couper tous les légumes en dés.',
                   'Faire revenir oignon et ail dans l\'huile d\'olive.',
                   'Ajouter les légumes dans l\'ordre : poivrons, aubergine, courgettes, tomates.',
                   'Assaisonner et mijoter 40 min à couvert.'],
        'tags': ['Végétarien', 'Provence', 'Été', 'Légumes'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Ratatouille_02.jpg/800px-Ratatouille_02.jpg',
    },
    {
        'titre': 'Crêpes Bretonnes',
        'pays': 'france',
        'region': 'Bretagne',
        'description': 'Fines crêpes de Bretagne, sucrées au caramel beurre salé ou salées jambon-fromage.',
        'temps_preparation': 10, 'temps_cuisson': 20, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['250 g de farine', '3 œufs', '500 ml de lait', '50 g de beurre fondu', 'Sel, sucre'],
        'etapes': ['Mélanger farine, œufs, sel et sucre.',
                   'Ajouter le lait progressivement en fouettant.',
                   'Incorporer beurre fondu, laisser reposer 30 min.',
                   'Cuire dans une poêle beurrée 1 min de chaque côté.'],
        'tags': ['Bretagne', 'Brunch', 'Rapide', 'Dessert'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Crepe_pan_pancake.jpg/800px-Crepe_pan_pancake.jpg',
    },
    {
        'titre': 'Coq au Vin',
        'pays': 'france',
        'description': 'Poulet fermier mijoté dans le vin rouge avec champignons et oignons grelots, recette paysanne emblématique.',
        'temps_preparation': 20, 'temps_cuisson': 90, 'nb_personnes': 4, 'difficulte': 'Moyen',
        'ingredients': ['1 poulet fermier découpé', '75 cl de vin rouge', '200 g de lardons',
                        '200 g de champignons', '150 g d\'oignons grelots', '2 gousses d\'ail', 'Thym, laurier'],
        'etapes': ['Faire dorer les morceaux de poulet dans une cocotte.',
                   'Ajouter lardons, oignons grelots et ail. Flamber au cognac (optionnel).',
                   'Couvrir de vin rouge, ajouter thym et laurier.',
                   'Mijoter 1h à feu doux. Ajouter les champignons 15 min avant la fin.'],
        'tags': ['Mijoté', 'Rustique', 'Hiver', 'Terroir'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Coq_au_vin.jpg/800px-Coq_au_vin.jpg',
    },
    {
        'titre': 'Quiche Lorraine',
        'pays': 'france',
        'region': 'Lorraine',
        'description': 'Tarte salée lorraine au migaine crémeux, lardons fumés, sans fromage — la vraie recette.',
        'temps_preparation': 20, 'temps_cuisson': 35, 'nb_personnes': 6, 'difficulte': 'Facile',
        'ingredients': ['1 pâte brisée', '200 g de lardons fumés', '3 œufs', '20 cl de crème fraîche',
                        '20 cl de lait', 'Noix de muscade', 'Sel, poivre'],
        'etapes': ['Préchauffer le four à 180°C. Foncer le moule avec la pâte.',
                   'Faire revenir les lardons à sec.',
                   'Battre œufs, crème et lait. Assaisonner, ajouter la muscade.',
                   'Déposer les lardons sur la pâte, verser la migaine.',
                   'Cuire 30–35 min jusqu\'à dorure.'],
        'tags': ['Lorraine', 'Tarte', 'Brunch', 'Rapide'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/FoodQuicheLorraine.jpg/800px-FoodQuicheLorraine.jpg',
    },
    {
        'titre': 'Bouillabaisse Marseillaise',
        'pays': 'france',
        'region': 'Provence',
        'description': 'La soupe de poisson mythique de Marseille, servie avec croûtons et rouille safranée.',
        'temps_preparation': 40, 'temps_cuisson': 50, 'nb_personnes': 6, 'difficulte': 'Difficile',
        'ingredients': ['1,5 kg de poissons variés (rascasse, grondin, saint-pierre)', '300 g de crevettes',
                        '500 g de moules', '3 tomates', '1 oignon', '1 bulbe de fenouil',
                        'Safran, thym, laurier', 'Huile d\'olive'],
        'etapes': ['Faire revenir oignon, fenouil et tomates dans l\'huile d\'olive.',
                   'Ajouter le safran, les herbes et 2 L d\'eau. Porter à ébullition.',
                   'Ajouter les poissons selon leur temps de cuisson (les plus fermes en premier).',
                   'Ajouter moules et crevettes 5 min avant la fin.',
                   'Servir avec croûtons frottés à l\'ail et rouille.'],
        'tags': ['Marseille', 'Poisson', 'Méditerranée', 'Festif'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Bouillabaisse.jpg/800px-Bouillabaisse.jpg',
    },
    {
        'titre': 'Soupe à l\'Oignon Gratinée',
        'pays': 'france',
        'region': 'Île-de-France',
        'description': 'Soupe brasserie parisienne par excellence : oignons caramélisés, bouillon de bœuf, croûton et gruyère fondu.',
        'temps_preparation': 15, 'temps_cuisson': 60, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['1 kg d\'oignons', '1 L de bouillon de bœuf', '50 g de beurre',
                        '4 tranches de pain grillé', '150 g de gruyère râpé', 'Vin blanc sec', 'Sel, poivre'],
        'etapes': ['Émincer les oignons et les caraméliser 40 min à feu doux dans le beurre.',
                   'Déglacer au vin blanc. Ajouter le bouillon et mijoter 20 min.',
                   'Verser dans des bols individuels allant au four.',
                   'Poser un croûton, couvrir de gruyère et gratiner 5 min au grill.'],
        'tags': ['Paris', 'Bistrot', 'Hiver', 'Réconfort'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Sopa_de_cebolla.jpg/800px-Sopa_de_cebolla.jpg',
    },
    {
        'titre': 'Croissant au Beurre',
        'pays': 'france',
        'region': 'Île-de-France',
        'description': 'L\'emblème de la boulangerie française : pâte feuilletée levée au beurre AOP, croustillante dehors et filante dedans.',
        'temps_preparation': 120, 'temps_cuisson': 18, 'nb_personnes': 8, 'difficulte': 'Difficile',
        'ingredients': ['500 g de farine T45', '10 g de sel', '80 g de sucre', '10 g de levure boulangère',
                        '300 ml de lait', '250 g de beurre AOP (tourage)', '1 jaune d\'œuf (dorure)'],
        'etapes': ['Pétrir farine, sel, sucre, levure et lait pour obtenir une détrempe. Réfrigérer 1h.',
                   'Incorporer le beurre en feuilletant (3 tours simples), réfrigérer entre chaque.',
                   'Abaisser la pâte, découper des triangles, rouler en croissants.',
                   'Laisser pousser 2h à température ambiante.',
                   'Dorer au jaune d\'œuf et cuire 16–18 min à 190°C.'],
        'tags': ['Boulangerie', 'Brunch', 'Paris', 'Petit-déjeuner'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Croissant_with_coffee.jpg/800px-Croissant_with_coffee.jpg',
    },

    # ── FRANCE — Régionales ──────────────────────────────────────────────────
    {
        'titre': 'Carbonnade Flamande',
        'pays': 'france',
        'region': 'Nord',
        'type_plat': 'salé',
        'description': 'Bœuf mijoté à la bière brune du Ch\'ti, oignons caramélisés et pain d\'épice — le comfort food du Nord.',
        'temps_preparation': 20, 'temps_cuisson': 150, 'nb_personnes': 4, 'difficulte': 'Moyen',
        'ingredients': ['1,2 kg de bœuf à braiser', '3 oignons', '50 cl de bière brune',
                        '2 tranches de pain d\'épice', '1 c. à soupe de moutarde', 'Thym, laurier', 'Sel, poivre'],
        'etapes': ['Faire dorer les morceaux de bœuf dans une cocotte. Réserver.',
                   'Caraméliser les oignons émincés 15 min.',
                   'Remettre la viande, verser la bière, ajouter thym et laurier.',
                   'Tartiner le pain d\'épice de moutarde et poser sur la viande.',
                   'Couvrir et mijoter 2h à feu doux. Rectifier l\'assaisonnement.'],
        'tags': ['Nord', 'Mijoté', 'Bière', 'Hiver'],
        'image_url': '',
    },
    {
        'titre': 'Tarte Flambée (Flammekueche)',
        'pays': 'france',
        'region': 'Alsace',
        'type_plat': 'salé',
        'description': 'La pizza alsacienne : pâte fine croustillante, fromage blanc, crème fraîche, lardons et oignons.',
        'temps_preparation': 20, 'temps_cuisson': 15, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['300 g de pâte à pain fine', '200 g de fromage blanc', '10 cl de crème fraîche',
                        '150 g de lardons', '2 oignons', 'Noix de muscade', 'Sel, poivre'],
        'etapes': ['Étaler la pâte très finement en rectangle.',
                   'Mélanger fromage blanc, crème fraîche, sel, poivre et muscade.',
                   'Étaler la crème, répartir oignons émincés et lardons.',
                   'Cuire au four très chaud (250°C) 12–15 min.',
                   'Servir immédiatement, bien croustillante.'],
        'tags': ['Alsace', 'Rapide', 'Apéro', 'Partage'],
        'image_url': '',
    },
    {
        'titre': 'Cassoulet Toulousain',
        'pays': 'france',
        'region': 'Occitanie',
        'type_plat': 'salé',
        'description': 'Le roi des plats mijotés du Sud-Ouest : haricots blancs, confit de canard, saucisse de Toulouse et couenne.',
        'temps_preparation': 30, 'temps_cuisson': 180, 'nb_personnes': 6, 'difficulte': 'Moyen',
        'ingredients': ['500 g de haricots blancs secs (trempés)', '4 cuisses de canard confites',
                        '4 saucisses de Toulouse', '200 g de lard', '400 g de tomates concassées',
                        '4 gousses d\'ail', 'Thym, laurier'],
        'etapes': ['Faire cuire les haricots 1h dans de l\'eau avec ail et laurier.',
                   'Faire revenir lard et saucisses. Réserver.',
                   'Dans une cassole, alterner haricots, viandes et tomates.',
                   'Couvrir de bouillon et enfourner à 160°C pendant 2h.',
                   'Casser la croûte 2–3 fois en cours de cuisson.'],
        'tags': ['Toulouse', 'Mijoté', 'Canard', 'Hiver'],
        'image_url': '',
    },
    {
        'titre': 'Moules à la Crème Normande',
        'pays': 'france',
        'region': 'Normandie',
        'type_plat': 'salé',
        'description': 'Moules de Normandie ouvertes à la crème fraîche, cidre brut et échalotes — la mer dans l\'assiette.',
        'temps_preparation': 15, 'temps_cuisson': 15, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['2 kg de moules de bouchot', '20 cl de cidre brut', '20 cl de crème fraîche épaisse',
                        '4 échalotes', '2 gousses d\'ail', 'Persil frais', 'Beurre'],
        'etapes': ['Faire revenir échalotes et ail dans le beurre.',
                   'Ajouter les moules et le cidre. Couvrir à feu vif.',
                   'Remuer et cuire 5 min jusqu\'à ouverture des moules.',
                   'Retirer les moules, verser la crème dans le jus de cuisson.',
                   'Faire réduire 3 min, napper les moules et parsemer de persil.'],
        'tags': ['Normandie', 'Fruits de mer', 'Cidre', 'Rapide'],
        'image_url': '',
    },
    {
        'titre': 'Kouign-Amann',
        'pays': 'france',
        'region': 'Bretagne',
        'type_plat': 'sucré',
        'description': 'Le gâteau breton au beurre salé caramélisé : croûte dorée et craquante, intérieur fondant et filant.',
        'temps_preparation': 30, 'temps_cuisson': 40, 'nb_personnes': 8, 'difficulte': 'Moyen',
        'ingredients': ['300 g de farine', '7 g de levure sèche', '150 ml d\'eau', '200 g de beurre demi-sel',
                        '150 g de sucre', '1 pincée de sel'],
        'etapes': ['Pétrir farine, eau, levure et sel. Laisser lever 1h.',
                   'Étaler la pâte, y enfermer le beurre comme un feuilletage.',
                   'Saupoudrer de sucre et replier plusieurs fois.',
                   'Disposer dans un moule beurré, saupoudrer de sucre.',
                   'Cuire 35–40 min à 200°C. Démouler chaud.'],
        'tags': ['Bretagne', 'Beurre salé', 'Dessert', 'Caramel'],
        'image_url': '',
    },
    {
        'titre': 'Gaufre de Liège',
        'pays': 'france',
        'region': 'Nord',
        'type_plat': 'sucré',
        'description': 'Gaufre épaisse et moelleuse de la frontière belge, parfumée à la vanille avec des perles de sucre crunchy.',
        'temps_preparation': 20, 'temps_cuisson': 20, 'nb_personnes': 8, 'difficulte': 'Facile',
        'ingredients': ['500 g de farine', '20 g de levure fraîche', '2 œufs', '250 g de beurre fondu',
                        '100 ml de lait', '1 sachet de sucre vanillé', '150 g de sucre perlé', 'Sel'],
        'etapes': ['Délayer la levure dans le lait tiède.',
                   'Mélanger farine, œufs, beurre fondu, sel et levure.',
                   'Incorporer le sucre perlé à la pâte.',
                   'Laisser reposer 1h à température ambiante.',
                   'Cuire des boules de pâte dans le gaufrier 4–5 min.'],
        'tags': ['Nord', 'Gaufre', 'Sucre perlé', 'Goûter'],
        'image_url': '',
    },
    {
        'titre': 'Kougelhopf',
        'pays': 'france',
        'region': 'Alsace',
        'type_plat': 'sucré',
        'description': 'La brioche alsacienne aux raisins secs et amandes, cuite dans son moule cannelé emblématique.',
        'temps_preparation': 30, 'temps_cuisson': 45, 'nb_personnes': 8, 'difficulte': 'Moyen',
        'ingredients': ['500 g de farine', '150 g de beurre mou', '2 œufs', '150 ml de lait tiède',
                        '20 g de levure fraîche', '80 g de sucre', '150 g de raisins secs',
                        '50 g d\'amandes entières', 'Sucre glace'],
        'etapes': ['Faire tremper les raisins dans du rhum ou de l\'eau tiède.',
                   'Mélanger farine, levure, lait, œufs, sucre et sel. Pétrir 10 min.',
                   'Incorporer le beurre en dés. Pétrir jusqu\'à pâte lisse.',
                   'Ajouter les raisins égouttés. Laisser lever 1h30.',
                   'Garnir le moule beurré d\'amandes, ajouter la pâte, lever encore 1h. Cuire 40–45 min à 180°C.'],
        'tags': ['Alsace', 'Brioche', 'Raisins', 'Noël'],
        'image_url': '',
    },
    {
        'titre': 'Crème Catalane',
        'pays': 'france',
        'region': 'Occitanie',
        'type_plat': 'sucré',
        'description': 'La crème brûlée du Sud : custard parfumé à la cannelle et zeste d\'orange, caramel craquant dessus.',
        'temps_preparation': 15, 'temps_cuisson': 15, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['500 ml de lait entier', '4 jaunes d\'œuf', '100 g de sucre',
                        '30 g de maïzena', '1 bâton de cannelle', '1 zeste de citron', 'Sucre brun (caramel)'],
        'etapes': ['Infuser la cannelle et le zeste dans le lait chaud 10 min.',
                   'Battre jaunes, sucre et maïzena.',
                   'Verser le lait filtré sur les jaunes en fouettant.',
                   'Cuire à feu moyen sans arrêter de remuer jusqu\'à épaississement.',
                   'Verser dans des coupelles, réfrigérer 2h. Saupoudrer de sucre et caraméliser au chalumeau.'],
        'tags': ['Occitanie', 'Dessert', 'Caramel', 'Cannelle'],
        'image_url': '',
    },

    # ── ENGLAND ─────────────────────────────────────────────────────────────
    {
        'titre': 'Fish and Chips',
        'pays': 'england',
        'description': 'Le plat national britannique : cabillaud en beignet croustillant, frites épaisses et sauce mushy peas.',
        'temps_preparation': 20, 'temps_cuisson': 25, 'nb_personnes': 4, 'difficulte': 'Moyen',
        'ingredients': ['4 filets de cabillaud', '200 g de farine', '330 ml de bière blonde',
                        '1 kg de pommes de terre', 'Huile de friture', 'Sel, vinaigre de malt'],
        'etapes': ['Préparer la pâte à beignet : farine + bière froide + sel, bien mélanger.',
                   'Couper les pommes de terre en frites épaisses, rincer et sécher.',
                   'Frire les frites une première fois à 160°C, égoutter.',
                   'Plonger le poisson dans la pâte et frire à 180°C jusqu\'à dorure.',
                   'Frire les chips une seconde fois à 190°C. Saler et servir avec vinaigre de malt.'],
        'tags': ['Pub', 'Traditionnel', 'Friture', 'Bord de mer'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Fish_and_chips_blackpool.jpg/800px-Fish_and_chips_blackpool.jpg',
    },
    {
        'titre': 'Sunday Roast',
        'pays': 'england',
        'description': 'Le rituel dominical anglais : rôti de bœuf, Yorkshire pudding, légumes rôtis et gravy.',
        'temps_preparation': 30, 'temps_cuisson': 90, 'nb_personnes': 6, 'difficulte': 'Moyen',
        'ingredients': ['1,5 kg de rosbif', '1 kg de pommes de terre', '500 g de carottes et panais',
                        '200 g de farine (Yorkshire)', '3 œufs', '300 ml de lait', 'Gravy granules', 'Huile de tournesol'],
        'etapes': ['Saisir et rôtir le bœuf 20 min/kg à 200°C. Reposer 20 min avant de découper.',
                   'Rôtir pommes de terre et légumes dans la graisse du rôti.',
                   'Préparer le Yorkshire : mélanger œufs, farine et lait. Cuire dans moules très chauds.',
                   'Préparer le gravy avec les sucs de cuisson.',
                   'Servir le tout avec des petits pois.'],
        'tags': ['Dimanche', 'Famille', 'Rôti', 'Traditionnel'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Sunday_roast_2.jpg/800px-Sunday_roast_2.jpg',
    },
    {
        'titre': 'Shepherd\'s Pie',
        'pays': 'england',
        'description': 'Hachis parmentier à l\'agneau : farce mijotée en sauce brune, coiffée d\'une purée gratinée.',
        'temps_preparation': 20, 'temps_cuisson': 40, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['600 g d\'agneau haché', '2 carottes', '1 oignon', '200 ml de bouillon',
                        '2 c. de sauce Worcestershire', '800 g de pommes de terre', '50 g de beurre', 'Lait'],
        'etapes': ['Faire revenir oignon et carottes, ajouter l\'agneau haché.',
                   'Ajouter bouillon et Worcestershire, mijoter 15 min.',
                   'Préparer une purée crémeuse.',
                   'Verser la farce dans un plat, couvrir de purée.',
                   'Enfourner 25 min à 200°C jusqu\'à dorure.'],
        'tags': ['Comfort food', 'Hiver', 'Familial', 'Gratiné'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Shepherdspie.jpg/800px-Shepherdspie.jpg',
    },
    {
        'titre': 'Full English Breakfast',
        'pays': 'england',
        'description': 'L\'incontournable petit-déjeuner anglais complet : œufs, bacon, saucisses, haricots, toast et champignons.',
        'temps_preparation': 10, 'temps_cuisson': 20, 'nb_personnes': 2, 'difficulte': 'Facile',
        'ingredients': ['4 tranches de bacon', '4 saucisses (Cumberland)', '2 œufs', '200 g de baked beans',
                        '4 champignons', '2 tomates', '4 tranches de pain de mie'],
        'etapes': ['Faire griller bacon et saucisses dans une grande poêle.',
                   'Faire revenir champignons et tomates coupées en deux.',
                   'Chauffer les baked beans dans une casserole.',
                   'Cuire les œufs (au plat ou brouillés).',
                   'Faire griller le pain et dresser l\'assiette.'],
        'tags': ['Brunch', 'Matin', 'Complet', 'Classique'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Full_English_breakfast_2.jpg/800px-Full_English_breakfast_2.jpg',
    },
    {
        'titre': 'Chicken Tikka Masala',
        'pays': 'england',
        'description': 'Plat national officieux britannique : poulet mariné au yaourt et épices, sauce tomate crémeuse au masala.',
        'temps_preparation': 30, 'temps_cuisson': 30, 'nb_personnes': 4, 'difficulte': 'Moyen',
        'ingredients': ['700 g de poulet', '200 ml de yaourt', '400 ml de crème de coco', '400 g de tomates concassées',
                        'Tikka masala (épices)', '2 oignons', 'Gingembre, ail', 'Coriandre fraîche'],
        'etapes': ['Mariner le poulet dans yaourt + épices tikka 2h minimum.',
                   'Griller le poulet au four ou à la poêle. Réserver.',
                   'Faire revenir oignons, ail et gingembre. Ajouter les tomates.',
                   'Incorporer la crème de coco et le poulet grillé. Mijoter 15 min.',
                   'Garnir de coriandre fraîche et servir avec riz basmati.'],
        'tags': ['Curry', 'Épicé', 'Fusion', 'Populaire'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Chicken_tikka_masala_2.jpg/800px-Chicken_tikka_masala_2.jpg',
    },

    # ── GERMANY ─────────────────────────────────────────────────────────────
    {
        'titre': 'Bratwurst au Grill',
        'pays': 'germany',
        'description': 'La saucisse grillée emblématique d\'Allemagne, servie avec moutarde et pain kaiser.',
        'temps_preparation': 5, 'temps_cuisson': 15, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['8 bratwurst (saucisses de porc épicées)', '4 petits pains kaiser',
                        'Moutarde allemande forte', 'Choucroute cuisinée', 'Bière allemande'],
        'etapes': ['Préchauffer le grill ou barbecue à feu moyen-vif.',
                   'Griller les bratwurst en les retournant régulièrement 12–15 min.',
                   'Chauffer la choucroute dans une casserole avec un peu de bière.',
                   'Servir dans les pains avec moutarde et choucroute.'],
        'tags': ['Grill', 'Barbecue', 'Oktoberfest', 'Rapide'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Nuremberg_Bratwurst.jpg/800px-Nuremberg_Bratwurst.jpg',
    },
    {
        'titre': 'Sauerbraten',
        'pays': 'germany',
        'description': 'Rôti de bœuf mariné plusieurs jours dans le vinaigre et épices, sauce aigre-douce aux raisins secs.',
        'temps_preparation': 30, 'temps_cuisson': 180, 'nb_personnes': 6, 'difficulte': 'Difficile',
        'ingredients': ['1,5 kg de bœuf (gîte)', '500 ml de vinaigre de vin rouge', '500 ml d\'eau',
                        '2 oignons', 'Clous de girofle, baies de genièvre', '50 g de raisins secs',
                        '50 g de pain d\'épice émietté', 'Sel, poivre'],
        'etapes': ['Préparer une marinade avec vinaigre, eau, oignons et épices. Mariner la viande 3 jours.',
                   'Égoutter la viande, la faire dorer dans une cocotte.',
                   'Ajouter la marinade filtrée et braiser 2h30.',
                   'Retirer la viande, épaissir la sauce avec pain d\'épice et raisins secs.',
                   'Trancher et servir avec Knödel ou nouilles Spätzle.'],
        'tags': ['Bavière', 'Mariné', 'Festif', 'Hiver'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Sauerbraten.jpg/800px-Sauerbraten.jpg',
    },
    {
        'titre': 'Currywurst',
        'pays': 'germany',
        'description': 'La street food culte de Berlin : saucisse grillée tranchée, sauce tomate-curry et poudre de curry.',
        'temps_preparation': 5, 'temps_cuisson': 15, 'nb_personnes': 2, 'difficulte': 'Facile',
        'ingredients': ['4 saucisses de porc (Bratwurst)', '400 g de ketchup', '2 c. à soupe de curry en poudre',
                        '1 c. à café de paprika', 'Frites ou pain'],
        'etapes': ['Griller ou poêler les saucisses jusqu\'à coloration.',
                   'Préparer la sauce en mélangeant ketchup, curry et paprika à feu doux.',
                   'Couper les saucisses en rondelles obliques.',
                   'Napper généreusement de sauce et saupoudrer de curry.'],
        'tags': ['Berlin', 'Street food', 'Rapide', 'Incontournable'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Curry_Wurst.jpg/800px-Curry_Wurst.jpg',
    },
    {
        'titre': 'Bretzel (Laugenbrezel)',
        'pays': 'germany',
        'description': 'Bretzel bavarois brillant et salé, croustillant en surface et moelleux à l\'intérieur.',
        'temps_preparation': 30, 'temps_cuisson': 15, 'nb_personnes': 8, 'difficulte': 'Moyen',
        'ingredients': ['500 g de farine', '7 g de levure sèche', '300 ml d\'eau tiède', '10 g de sel',
                        '20 g de beurre', '1 L d\'eau + 40 g de bicarbonate (bain)', 'Gros sel'],
        'etapes': ['Pétrir tous les ingrédients 10 min. Laisser lever 1h.',
                   'Façonner des rouleaux et former les bretzels.',
                   'Plonger chaque bretzel dans le bain bicarbonate 30 sec.',
                   'Disposer sur plaque, inciser, parsemer de gros sel.',
                   'Cuire 12–15 min à 220°C jusqu\'à brun profond.'],
        'tags': ['Boulangerie', 'Bavière', 'Oktoberfest', 'Apéro'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Pretzel_2.jpg/800px-Pretzel_2.jpg',
    },
    {
        'titre': 'Schwarzwälder Kirschtorte',
        'pays': 'germany',
        'description': 'La Forêt-Noire : gâteau au chocolat imbibé de kirsch, crème chantilly et cerises griotte.',
        'temps_preparation': 60, 'temps_cuisson': 35, 'nb_personnes': 10, 'difficulte': 'Difficile',
        'ingredients': ['4 œufs', '150 g de sucre', '100 g de farine', '50 g de cacao', '50 g de beurre',
                        '500 ml de crème fraîche', '400 g de cerises (bocal)', '5 cl de kirsch'],
        'etapes': ['Battre œufs et sucre jusqu\'à blanchissement. Incorporer farine, cacao et beurre fondu.',
                   'Cuire 30–35 min à 180°C. Laisser refroidir et couper en 3 disques.',
                   'Monter la crème en chantilly ferme.',
                   'Imbiber chaque disque de kirsch, garnir de chantilly et cerises.',
                   'Assembler, couvrir de chantilly et décorer de copeaux de chocolat noir.'],
        'tags': ['Dessert', 'Forêt-Noire', 'Gâteau', 'Festif'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Schwarzwaelder_Kirschtorte.jpg/800px-Schwarzwaelder_Kirschtorte.jpg',
    },

    # ── SPAIN ────────────────────────────────────────────────────────────────
    {
        'titre': 'Paella Valenciana',
        'pays': 'spain',
        'description': 'L\'emblème espagnol : riz safrané aux poulet, lapin et haricots verts, cuit dans le paellero.',
        'temps_preparation': 30, 'temps_cuisson': 40, 'nb_personnes': 6, 'difficulte': 'Moyen',
        'ingredients': ['500 g de riz à paella', '400 g de poulet', '300 g de lapin',
                        '200 g de haricots verts', '400 g de tomates', '1 L de bouillon de volaille',
                        'Safran, paprika doux', 'Huile d\'olive'],
        'etapes': ['Faire dorer poulet et lapin dans la paellera avec huile d\'olive.',
                   'Ajouter tomates concassées et paprika, faire revenir.',
                   'Verser le bouillon chaud avec le safran infusé. Porter à ébullition.',
                   'Ajouter le riz et les haricots verts. Cuire à feu moyen 18–20 min sans remuer.',
                   'Laisser reposer 5 min couvert. Le socarrat (fond grillé) est une réussite !'],
        'tags': ['Valence', 'Riz', 'Safran', 'Festif'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Paella_Valenciana_Restaurant.jpg/800px-Paella_Valenciana_Restaurant.jpg',
    },
    {
        'titre': 'Gazpacho Andaluz',
        'pays': 'spain',
        'description': 'Soupe froide d\'Andalousie : tomates, concombre, poivron et ail mixés avec huile d\'olive.',
        'temps_preparation': 15, 'temps_cuisson': 0, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['1 kg de tomates mûres', '1 concombre', '1 poivron rouge', '1 oignon',
                        '2 gousses d\'ail', '4 c. à soupe d\'huile d\'olive', 'Vinaigre de Jerez', 'Sel'],
        'etapes': ['Éplucher et couper tous les légumes.',
                   'Mixer jusqu\'à obtenir une consistance lisse.',
                   'Ajouter huile d\'olive et vinaigre. Assaisonner.',
                   'Filtrer si désiré. Réfrigérer au moins 2h.',
                   'Servir très frais avec garnitures (dés de légumes, croûtons).'],
        'tags': ['Andalousie', 'Froid', 'Été', 'Végétarien'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Gazpacho_all%C3%A0.jpg/800px-Gazpacho_all%C3%A0.jpg',
    },
    {
        'titre': 'Tortilla Española',
        'pays': 'spain',
        'description': 'L\'omelette espagnole aux pommes de terre et oignons confits dans l\'huile d\'olive.',
        'temps_preparation': 20, 'temps_cuisson': 30, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['6 œufs', '500 g de pommes de terre', '2 oignons', '200 ml d\'huile d\'olive', 'Sel'],
        'etapes': ['Éplucher et émincer pommes de terre et oignons.',
                   'Confire lentement dans l\'huile d\'olive 20 min à feu doux. Égoutter.',
                   'Battre les œufs avec du sel. Incorporer les pommes de terre.',
                   'Cuire dans une poêle huilée 4 min. Retourner à l\'aide d\'un couvercle.',
                   'Cuire encore 3 min. La tortilla doit être légèrement coulante au centre.'],
        'tags': ['Tapas', 'Brunch', 'Simple', 'Traditionnel'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/OmeleteEspanhola.jpg/800px-OmeleteEspanhola.jpg',
    },
    {
        'titre': 'Churros con Chocolate',
        'pays': 'spain',
        'description': 'Beignets frits en forme d\'étoile, trempés dans un chocolat chaud épais et soyeux.',
        'temps_preparation': 15, 'temps_cuisson': 15, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['250 ml d\'eau', '125 g de farine', '1 pincée de sel', 'Huile de friture',
                        'Sucre en poudre', '200 g de chocolat noir', '300 ml de lait entier'],
        'etapes': ['Porter l\'eau à ébullition avec le sel. Verser sur la farine et mélanger vigoureusement.',
                   'Remplir une poche à douille étoilée et former des churros.',
                   'Frire à 180°C 3–4 min jusqu\'à dorure. Égoutter et sucrer.',
                   'Fondre le chocolat avec le lait chaud en fouettant pour le chocolat chaud.',
                   'Servir immédiatement avec le chocolat pour tremper.'],
        'tags': ['Dessert', 'Petit-déjeuner', 'Madrid', 'Friture'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Churros.jpg/800px-Churros.jpg',
    },
    {
        'titre': 'Jamón Ibérico & Tapas',
        'pays': 'spain',
        'description': 'Plateau de tapas madrilènes : jamón ibérico, patatas bravas, manchego et olives marinées.',
        'temps_preparation': 20, 'temps_cuisson': 20, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['150 g de jamón ibérico tranché', '4 pommes de terre (patatas bravas)',
                        '100 g de manchego', 'Sauce brava (tomate épicée)', 'Olives marinées', 'Chorizo', 'Pain'],
        'etapes': ['Couper les pommes de terre en cubes et frire à 180°C jusqu\'à dorure.',
                   'Préparer la sauce brava : tomates, ail, piment, paprika fumé, cuire 15 min.',
                   'Disposer le jamón et le manchego sur une planche.',
                   'Dresser les patatas bravas nappées de sauce.',
                   'Présenter avec olives marinées et pain grillé.'],
        'tags': ['Tapas', 'Apéro', 'Madrid', 'Partage'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Jamon_iberico.jpg/800px-Jamon_iberico.jpg',
    },

    # ── ITALY ────────────────────────────────────────────────────────────────
    {
        'titre': 'Pizza Margherita',
        'pays': 'italy',
        'description': 'La pizza napolitaine originale : pâte à main levée, tomates San Marzano, fior di latte et basilic.',
        'temps_preparation': 30, 'temps_cuisson': 10, 'nb_personnes': 4, 'difficulte': 'Moyen',
        'ingredients': ['500 g de farine type 00', '7 g de levure sèche', '300 ml d\'eau',
                        '400 g de tomates San Marzano', '250 g de mozzarella fior di latte',
                        'Basilic frais', 'Huile d\'olive extra vierge', 'Sel'],
        'etapes': ['Pétrir farine, eau, levure et sel. Laisser lever 8h (idéalement 24h au frigo).',
                   'Diviser en pâtons, étaler à la main (ne pas rouler).',
                   'Écraser les tomates à la main avec du sel et de l\'huile.',
                   'Garnir de sauce tomate et enfourner à 250°C 8–10 min.',
                   'Sortir du four, ajouter mozzarella déchirée et basilic frais.'],
        'tags': ['Naples', 'Pizza', 'Végétarien', 'Classique'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg/800px-Eq_it-na_pizza-margherita_sep2005_sml.jpg',
    },
    {
        'titre': 'Pasta alla Carbonara',
        'pays': 'italy',
        'description': 'La vraie carbonara romaine : spaghetti, guanciale croustillant, pecorino, jaunes d\'œuf — sans crème.',
        'temps_preparation': 10, 'temps_cuisson': 15, 'nb_personnes': 4, 'difficulte': 'Moyen',
        'ingredients': ['400 g de spaghetti', '200 g de guanciale (ou pancetta)', '4 jaunes d\'œuf + 1 entier',
                        '80 g de pecorino romano râpé', '50 g de parmesan râpé', 'Poivre noir', 'Sel'],
        'etapes': ['Faire dorer le guanciale en dés à sec. Réserver la graisse.',
                   'Cuire les pâtes al dente dans une grande quantité d\'eau salée.',
                   'Mélanger œufs, pecorino, parmesan et poivre dans un bol.',
                   'Hors du feu, incorporer les pâtes égouttées au guanciale.',
                   'Ajouter le mélange œuf-fromage en remuant vivement hors du feu (jamais sur le feu).'],
        'tags': ['Rome', 'Pasta', 'Traditionnel', 'Rapide'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Fresh_made_pasta_02.jpg/800px-Fresh_made_pasta_02.jpg',
    },
    {
        'titre': 'Risotto ai Funghi Porcini',
        'pays': 'italy',
        'description': 'Risotto crémeux aux cèpes séchés réhydratés, parmesan et beurre mantecat — la texture parfaite.',
        'temps_preparation': 15, 'temps_cuisson': 30, 'nb_personnes': 4, 'difficulte': 'Moyen',
        'ingredients': ['320 g de riz Carnaroli ou Arborio', '30 g de cèpes séchés', '1 L de bouillon de légumes',
                        '1 oignon', '10 cl de vin blanc', '80 g de parmesan', '50 g de beurre', 'Sel, poivre'],
        'etapes': ['Réhydrater les cèpes 20 min dans de l\'eau tiède. Filtrer l\'eau de trempage.',
                   'Faire revenir l\'oignon dans le beurre. Ajouter le riz et nacrer 2 min.',
                   'Déglacer au vin blanc. Ajouter le bouillon louche par louche en remuant.',
                   'Incorporer les cèpes et leur eau filtrée.',
                   'Hors du feu, mantéquer avec beurre froid et parmesan. Reposer 2 min.'],
        'tags': ['Lombardie', 'Végétarien', 'Crémeux', 'Champignons'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Risotto_with_porcini.jpg/800px-Risotto_with_porcini.jpg',
    },
    {
        'titre': 'Tiramisù',
        'pays': 'italy',
        'description': 'Le dessert italien culte : biscuits imbibés de café, crème mascarpone et cacao amer.',
        'temps_preparation': 30, 'temps_cuisson': 0, 'nb_personnes': 8, 'difficulte': 'Facile',
        'ingredients': ['500 g de mascarpone', '4 œufs', '100 g de sucre', '300 ml de café fort refroidi',
                        '200 g de biscuits Savoiardi', '4 cl de marsala ou Amaretto', 'Cacao amer en poudre'],
        'etapes': ['Séparer blancs et jaunes. Battre jaunes + sucre jusqu\'à blanchissement.',
                   'Incorporer le mascarpone. Battre les blancs en neige ferme et les plier délicatement.',
                   'Mélanger café et alcool. Tremper brièvement les biscuits.',
                   'Alterner couches de biscuits et crème dans un plat.',
                   'Réfrigérer 6h minimum. Saupoudrer de cacao avant service.'],
        'tags': ['Dessert', 'Café', 'Vénétie', 'Classique'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Tiramis%C3%B9.jpg/800px-Tiramis%C3%B9.jpg',
    },
    {
        'titre': 'Osso Buco alla Milanese',
        'pays': 'italy',
        'description': 'Jarret de veau braisé à la milanaise avec gremolata, servi sur risotto safrané.',
        'temps_preparation': 20, 'temps_cuisson': 120, 'nb_personnes': 4, 'difficulte': 'Moyen',
        'ingredients': ['4 tranches de jarret de veau (4 cm)', '2 carottes', '2 branches de céleri',
                        '1 oignon', '200 ml de vin blanc', '400 g de tomates', '1 zeste de citron',
                        'Persil, ail (gremolata)'],
        'etapes': ['Fariner et dorer les jarrets dans une cocotte large.',
                   'Faire revenir légumes. Remettre la viande, déglacer au vin blanc.',
                   'Ajouter tomates et bouillon. Braiser 1h30 à feu doux.',
                   'Préparer la gremolata : hacher persil, ail et zeste de citron.',
                   'Servir avec gremolata et risotto safrané.'],
        'tags': ['Milan', 'Braisé', 'Veau', 'Festif'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Osso_buco.jpg/800px-Osso_buco.jpg',
    },
]


class Command(BaseCommand):
    help = 'Charge les recettes en base (Part 1 : France, England, Germany, Spain, Italy)'

    def handle(self, *args, **options):
        created, updated = 0, 0
        for data in RECIPES:
            obj, was_created = Recipe.objects.update_or_create(
                titre=data['titre'],
                pays=data['pays'],
                type_plat=data.get('type_plat', Recipe.TYPE_SALE),
                defaults=data,
            )
            if was_created:
                created += 1
            else:
                updated += 1
        self.stdout.write(self.style.SUCCESS(
            f'Done — {created} created, {updated} updated ({created + updated} total)'
        ))
