from django.core.management.base import BaseCommand
from apps.recipes.models import Recipe

RECIPES_EXTRA = [
    # ── PORTUGAL ────────────────────────────────────────────────────────────
    {
        'titre': 'Bacalhau à Brás',
        'pays': 'portugal',
        'description': 'Morue effilochée sautée avec pommes de terre en allumettes, œufs brouillés et olives noires.',
        'temps_preparation': 20, 'temps_cuisson': 25, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['500 g de morue dessalée', '400 g de pommes de terre', '4 œufs',
                        '2 oignons', '3 gousses d\'ail', 'Olives noires', 'Persil', 'Huile d\'olive'],
        'etapes': ['Effilocher la morue dessalée en petits morceaux.',
                   'Frire les pommes de terre en allumettes fines. Réserver.',
                   'Faire revenir oignons et ail dans l\'huile d\'olive, ajouter la morue.',
                   'Incorporer les pommes de terre frites et les œufs battus hors du feu.',
                   'Remuer jusqu\'à prise crémeuse. Garnir d\'olives et persil haché.'],
        'tags': ['Morue', 'Lisbonne', 'Traditionnel', 'Rapide'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Bacalhau_a_bras.jpg/800px-Bacalhau_a_bras.jpg',
    },
    {
        'titre': 'Pastéis de Nata',
        'pays': 'portugal',
        'description': 'Les tartelettes à la crème custard de Belém, caramélisées, saupoudrées de cannelle.',
        'temps_preparation': 40, 'temps_cuisson': 20, 'nb_personnes': 12, 'difficulte': 'Moyen',
        'ingredients': ['1 rouleau de pâte feuilletée', '250 ml de lait', '3 jaunes d\'œuf',
                        '120 g de sucre', '25 g de farine', 'Zeste de citron', 'Cannelle en poudre'],
        'etapes': ['Découper des disques de pâte feuilletée et foncer des moules à tartelette.',
                   'Chauffer lait et zeste de citron. Mélanger jaunes, sucre et farine.',
                   'Verser le lait chaud sur le mélange œufs en fouettant. Remettre sur feu.',
                   'Cuire la crème jusqu\'à épaississement. Remplir les fonds de tarte.',
                   'Cuire à 250°C 15–18 min jusqu\'à caramélisation. Saupoudrer de cannelle.'],
        'tags': ['Dessert', 'Belém', 'Petite fournée', 'Café'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Pastel_de_nata_%281%29.jpg/800px-Pastel_de_nata_%281%29.jpg',
    },
    {
        'titre': 'Caldo Verde',
        'pays': 'portugal',
        'description': 'Soupe nationale du Portugal : chou kale ou chou portugais, pommes de terre et chorizo.',
        'temps_preparation': 15, 'temps_cuisson': 30, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['400 g de pommes de terre', '300 g de chou vert ou kale', '1 chorizo',
                        '1 oignon', '3 gousses d\'ail', '1 L de bouillon de légumes', 'Huile d\'olive', 'Sel'],
        'etapes': ['Faire revenir oignon et ail dans l\'huile d\'olive.',
                   'Ajouter pommes de terre en cubes et bouillon. Cuire 20 min.',
                   'Écraser grossièrement les pommes de terre dans le bouillon.',
                   'Émincer finement le chou en chiffonnade. Ajouter 5 min avant la fin.',
                   'Servir avec rondelles de chorizo grillé et huile d\'olive.'],
        'tags': ['Soupe', 'Minho', 'Réconfort', 'Hiver'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Caldo_verde.jpg/800px-Caldo_verde.jpg',
    },
    {
        'titre': 'Francesinha do Porto',
        'pays': 'portugal',
        'description': 'Le croque-monsieur portugais version extrême : viandes, fromage fondu et sauce tomate-bière.',
        'temps_preparation': 20, 'temps_cuisson': 20, 'nb_personnes': 2, 'difficulte': 'Moyen',
        'ingredients': ['4 tranches de pain de mie', '2 tranches de jambon', '2 saucisses linguiça',
                        '200 g de fromage à fondre', '400 ml de sauce tomate', '200 ml de bière',
                        'Piment, laurier', 'Frites pour accompagner'],
        'etapes': ['Assembler le sandwich : pain, jambon, saucisse grillée, pain.',
                   'Couvrir entièrement de fromage râpé.',
                   'Préparer la sauce : tomates, bière, piment, laurier — mijoter 15 min.',
                   'Napper le sandwich de sauce chaude.',
                   'Faire gratiner 3 min au four. Servir avec frites.'],
        'tags': ['Porto', 'Sandwich', 'Comfort food', 'Fromage'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Francesinha.jpg/800px-Francesinha.jpg',
    },

    # ── TURKEY ───────────────────────────────────────────────────────────────
    {
        'titre': 'Köfte (Boulettes Turques)',
        'pays': 'turkey',
        'description': 'Boulettes de viande épicées grillées, servies avec riz pilav, salade et sauce yaourt.',
        'temps_preparation': 20, 'temps_cuisson': 15, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['500 g de bœuf haché', '1 oignon râpé', '2 gousses d\'ail', '1 œuf',
                        'Persil, cumin, paprika', '50 g de chapelure', 'Sel, poivre'],
        'etapes': ['Mélanger bœuf, oignon, ail, œuf, chapelure et épices.',
                   'Façonner en petites boulettes ovales de 3 cm.',
                   'Griller à feu vif sur barbecue ou poêle 5–6 min de chaque côté.',
                   'Servir avec riz pilav, salade tomate-oignon et cacık (yaourt à l\'ail).'],
        'tags': ['Grill', 'Épicé', 'Street food', 'Traditionnel'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Turkish_K%C3%B6fte.jpg/800px-Turkish_K%C3%B6fte.jpg',
    },
    {
        'titre': 'Döner Kebab',
        'pays': 'turkey',
        'description': 'Viande d\'agneau marinée rôtie à la broche verticale, servie dans du pain pita avec légumes et sauce.',
        'temps_preparation': 30, 'temps_cuisson': 90, 'nb_personnes': 4, 'difficulte': 'Moyen',
        'ingredients': ['600 g d\'agneau (épaule)', '200 ml de yaourt', '2 gousses d\'ail',
                        'Cumin, paprika, origan', 'Pain pita', 'Tomates, salade', 'Sauce yaourt-ail'],
        'etapes': ['Mariner l\'agneau tranché fin dans yaourt + épices minimum 4h.',
                   'Empiler les tranches et cuire au four à 180°C 1h30 en arrosant régulièrement.',
                   'Découper en copeaux fins.',
                   'Garnir le pain pita grillé de viande, tomates, salade et sauce.'],
        'tags': ['Street food', 'Pita', 'Istanbul', 'Populaire'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Doner_kebab_1.jpg/800px-Doner_kebab_1.jpg',
    },
    {
        'titre': 'Baklava',
        'pays': 'turkey',
        'description': 'Feuilleté de pâte filo aux pistaches et noix, imbibé de sirop de miel et eau de rose.',
        'temps_preparation': 45, 'temps_cuisson': 35, 'nb_personnes': 12, 'difficulte': 'Moyen',
        'ingredients': ['500 g de pâte filo', '200 g de pistaches non salées', '150 g de noix',
                        '200 g de beurre clarifié', '300 g de sucre', '200 ml d\'eau', 'Eau de rose'],
        'etapes': ['Hacher grossièrement pistaches et noix.',
                   'Superposer 8 feuilles de filo en badigeonnant de beurre à chaque couche.',
                   'Étaler les fruits secs, continuer avec 8 autres couches de filo.',
                   'Découper en losanges et cuire 30–35 min à 170°C.',
                   'Napper de sirop chaud (sucre + eau + eau de rose) dès la sortie du four.'],
        'tags': ['Dessert', 'Istanbul', 'Pistache', 'Festif'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Baklava_-_Turkish_special%2C_fresh_out_of_the_oven_%283392593238%29.jpg/800px-Baklava_-_Turkish_special%2C_fresh_out_of_the_oven_%283392593238%29.jpg',
    },
    {
        'titre': 'Lahmacun',
        'pays': 'turkey',
        'description': 'La "pizza turque" : fine galette garnie de viande hachée épicée et herbes fraîches.',
        'temps_preparation': 30, 'temps_cuisson': 10, 'nb_personnes': 4, 'difficulte': 'Moyen',
        'ingredients': ['400 g de pâte à pain', '300 g d\'agneau haché', '2 tomates', '1 oignon',
                        'Persil, piment rouge', 'Paprika, cumin', 'Citron, salade verte'],
        'etapes': ['Mixer viande hachée, tomates, oignon, persil et épices en pâte homogène.',
                   'Étaler la pâte très finement (2 mm) en disques de 25 cm.',
                   'Étaler une fine couche de farce sur chaque disque.',
                   'Cuire 8–10 min à 240°C sur une plaque très chaude.',
                   'Servir roulé avec salade et jus de citron.'],
        'tags': ['Pizza', 'Galette', 'Épicé', 'Street food'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Lahmacun_2.jpg/800px-Lahmacun_2.jpg',
    },

    # ── NETHERLANDS ─────────────────────────────────────────────────────────
    {
        'titre': 'Stamppot Boerenkool',
        'pays': 'netherlands',
        'description': 'Purée de pommes de terre au chou frisé, lard fumé et saucisse rookworst — plat néerlandais de l\'hiver.',
        'temps_preparation': 15, 'temps_cuisson': 30, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['1 kg de pommes de terre', '500 g de chou frisé (boerenkool)', '200 g de lardons',
                        '2 saucisses fumées rookworst', '100 ml de lait', '50 g de beurre', 'Moutarde, sel'],
        'etapes': ['Cuire pommes de terre et chou ensemble dans une casserole d\'eau salée.',
                   'Faire dorer les lardons à sec. Réchauffer les saucisses.',
                   'Écraser pommes de terre et chou avec beurre et lait.',
                   'Incorporer les lardons. Servir avec saucisse et moutarde.'],
        'tags': ['Hiver', 'Traditionnel', 'Réconfort', 'Amsterdam'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Boerenkool_Stamppot.jpg/800px-Boerenkool_Stamppot.jpg',
    },
    {
        'titre': 'Stroopwafels',
        'pays': 'netherlands',
        'description': 'Gaufrettes hollandaises fines garnies d\'un caramel sirupeux — à poser sur une tasse de thé chaud.',
        'temps_preparation': 30, 'temps_cuisson': 20, 'nb_personnes': 20, 'difficulte': 'Moyen',
        'ingredients': ['250 g de farine', '125 g de beurre', '75 g de sucre', '1 œuf', '7 g de levure',
                        '150 g de sirop de canne', '100 g de cassonade', '1 c. cannelle'],
        'etapes': ['Mélanger farine, beurre, sucre, œuf et levure. Laisser reposer 30 min.',
                   'Former des billes de 25 g et cuire dans un gaufrier fin.',
                   'Préparer le caramel : sirop + cassonade + cannelle, cuire 5 min.',
                   'Couper chaque gaufrette en deux, garnir de caramel chaud, refermer.'],
        'tags': ['Biscuit', 'Gouda', 'Café', 'Sucrerie'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Stroopwafels.jpg/800px-Stroopwafels.jpg',
    },
    {
        'titre': 'Bitterballen',
        'pays': 'netherlands',
        'description': 'Croquettes rondes de ragout de bœuf panées frites, incontournables des cafés bruns d\'Amsterdam.',
        'temps_preparation': 30, 'temps_cuisson': 5, 'nb_personnes': 4, 'difficulte': 'Moyen',
        'ingredients': ['300 g de bœuf haché cuit', '50 g de beurre', '50 g de farine', '300 ml de bouillon',
                        'Persil, noix de muscade', '2 œufs', 'Chapelure', 'Huile de friture'],
        'etapes': ['Préparer le ragout : beurre + farine en roux, ajouter bouillon, viande, persil et muscade.',
                   'Étaler sur plaque et réfrigérer 3h jusqu\'à solidification.',
                   'Former des boules de 3 cm. Paner : farine, œuf battu, chapelure.',
                   'Frire à 180°C 3–4 min jusqu\'à dorure.'],
        'tags': ['Apéro', 'Café brun', 'Amsterdam', 'Friture'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Bitterballen.jpg/800px-Bitterballen.jpg',
    },

    # ── BELGIUM ──────────────────────────────────────────────────────────────
    {
        'titre': 'Moules-Frites',
        'pays': 'belgium',
        'description': 'Le plat national belge : moules marinières au vin blanc, avec frites dorées et mayonnaise.',
        'temps_preparation': 20, 'temps_cuisson': 15, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['2 kg de moules fraîches', '200 ml de vin blanc sec', '2 oignons', '3 branches de céleri',
                        'Beurre, thym, laurier', '1 kg de pommes de terre', 'Huile de friture', 'Mayonnaise'],
        'etapes': ['Gratter et rincer les moules. Jeter celles ouvertes.',
                   'Faire revenir oignons et céleri dans le beurre. Ajouter vin blanc et herbes.',
                   'Ajouter les moules à feu vif. Couvrir et cuire 5 min en secouant.',
                   'Couper les pommes de terre en frites. Frire deux fois (150°C puis 180°C).',
                   'Servir les moules en marmite avec frites et mayonnaise.'],
        'tags': ['Moules', 'Bruxelles', 'Mer du Nord', 'Convivial'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Moules-frites.jpg/800px-Moules-frites.jpg',
    },
    {
        'titre': 'Gaufres de Liège',
        'pays': 'belgium',
        'description': 'Gaufres épaisses et moelleuses aux perles de sucre caramélisées, recette liégeoise originale.',
        'temps_preparation': 20, 'temps_cuisson': 15, 'nb_personnes': 8, 'difficulte': 'Facile',
        'ingredients': ['300 g de farine', '10 g de levure', '150 g de beurre', '2 œufs',
                        '100 ml de lait tiède', '200 g de sucre perlé', '1 sachet de sucre vanillé', 'Sel'],
        'etapes': ['Dissoudre la levure dans le lait tiède.',
                   'Mélanger farine, œufs, beurre ramolli, sel et vanille. Ajouter le lait levuré.',
                   'Pétrir 5 min. Laisser lever 1h30.',
                   'Incorporer le sucre perlé délicatement.',
                   'Cuire dans un gaufrier bien chaud 4–5 min. Servir tièdes.'],
        'tags': ['Liège', 'Brunch', 'Sucré', 'Boulangerie'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Liege_waffle.jpg/800px-Liege_waffle.jpg',
    },
    {
        'titre': 'Carbonnade Flamande',
        'pays': 'belgium',
        'description': 'Bœuf mijoté à la bière brune belge avec pain d\'épice moutardé — le bœuf bourguignon flamand.',
        'temps_preparation': 20, 'temps_cuisson': 150, 'nb_personnes': 6, 'difficulte': 'Moyen',
        'ingredients': ['1,2 kg de bœuf (joue ou paleron)', '500 ml de bière brune belge (Leffe)',
                        '3 oignons', '2 tranches de pain d\'épice', '2 c. de moutarde', 'Thym, laurier', 'Cassonade'],
        'etapes': ['Dorer les morceaux de bœuf dans une cocotte. Réserver.',
                   'Faire revenir les oignons émincés jusqu\'à caramélisation.',
                   'Remettre la viande, ajouter la bière brune, thym et laurier.',
                   'Tartiner le pain d\'épice de moutarde et poser sur le dessus.',
                   'Mijoter 2h30 à feu très doux. Rectifier avec cassonade si nécessaire.'],
        'tags': ['Braisé', 'Bière', 'Flandre', 'Hiver'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Carbonnade_flamande.jpg/800px-Carbonnade_flamande.jpg',
    },

    # ── GREECE ───────────────────────────────────────────────────────────────
    {
        'titre': 'Moussaka',
        'pays': 'greece',
        'description': 'Gratin grec : couches d\'aubergines, d\'agneau haché à la tomate et béchamel crémeuse gratinée.',
        'temps_preparation': 40, 'temps_cuisson': 60, 'nb_personnes': 6, 'difficulte': 'Moyen',
        'ingredients': ['3 aubergines', '600 g d\'agneau haché', '400 g de tomates concassées',
                        '2 oignons', 'Cannelle, muscade', '500 ml de béchamel', '100 g de feta', 'Huile d\'olive'],
        'etapes': ['Couper et saler les aubergines 30 min. Rincer, sécher, faire dorer dans l\'huile.',
                   'Faire revenir oignons et agneau. Ajouter tomates et épices. Mijoter 20 min.',
                   'Alterner couches d\'aubergine et de viande dans un plat.',
                   'Couvrir de béchamel, émietter la feta.',
                   'Cuire 45 min à 180°C jusqu\'à dorure.'],
        'tags': ['Gratiné', 'Athènes', 'Traditionnel', 'Agneau'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Moussaka_2.jpg/800px-Moussaka_2.jpg',
    },
    {
        'titre': 'Souvlaki',
        'pays': 'greece',
        'description': 'Brochettes de porc marinées à l\'origan et citron, servies dans un pita avec tzatziki.',
        'temps_preparation': 20, 'temps_cuisson': 15, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['600 g de porc (épaule)', 'Origan, thym', '3 c. d\'huile d\'olive', 'Jus de 1 citron',
                        'Pains pita', '200 g de yaourt grec', '1 concombre', '2 gousses d\'ail'],
        'etapes': ['Couper le porc en cubes de 3 cm. Mariner avec huile, citron et herbes 2h.',
                   'Enfiler sur brochettes et griller 12–15 min en retournant.',
                   'Préparer le tzatziki : yaourt + concombre râpé égoutté + ail + menthe.',
                   'Servir dans le pita grillé avec tzatziki et tomates.'],
        'tags': ['Grill', 'Street food', 'Athènes', 'Brochette'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Greek_souvlaki.jpg/800px-Greek_souvlaki.jpg',
    },
    {
        'titre': 'Spanakopita',
        'pays': 'greece',
        'description': 'Tarte feuilletée grecque aux épinards, feta et herbes fraîches, en couches de pâte filo.',
        'temps_preparation': 30, 'temps_cuisson': 40, 'nb_personnes': 8, 'difficulte': 'Moyen',
        'ingredients': ['500 g d\'épinards frais', '300 g de feta', '3 œufs', '2 oignons verts',
                        'Aneth, menthe fraîche', '12 feuilles de pâte filo', '100 g de beurre clarifié'],
        'etapes': ['Faire revenir épinards et oignons verts. Bien égoutter.',
                   'Mélanger épinards, feta émiettée, œufs et herbes.',
                   'Superposer 6 feuilles de filo beurrées dans un moule.',
                   'Verser la garniture, couvrir de 6 autres feuilles beurrées.',
                   'Inciser en portions, cuire 35–40 min à 180°C.'],
        'tags': ['Épinards', 'Végétarien', 'Feta', 'Crète'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Spanakopita.jpg/800px-Spanakopita.jpg',
    },
    {
        'titre': 'Tzatziki',
        'pays': 'greece',
        'description': 'Sauce fraîche grecque au yaourt, concombre, ail et aneth — indispensable en mezze.',
        'temps_preparation': 15, 'temps_cuisson': 0, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['400 g de yaourt grec épais (0% égoutté)', '1 concombre', '3 gousses d\'ail',
                        'Aneth frais', 'Jus de citron', 'Huile d\'olive', 'Sel, poivre'],
        'etapes': ['Râper le concombre, saler et laisser dégorger 20 min dans une passoire.',
                   'Bien essorer le concombre avec les mains.',
                   'Mélanger yaourt, concombre, ail écrasé, aneth et jus de citron.',
                   'Arroser d\'huile d\'olive. Réfrigérer 1h avant service.'],
        'tags': ['Sauce', 'Mezze', 'Végétarien', 'Rapide'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Tzatziki_%28Greece%29.jpg/800px-Tzatziki_%28Greece%29.jpg',
    },

    # ── NORWAY ───────────────────────────────────────────────────────────────
    {
        'titre': 'Gravlaks',
        'pays': 'norway',
        'description': 'Saumon mariné à la scandinave dans sel, sucre et aneth — servi finement tranché avec moutarde douce.',
        'temps_preparation': 20, 'temps_cuisson': 0, 'nb_personnes': 8, 'difficulte': 'Facile',
        'ingredients': ['1 kg de saumon frais (filet avec peau)', '3 c. de gros sel',
                        '2 c. de sucre', '1 bouquet d\'aneth', 'Poivre blanc concassé', 'Sauce moutarde-aneth'],
        'etapes': ['Mélanger sel, sucre et poivre. Hacher grossièrement l\'aneth.',
                   'Frotter le saumon avec le mélange sel-sucre des deux côtés.',
                   'Couvrir généreusement d\'aneth haché.',
                   'Emballer dans du film alimentaire, peser et réfrigérer 48h en retournant.',
                   'Trancher finement en biais. Servir avec sauce moutarde et pain de seigle.'],
        'tags': ['Saumon', 'Scandinave', 'Fumé', 'Apéro'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Gravlax.jpg/800px-Gravlax.jpg',
    },
    {
        'titre': 'Fårikål',
        'pays': 'norway',
        'description': 'Le plat national norvégien : mouton mijoté longuement avec chou et grains de poivre noir.',
        'temps_preparation': 10, 'temps_cuisson': 120, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['1 kg d\'épaule de mouton avec os', '1 chou blanc (1 kg)', '1 c. de grains de poivre',
                        '1 c. de sel', '300 ml d\'eau', 'Pain de seigle pour accompagner'],
        'etapes': ['Couper le mouton en morceaux et le chou en larges quartiers.',
                   'Alterner couches de mouton et de chou dans une cocotte.',
                   'Ajouter grains de poivre et sel. Couvrir d\'eau.',
                   'Porter à ébullition puis mijoter 2h à feu très doux.',
                   'Servir directement dans la cocotte avec pain de seigle.'],
        'tags': ['Agneau', 'Chou', 'Automne', 'Traditionnel'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/F%C3%A5rik%C3%A5l.jpg/800px-F%C3%A5rik%C3%A5l.jpg',
    },
    {
        'titre': 'Kjøttkaker',
        'pays': 'norway',
        'description': 'Boulettes de viande norvégiennes en sauce brune crémeuse — version locale des Swedish meatballs.',
        'temps_preparation': 20, 'temps_cuisson': 25, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['500 g de bœuf haché', '1 œuf', '50 ml de lait', '50 g de chapelure',
                        '1 oignon', 'Muscade, sel, poivre', '300 ml de fond de veau', '100 ml de crème'],
        'etapes': ['Mélanger bœuf, œuf, lait, chapelure, oignon râpé et épices.',
                   'Former des boulettes de 5 cm et faire dorer dans le beurre.',
                   'Préparer la sauce : fond de veau + farine + crème, mijoter 10 min.',
                   'Remettre les boulettes dans la sauce. Cuire 15 min à couvert.',
                   'Servir avec purée de pommes de terre et airelles.'],
        'tags': ['Boulettes', 'Sauce brune', 'Réconfort', 'Oslo'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Kjøttkaker.jpg/800px-Kjøttkaker.jpg',
    },

    # ── DENMARK ──────────────────────────────────────────────────────────────
    {
        'titre': 'Smørrebrød',
        'pays': 'denmark',
        'description': 'Les tartines ouvertes danoises sur pain de seigle : hareng mariné, crevettes ou rosbif garnies.',
        'temps_preparation': 20, 'temps_cuisson': 0, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['8 tranches de pain de seigle', '200 g de hareng mariné', '150 g de crevettes grises',
                        '2 œufs durs', 'Mayonnaise, crème fraîche', 'Aneth, radis', 'Cornichons'],
        'etapes': ['Tartiner le pain de seigle de beurre ou crème fraîche.',
                   'Disposer le hareng mariné avec oignon rouge et câpres.',
                   'Pour les crevettes : mayonnaise + crevettes + aneth + citron.',
                   'Garnir avec œufs durs tranchés, radis et cornichons.'],
        'tags': ['Copenhague', 'Ouvert', 'Traditionnel', 'Brunch'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Open_sandwich_Denmark.jpg/800px-Open_sandwich_Denmark.jpg',
    },
    {
        'titre': 'Æbleskiver',
        'pays': 'denmark',
        'description': 'Petites boules de pâte levée danoises, cuites dans un moule spécial, servies avec confiture et sucre glace.',
        'temps_preparation': 15, 'temps_cuisson': 20, 'nb_personnes': 4, 'difficulte': 'Moyen',
        'ingredients': ['250 g de farine', '3 œufs', '300 ml de lait fermenté (kefir)', '25 g de beurre',
                        '1 sachet de levure', 'Sucre, sel', 'Confiture de groseilles', 'Sucre glace'],
        'etapes': ['Séparer jaunes et blancs d\'œufs.',
                   'Mélanger farine, levure, sel, sucre, jaunes et lait fermenté.',
                   'Incorporer le beurre fondu. Battre les blancs en neige et les plier.',
                   'Chauffer le moule æbleskiver beurré. Remplir chaque cavité aux 2/3.',
                   'Retourner avec une brochette quand le dessous est doré. Servir avec confiture.'],
        'tags': ['Dessert', 'Noël', 'Danemark', 'Brunch'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Aebleskiver.jpg/800px-Aebleskiver.jpg',
    },
    {
        'titre': 'Flæskesteg (Rôti de Porc Danois)',
        'pays': 'denmark',
        'description': 'Rôti de porc avec couenne ultra-croustillante, classique du réveillon danois.',
        'temps_preparation': 15, 'temps_cuisson': 90, 'nb_personnes': 6, 'difficulte': 'Facile',
        'ingredients': ['1,5 kg de carré de porc avec couenne', 'Gros sel', 'Clous de girofle',
                        '3 feuilles de laurier', 'Pommes de terre', 'Chou rouge braisé', 'Jus de cuisson'],
        'etapes': ['Inciser la couenne en losanges profonds. Frotter généreusement de gros sel.',
                   'Piquer de clous de girofle aux intersections, glisser le laurier.',
                   'Rôtir sur grille à 200°C pendant 1h30.',
                   'Monter le four à 250°C les 10 dernières minutes pour faire souffler la couenne.',
                   'Laisser reposer 10 min. Servir avec pommes de terre et chou rouge.'],
        'tags': ['Porc', 'Noël', 'Couenne', 'Festif'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Fl%C3%A6skesteg.jpg/800px-Fl%C3%A6skesteg.jpg',
    },

    # ── CZECH REPUBLIC ───────────────────────────────────────────────────────
    {
        'titre': 'Svíčková na Smetaně',
        'pays': 'czech republic',
        'description': 'Filet de bœuf braisé en sauce à la crème et légumes, servi avec knedlíky et airelles.',
        'temps_preparation': 30, 'temps_cuisson': 120, 'nb_personnes': 4, 'difficulte': 'Moyen',
        'ingredients': ['800 g de filet de bœuf', '2 carottes', '1 panais', '1 oignon', '200 ml de crème',
                        '100 ml de vin blanc', 'Thym, laurier, grains de poivre', 'Knedlíky (boulettes de pain)'],
        'etapes': ['Faire dorer le bœuf dans une cocotte. Réserver.',
                   'Faire revenir légumes coupés en brunoise. Déglacer au vin blanc.',
                   'Remettre la viande, couvrir et braiser 2h à 160°C.',
                   'Retirer la viande. Mixer la sauce, ajouter la crème, rectifier.',
                   'Trancher le bœuf. Servir nappé de sauce avec knedlíky et airelles.'],
        'tags': ['Prague', 'Braisé', 'Crème', 'Traditionnel'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Sv%C3%AD%C4%8Dkov%C3%A1_na_smetan%C4%9B.jpg/800px-Sv%C3%AD%C4%8Dkov%C3%A1_na_smetan%C4%9B.jpg',
    },
    {
        'titre': 'Vepřo Knedlo Zelo',
        'pays': 'czech republic',
        'description': 'La Sainte Trinité tchèque : porc rôti, knedlíky et choucroute — plat dominical national.',
        'temps_preparation': 20, 'temps_cuisson': 90, 'nb_personnes': 4, 'difficulte': 'Moyen',
        'ingredients': ['800 g d\'épaule de porc', '500 g de choucroute', '3 oignons', 'Carvi, sel',
                        '500 g de farine (knedlíky)', '2 petits pains rassis', '2 œufs', '200 ml de lait'],
        'etapes': ['Rôtir le porc assaisonné avec oignons et carvi 1h30 à 180°C.',
                   'Préparer les knedlíky : mélanger farine, pain en cubes, œufs et lait. Façonner des rouleaux.',
                   'Cuire les rouleaux 20 min dans l\'eau bouillante. Trancher.',
                   'Réchauffer la choucroute avec un peu de graisse du rôti et carvi.',
                   'Servir porc tranché avec sauce de cuisson, knedlíky et choucroute.'],
        'tags': ['Bohême', 'Rôti', 'Dominical', 'Traditionnel'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Vepro_knedlo_zelo.jpg/800px-Vepro_knedlo_zelo.jpg',
    },
    {
        'titre': 'Trdelník',
        'pays': 'czech republic',
        'description': 'Gâteau de rue praguois : pâte enroulée sur bâton, grillée sur braise, roulée dans sucre et cannelle.',
        'temps_preparation': 30, 'temps_cuisson': 15, 'nb_personnes': 6, 'difficulte': 'Moyen',
        'ingredients': ['500 g de farine', '7 g de levure', '250 ml de lait', '50 g de beurre', '50 g de sucre',
                        '2 jaunes d\'œuf', 'Zeste de citron', '100 g de sucre + 2 c. cannelle (enrobage)'],
        'etapes': ['Préparer la pâte levée en mélangeant tous les ingrédients. Laisser lever 1h.',
                   'Diviser en bandes longues de 2 cm de large.',
                   'Enrouler en spirale autour d\'un bâton ou rouleau.',
                   'Griller au four à 200°C ou sur braise en tournant régulièrement.',
                   'Rouler chaud dans le mélange sucre-cannelle.'],
        'tags': ['Prague', 'Street food', 'Dessert', 'Boulangerie'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Trdelnik.jpg/800px-Trdelnik.jpg',
    },

    # ── AZERBAIJAN ───────────────────────────────────────────────────────────
    {
        'titre': 'Plov Azerbaïdjanais',
        'pays': 'azerbaijan',
        'description': 'Riz safrané au beurre sur Gazmag (croûte croustillante), avec agneau aux épices et fruits secs.',
        'temps_preparation': 30, 'temps_cuisson': 60, 'nb_personnes': 6, 'difficulte': 'Difficile',
        'ingredients': ['500 g de riz basmati', '600 g d\'agneau', '100 g de pruneaux',
                        '50 g d\'abricots secs', '50 g de raisins secs', 'Safran', '100 g de beurre clarifié',
                        'Cannelle, cardamome', 'Sel'],
        'etapes': ['Faire tremper le riz 2h. Cuire à demi dans l\'eau bouillante salée. Égoutter.',
                   'Préparer le gazmag : pâte fine beurrée au fond du chaudron.',
                   'Remettre le riz en dôme, arroser de beurre clarifié + safran infusé.',
                   'Cuire à couvert à feu très doux 40 min (la croûte doit rester intacte).',
                   'Faire revenir l\'agneau avec fruits secs et épices séparément. Servir ensemble.'],
        'tags': ['Bakou', 'Riz', 'Safran', 'Festif'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Azerbaijani_plov.jpg/800px-Azerbaijani_plov.jpg',
    },
    {
        'titre': 'Dolma (Feuilles de Vigne)',
        'pays': 'azerbaijan',
        'description': 'Feuilles de vigne farcies de viande hachée, riz et herbes, mijotées dans un bouillon citronné.',
        'temps_preparation': 45, 'temps_cuisson': 45, 'nb_personnes': 4, 'difficulte': 'Moyen',
        'ingredients': ['30 feuilles de vigne en saumure', '300 g d\'agneau haché', '100 g de riz cru',
                        '2 oignons', 'Menthe, coriandre, aneth', 'Jus de citron', 'Yaourt pour servir'],
        'etapes': ['Rincer les feuilles et les blanchir 2 min. Égoutter.',
                   'Mélanger viande, riz, oignons hachés et herbes. Assaisonner.',
                   'Déposer 1 c. de farce sur chaque feuille. Rouler en serrant.',
                   'Disposer en couches dans une cocotte. Couvrir d\'eau citronnée.',
                   'Cuire à feu doux 40 min. Servir avec yaourt froid.'],
        'tags': ['Feuilles de vigne', 'Traditionnel', 'Partage', 'Méditerranée'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Dolma_%28stuffed_grape_leaves%29.jpg/800px-Dolma_%28stuffed_grape_leaves%29.jpg',
    },
    {
        'titre': 'Dushbara',
        'pays': 'azerbaijan',
        'description': 'Petits raviolis azerbaïdjanais au bouillon, farce d\'agneau aux épices — les plus petits raviolis du monde.',
        'temps_preparation': 60, 'temps_cuisson': 20, 'nb_personnes': 4, 'difficulte': 'Difficile',
        'ingredients': ['300 g de farine', '1 œuf', '100 ml d\'eau', '200 g d\'agneau haché',
                        '1 oignon', 'Sumac, poivre', '1 L de bouillon d\'agneau', 'Menthe séchée'],
        'etapes': ['Préparer la pâte : farine, œuf, eau. Reposer 30 min.',
                   'Mélanger agneau, oignon finement haché, sumac et épices.',
                   'Abaisser la pâte très finement. Couper en carrés de 3 cm.',
                   'Poser une micro-portion de farce, plier en triangle et coller les bords.',
                   'Cuire dans le bouillon d\'agneau bouillant 5–7 min. Servir avec menthe et vinaigre.'],
        'tags': ['Raviolis', 'Bouillon', 'Bakou', 'Artisanal'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Dushbara.jpg/800px-Dushbara.jpg',
    },

    # ── MONACO ───────────────────────────────────────────────────────────────
    {
        'titre': 'Barbagiuan',
        'pays': 'monaco',
        'description': 'Beignets frits monégasques farcis aux blettes, ricotta et parmesan — spécialité de la fête nationale.',
        'temps_preparation': 40, 'temps_cuisson': 15, 'nb_personnes': 6, 'difficulte': 'Moyen',
        'ingredients': ['500 g de blettes', '200 g de ricotta', '50 g de parmesan', '2 œufs',
                        '300 g de farine (pâte)', '100 ml d\'eau', 'Huile d\'olive', 'Huile de friture', 'Sel'],
        'etapes': ['Préparer la pâte : farine, eau, huile d\'olive, sel. Reposer 30 min.',
                   'Faire revenir les blettes émincées à l\'huile. Laisser refroidir.',
                   'Mélanger blettes, ricotta, parmesan et œuf. Assaisonner.',
                   'Abaisser la pâte, découper des disques. Garnir et fermer en demi-lune.',
                   'Frire à 180°C jusqu\'à dorure. Servir chauds.'],
        'tags': ['Fête nationale', 'Beignet', 'Monaco', 'Apéro'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Barbagiuan.jpg/800px-Barbagiuan.jpg',
    },
    {
        'titre': 'Socca Niçoise',
        'pays': 'monaco',
        'description': 'Galette de farine de pois chiche grillée à l\'huile d\'olive et poivre noir — spécialité de la Côte d\'Azur.',
        'temps_preparation': 10, 'temps_cuisson': 15, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['250 g de farine de pois chiche', '500 ml d\'eau', '4 c. d\'huile d\'olive',
                        '1 c. de sel', 'Poivre noir grossier', 'Huile d\'olive pour le plat'],
        'etapes': ['Mélanger farine de pois chiche, eau, huile d\'olive et sel. Laisser reposer 1h.',
                   'Huiler généreusement une grande plaque ou poêle en fonte.',
                   'Verser la pâte en couche de 3–4 mm.',
                   'Cuire sous le grill très chaud 10–15 min jusqu\'à coloration et cloques.',
                   'Poivrer généreusement et couper en morceaux irréguliers. Servir chaud.'],
        'tags': ['Végétarien', 'Côte d\'Azur', 'Street food', 'Rapide'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Socca.jpg/800px-Socca.jpg',
    },
    {
        'titre': 'Stocaficada Monégasque',
        'pays': 'monaco',
        'description': 'Stockfish (morue séchée) mijoté avec tomates, pommes de terre, olives et herbes — tradition monégasque.',
        'temps_preparation': 30, 'temps_cuisson': 90, 'nb_personnes': 4, 'difficulte': 'Moyen',
        'ingredients': ['800 g de stockfish dessalé', '500 g de pommes de terre', '400 g de tomates',
                        '100 g d\'olives noires', '2 oignons', '2 poivrons', 'Herbes de Provence', 'Huile d\'olive'],
        'etapes': ['Couper le stockfish en morceaux. Réserver.',
                   'Faire revenir oignons et poivrons dans l\'huile d\'olive.',
                   'Ajouter tomates, olives et herbes. Cuire 10 min.',
                   'Ajouter le stockfish et les pommes de terre en cubes.',
                   'Mijoter à couvert 1h jusqu\'à ce que les pommes de terre soient fondantes.'],
        'tags': ['Morue', 'Monaco', 'Mijoté', 'Méditerranée'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Stockfish.jpg/800px-Stockfish.jpg',
    },

    # ── CYPRUS ───────────────────────────────────────────────────────────────
    {
        'titre': 'Halloumi Grillé',
        'pays': 'cyprus',
        'description': 'Fromage chypriote à la saumure résistant à la chaleur, grillé jusqu\'à la croûte dorée.',
        'temps_preparation': 5, 'temps_cuisson': 10, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['400 g de halloumi', 'Menthe fraîche', 'Jus de citron',
                        'Huile d\'olive', 'Poivre noir', 'Pain pita grillé'],
        'etapes': ['Couper le halloumi en tranches de 1 cm.',
                   'Chauffer une poêle ou grill à feu vif sans matière grasse.',
                   'Griller 2–3 min de chaque côté jusqu\'à coloration dorée.',
                   'Presser du citron immédiatement. Garnir de menthe fraîche.',
                   'Servir chaud avec pain pita et olives.'],
        'tags': ['Fromage', 'Végétarien', 'Grill', 'Méditerranée'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Grilled_halloumi.jpg/800px-Grilled_halloumi.jpg',
    },
    {
        'titre': 'Mezze Chypriote',
        'pays': 'cyprus',
        'description': 'Table de mezze : houmous, tzatziki, taramosalata, olives, légumes grillés et viandes marinées.',
        'temps_preparation': 30, 'temps_cuisson': 15, 'nb_personnes': 6, 'difficulte': 'Facile',
        'ingredients': ['200 g de houmous', '200 g de taramosalata', '200 g de tzatziki',
                        'Halloumi grillé', 'Olives vertes et noires', 'Légumes crus (carottes, concombre)',
                        'Pains pita', 'Loukoumades (beignets miel)'],
        'etapes': ['Préparer ou acheter les différentes sauces (houmous, tzatziki, taramosalata).',
                   'Griller le halloumi en tranches.',
                   'Chauffer les pains pita.',
                   'Dresser tous les éléments en petites assiettes sur la table.',
                   'Servir de façon conviviale en partage.'],
        'tags': ['Mezze', 'Partage', 'Nicosie', 'Convivial'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Cyprus_meze.jpg/800px-Cyprus_meze.jpg',
    },
    {
        'titre': 'Souvla',
        'pays': 'cyprus',
        'description': 'Grandes brochettes chypriotes d\'agneau ou de porc rôties lentement sur braise — version XXL du souvlaki.',
        'temps_preparation': 20, 'temps_cuisson': 90, 'nb_personnes': 6, 'difficulte': 'Moyen',
        'ingredients': ['1,5 kg d\'épaule d\'agneau', 'Origan, thym, romarin', 'Jus de citron',
                        'Huile d\'olive', '4 gousses d\'ail', 'Sel, poivre', 'Pain pita grillé'],
        'etapes': ['Couper la viande en gros morceaux de 8 cm. Mariner 4h.',
                   'Enfiler sur grandes brochettes métalliques.',
                   'Cuire sur braise à feu moyen 1h30 en tournant toutes les 15 min.',
                   'La viande doit être bien colorée et fondante.',
                   'Servir avec pain pita, salade et tahini.'],
        'tags': ['Grill', 'Braise', 'Agneau', 'Fête'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Souvla.jpg/800px-Souvla.jpg',
    },

    # ── KAZAKHSTAN ───────────────────────────────────────────────────────────
    {
        'titre': 'Beshbarmak',
        'pays': 'kazakhstan',
        'description': 'Le plat national kazakh : larges pâtes plates, agneau ou cheval bouilli, bouillon et oignons confits.',
        'temps_preparation': 30, 'temps_cuisson': 120, 'nb_personnes': 6, 'difficulte': 'Moyen',
        'ingredients': ['1 kg d\'agneau (jarret ou épaule)', '400 g de farine', '2 œufs', '3 oignons',
                        '3 carottes', 'Sel, poivre noir', 'Persil frais'],
        'etapes': ['Cuire l\'agneau avec carottes 2h dans grande quantité d\'eau salée. Réserver le bouillon.',
                   'Préparer la pâte : farine + œufs + eau. Abaisser et couper en losanges.',
                   'Cuire les pâtes dans le bouillon frémissant 5 min.',
                   'Faire revenir les oignons émincés dans le gras jusqu\'à caramélisation.',
                   'Dresser : pâtes, viande effilochée, oignons. Servir le bouillon en accompagnement.'],
        'tags': ['National', 'Steppe', 'Partage', 'Agneau'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Beshbarmak.jpg/800px-Beshbarmak.jpg',
    },
    {
        'titre': 'Samsa (Samoussas Kazakhs)',
        'pays': 'kazakhstan',
        'description': 'Chaussons feuilletés farcis d\'agneau haché et oignons, cuits au four dans un tandyr.',
        'temps_preparation': 40, 'temps_cuisson': 25, 'nb_personnes': 6, 'difficulte': 'Moyen',
        'ingredients': ['400 g de farine', '100 g de beurre', '150 ml d\'eau', '400 g d\'agneau haché',
                        '3 oignons', 'Cumin, sel, poivre', 'Graines de sésame (dorure)', '1 œuf'],
        'etapes': ['Préparer la pâte feuilletée rapide : farine, beurre, eau. Étaler et plier 3 fois.',
                   'Mélanger agneau, oignons hachés, cumin, sel et poivre.',
                   'Couper la pâte en carrés de 15 cm. Garnir avec 2 c. de farce.',
                   'Fermer en triangle et bien souder les bords.',
                   'Dorer à l\'œuf, parsemer de sésame. Cuire 20–25 min à 200°C.'],
        'tags': ['Feuilleté', 'Street food', 'Almaty', 'Agneau'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Samsa_Kazakhstan.jpg/800px-Samsa_Kazakhstan.jpg',
    },
    {
        'titre': 'Pilav Kazakh (Palov)',
        'pays': 'kazakhstan',
        'description': 'Riz pilaf des steppes : agneau, carottes jaunes et rouges, ail entier et épices d\'Asie centrale.',
        'temps_preparation': 20, 'temps_cuisson': 60, 'nb_personnes': 6, 'difficulte': 'Moyen',
        'ingredients': ['500 g de riz long', '500 g d\'agneau', '400 g de carottes jaunes',
                        '300 g de carottes oranges', '2 oignons', '1 tête d\'ail entière',
                        'Cumin, safran', '100 ml d\'huile', 'Sel'],
        'etapes': ['Faire dorer l\'agneau en morceaux dans l\'huile dans un chaudron.',
                   'Ajouter oignons émincés, puis carottes en julienne épaisse.',
                   'Ajouter eau bouillante, cumin et safran. Cuire 30 min.',
                   'Verser le riz lavé sur la viande sans mélanger. Enfoncer l\'ail entier.',
                   'Couvrir et cuire à feu très doux 30 min. Mélanger et servir.'],
        'tags': ['Riz', 'Steppe', 'Festif', 'Asie centrale'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Plov_uzbek.jpg/800px-Plov_uzbek.jpg',
    },

    # ── SCOTLAND ─────────────────────────────────────────────────────────────
    {
        'titre': 'Haggis, Neeps and Tatties',
        'pays': 'scotland',
        'description': 'Le plat national écossais : haggis d\'agneau épicé avec purée de rutabaga et pommes de terre.',
        'temps_preparation': 20, 'temps_cuisson': 80, 'nb_personnes': 4, 'difficulte': 'Moyen',
        'ingredients': ['1 haggis (400 g, prêt à cuire)', '400 g de rutabaga (navet)', '600 g de pommes de terre',
                        'Beurre, crème', 'Whisky écossais', 'Sel, poivre noir'],
        'etapes': ['Cuire le haggis selon les instructions (four ou vapeur, ~80 min).',
                   'Cuire rutabaga et pommes de terre séparément dans eau salée.',
                   'Écraser le rutabaga avec beurre et noix de muscade.',
                   'Préparer la purée de pommes de terre crémeuse.',
                   'Flamber le haggis au whisky si désiré. Servir les trois ensemble.'],
        'tags': ['Burns Night', 'Agneau', 'Ecosse', 'Traditionnel'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Haggis_with_tatties_and_neeps.jpg/800px-Haggis_with_tatties_and_neeps.jpg',
    },
    {
        'titre': 'Cullen Skink',
        'pays': 'scotland',
        'description': 'Chowder écossais fumé : haddock fumé, pommes de terre et crème — soupe des pêcheurs de Cullen.',
        'temps_preparation': 15, 'temps_cuisson': 25, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['400 g de haddock fumé', '3 pommes de terre', '1 oignon', '500 ml de lait',
                        '200 ml de crème fraîche', 'Beurre', 'Persil frais', 'Sel, poivre'],
        'etapes': ['Pocher le haddock dans le lait 10 min. Retirer et émietter. Garder le lait.',
                   'Faire revenir l\'oignon dans le beurre. Ajouter pommes de terre en cubes.',
                   'Verser le lait de pochage. Cuire 15 min.',
                   'Écraser partiellement pour épaissir. Ajouter haddock et crème.',
                   'Chauffer sans bouillir. Garnir de persil haché.'],
        'tags': ['Soupe', 'Poisson', 'Côte est', 'Réconfort'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Cullen_skink.jpg/800px-Cullen_skink.jpg',
    },
    {
        'titre': 'Cranachan',
        'pays': 'scotland',
        'description': 'Dessert écossais : crème fouettée, flocons d\'avoine grillés, whisky, miel et framboises fraîches.',
        'temps_preparation': 20, 'temps_cuisson': 5, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['300 ml de crème entière', '50 g de flocons d\'avoine', '3 c. de miel',
                        '3 c. de whisky écossais', '250 g de framboises fraîches'],
        'etapes': ['Griller les flocons d\'avoine à sec dans une poêle jusqu\'à dorure. Laisser refroidir.',
                   'Monter la crème en chantilly souple.',
                   'Incorporer miel et whisky à la crème.',
                   'Plier délicatement les flocons d\'avoine et framboises.',
                   'Servir en verrines avec quelques framboises entières et filet de miel.'],
        'tags': ['Dessert', 'Whisky', 'Framboises', 'Ecosse'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Cranachan.jpg/800px-Cranachan.jpg',
    },

    # ── AUSTRIA ──────────────────────────────────────────────────────────────
    {
        'titre': 'Wiener Schnitzel',
        'pays': 'austria',
        'description': 'L\'escalope panée viennoise : veau aplati, panure fine au beurre, citron et persil.',
        'temps_preparation': 20, 'temps_cuisson': 10, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['4 escalopes de veau (150 g chacune)', '2 œufs', '100 g de chapelure fine',
                        '50 g de farine', '150 g de beurre clarifié', '1 citron', 'Sel'],
        'etapes': ['Aplatir les escalopes à 4 mm d\'épaisseur. Saler.',
                   'Paner dans cet ordre : farine, œuf battu, chapelure (ne pas presser).',
                   'Faire fondre le beurre clarifié dans une grande poêle à feu moyen.',
                   'Frire 2–3 min de chaque côté en arrosant de beurre. La chapelure doit souffler.',
                   'Égoutter, servir immédiatement avec quartier de citron et pommes de terre.'],
        'tags': ['Vienne', 'Escalope', 'Classique', 'Rapide'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Wiener-Schnitzel02.jpg/800px-Wiener-Schnitzel02.jpg',
    },
    {
        'titre': 'Apfelstrudel',
        'pays': 'austria',
        'description': 'Strudel aux pommes viennois : pâte étirée très fine enroulant pommes, raisins et cannelle.',
        'temps_preparation': 45, 'temps_cuisson': 35, 'nb_personnes': 8, 'difficulte': 'Difficile',
        'ingredients': ['300 g de farine', '150 ml d\'eau tiède', '2 c. d\'huile', '1 kg de pommes',
                        '100 g de raisins secs', '80 g de chapelure', '80 g de sucre', '2 c. de cannelle',
                        '100 g de beurre fondu'],
        'etapes': ['Préparer la pâte en mélangeant farine, eau et huile. Reposer 30 min enveloppée.',
                   'Étirer sur nappe farinée jusqu\'à épaisseur d\'un tissu (on doit voir la main en dessous).',
                   'Dorer la chapelure dans le beurre et répartir sur la pâte.',
                   'Garnir de pommes, raisins, sucre et cannelle. Rouler sans serrer.',
                   'Badigeonner de beurre, cuire 30–35 min à 190°C. Saupoudrer de sucre glace.'],
        'tags': ['Dessert', 'Vienne', 'Pommes', 'Feuilleté'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Apfelstrudel_mit_Schlagobers.jpg/800px-Apfelstrudel_mit_Schlagobers.jpg',
    },
    {
        'titre': 'Sachertorte',
        'pays': 'austria',
        'description': 'Le gâteau au chocolat noir viennois avec couche d\'abricot et glaçage miroir, né au Hôtel Sacher.',
        'temps_preparation': 45, 'temps_cuisson': 55, 'nb_personnes': 12, 'difficulte': 'Difficile',
        'ingredients': ['150 g de chocolat noir 70%', '130 g de beurre', '130 g de sucre glace',
                        '6 œufs', '150 g de farine', '200 g de confiture d\'abricot',
                        '200 g de chocolat noir (glaçage)', '100 ml de crème'],
        'etapes': ['Fondre chocolat et beurre. Incorporer sucre glace, jaunes et farine.',
                   'Battre les blancs en neige ferme et les plier délicatement.',
                   'Cuire dans un moule de 24 cm, 50–55 min à 170°C. Laisser refroidir.',
                   'Couper horizontalement. Napper l\'intérieur et l\'extérieur de confiture chaude.',
                   'Préparer le glaçage : chocolat fondu + crème chaude. Napper et lisser.'],
        'tags': ['Vienne', 'Chocolat', 'Festif', 'Pâtisserie'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Sachertorte_DSC03027.jpg/800px-Sachertorte_DSC03027.jpg',
    },

    # ── SWITZERLAND ──────────────────────────────────────────────────────────
    {
        'titre': 'Fondue au Fromage',
        'pays': 'switzerland',
        'description': 'La fondue suisse par excellence : gruyère et emmental fondus dans le vin blanc et kirsch.',
        'temps_preparation': 15, 'temps_cuisson': 15, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['400 g de gruyère râpé', '400 g d\'emmental râpé', '300 ml de vin blanc sec',
                        '1 gousse d\'ail', '2 c. de Maïzena', '2 cl de kirsch', 'Noix de muscade',
                        '1 baguette ou pain campagne pour tremper'],
        'etapes': ['Frotter le caquelon avec la gousse d\'ail coupée.',
                   'Verser le vin blanc et chauffer doucement.',
                   'Ajouter les fromages en mélangeant en 8 jusqu\'à fonte.',
                   'Délayer la Maïzena dans le kirsch et incorporer à la fondue.',
                   'Assaisonner de muscade. Maintenir au chaud. Tremper les morceaux de pain.'],
        'tags': ['Convivial', 'Hiver', 'Fromage', 'Neuchâtel'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Cheese_fondue.jpg/800px-Cheese_fondue.jpg',
    },
    {
        'titre': 'Rösti',
        'pays': 'switzerland',
        'description': 'Galette de pommes de terre râpées dorée dans le beurre — le rösti bernois croustillant.',
        'temps_preparation': 15, 'temps_cuisson': 20, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['800 g de pommes de terre (à chair ferme)', '50 g de beurre clarifié', 'Sel, poivre'],
        'etapes': ['Précuire les pommes de terre 10 min dans l\'eau (elles doivent rester fermes).',
                   'Éplucher et râper grossièrement. Assaisonner.',
                   'Faire fondre le beurre dans une poêle de 26 cm.',
                   'Presser les pommes de terre râpées pour former une galette.',
                   'Cuire 10 min à feu moyen, retourner sur couvercle et cuire encore 10 min.'],
        'tags': ['Berne', 'Accompagnement', 'Végétarien', 'Rapide'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/R%C3%B6sti.jpg/800px-R%C3%B6sti.jpg',
    },
    {
        'titre': 'Raclette',
        'pays': 'switzerland',
        'description': 'Fromage de Raclette fondu raclé sur pommes de terre, cornichons et charcuterie.',
        'temps_preparation': 10, 'temps_cuisson': 30, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['600 g de fromage à raclette en tranches', '1 kg de petites pommes de terre',
                        'Cornichons', 'Oignons grelots au vinaigre', 'Viande des Grisons', 'Jambon cru'],
        'etapes': ['Cuire les pommes de terre en robe des champs à l\'eau salée.',
                   'Disposer tranches de fromage dans le poêlon du appareil à raclette.',
                   'Faire fondre sous la résistance chauffante.',
                   'Racler le fromage fondu sur les pommes de terre dans l\'assiette.',
                   'Accompagner de cornichons, oignons et charcuterie.'],
        'tags': ['Convivial', 'Fromage', 'Valais', 'Hiver'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Raclette.jpg/800px-Raclette.jpg',
    },
]


class Command(BaseCommand):
    help = 'Charge les recettes supplémentaires (Part 2 : PT, TR, NL, BE, GR, NO, DK, CZ, AZ, MC, CY, KZ, SCO, AT, CH)'

    def handle(self, *args, **options):
        created, updated = 0, 0
        for data in RECIPES_EXTRA:
            obj, was_created = Recipe.objects.update_or_create(
                titre=data['titre'],
                pays=data['pays'],
                defaults=data,
            )
            if was_created:
                created += 1
            else:
                updated += 1
        self.stdout.write(self.style.SUCCESS(
            f'Done — {created} created, {updated} updated ({created + updated} total)'
        ))
