from django.core.management.base import BaseCommand
from apps.recipes.models import Recipe

RECIPES = [
    # ── HAITI ──────────────────────────────────────────────────────────────────
    {'titre': 'Griot', 'pays': 'haiti', 'type_plat': 'salé',
     'description': "Le plat emblématique d'Haïti, des cubes de porc marinés aux agrumes puis frits jusqu'à obtenir une croûte dorée et croustillante.",
     'temps_preparation': 30, 'temps_cuisson': 90, 'nb_personnes': 4, 'difficulte': 'Moyen',
     'ingredients': ["1 kg d'épaule de porc coupée en cubes", "jus de 3 citrons verts", "jus de 2 oranges amères", "4 gousses d'ail écrasées", "1 oignon émincé", "2 piments Scotch Bonnet", "1 cuillère à soupe de thym frais", "sel et poivre", "huile pour la friture"],
     'etapes': ["Mélanger le porc avec le jus de citron, le jus d'orange, l'ail, l'oignon, le thym, le sel et le poivre, puis laisser mariner au moins 4 heures.", "Faire bouillir le porc avec sa marinade jusqu'à évaporation du liquide et attendrissement de la viande.", "Égoutter les morceaux, puis les frire dans l'huile chaude jusqu'à obtention d'une croûte dorée.", "Servir bien chaud avec du pikliz et du riz."],
     'tags': ['Porc', 'Frit', 'Port-au-Prince', 'National'], 'image_url': ''},
    {'titre': 'Pain patate', 'pays': 'haiti', 'type_plat': 'sucré',
     'description': 'Un gâteau moelleux à la patate douce et au lait de coco, parfumé à la cannelle et à la muscade, dessert incontournable des fêtes haïtiennes.',
     'temps_preparation': 25, 'temps_cuisson': 60, 'nb_personnes': 8, 'difficulte': 'Facile',
     'ingredients': ["1 kg de patate douce râpée", "2 bananes mûres écrasées", "400 ml de lait de coco", "200 g de sucre", "100 g de beurre fondu", "1 cuillère à café de cannelle", "1 cuillère à café de muscade", "1 cuillère à café d'extrait de vanille", "100 g de raisins secs"],
     'etapes': ["Préchauffer le four à 180 degrés.", "Mélanger la patate douce râpée avec les bananes, le lait de coco et le sucre.", "Ajouter le beurre fondu, les épices, la vanille et les raisins secs.", "Verser dans un moule beurré et enfourner environ 1 heure jusqu'à ce que le dessus soit doré.", "Laisser tiédir avant de découper en parts."],
     'tags': ['Patate douce', 'Dessert', 'Cannelle', 'National'], 'image_url': ''},

    # ── MOROCCO ────────────────────────────────────────────────────────────────
    {'titre': 'Tajine d\'agneau aux pruneaux', 'pays': 'morocco', 'type_plat': 'salé',
     'description': 'Un tajine sucré-salé mijoté longuement, l\'agneau fondant marié aux pruneaux, aux amandes et aux épices marocaines.',
     'temps_preparation': 30, 'temps_cuisson': 120, 'nb_personnes': 6, 'difficulte': 'Moyen',
     'ingredients': ["1,2 kg d'épaule d'agneau", "2 oignons émincés", "500 g de pruneaux dénoyautés", "100 g d'amandes émondées", "2 cuillères à café de cannelle", "1 cuillère à café de gingembre", "1 pincée de safran", "2 cuillères à soupe de miel", "huile d'olive", "sel et poivre"],
     'etapes': ["Faire revenir l'agneau avec les oignons, les épices et un filet d'huile d'olive.", "Couvrir d'eau et laisser mijoter à feu doux pendant environ 1h30.", "Ajouter les pruneaux et le miel, puis poursuivre la cuisson 30 minutes.", "Faire dorer les amandes à sec et les parsemer sur le tajine avant de servir."],
     'tags': ['Agneau', 'Sucré-salé', 'Fès', 'National'], 'image_url': ''},
    {'titre': 'Cornes de gazelle', 'pays': 'morocco', 'type_plat': 'sucré',
     'description': 'Des pâtisseries en forme de croissant, garnies d\'une pâte d\'amande parfumée à la fleur d\'oranger, fierté des tables marocaines.',
     'temps_preparation': 60, 'temps_cuisson': 15, 'nb_personnes': 10, 'difficulte': 'Difficile',
     'ingredients': ["300 g de farine", "250 g d'amandes en poudre", "200 g de sucre glace", "2 cuillères à soupe d'eau de fleur d'oranger", "1 cuillère à café de cannelle", "50 g de beurre fondu", "1 jaune d'oeuf", "eau"],
     'etapes': ["Préparer une pâte fine avec la farine, le beurre et un peu d'eau, puis laisser reposer.", "Mélanger les amandes, le sucre glace, la cannelle et la fleur d'oranger pour former la farce.", "Étaler la pâte finement, déposer des boudins de farce et former les croissants.", "Souder les bords, badigeonner de jaune d'oeuf et cuire 12 à 15 minutes à 180 degrés."],
     'tags': ['Amande', 'Pâtisserie', "Fleur d'oranger", 'Fête'], 'image_url': ''},

    # ── ARGENTINA ──────────────────────────────────────────────────────────────
    {'titre': 'Empanadas de carne', 'pays': 'argentina', 'type_plat': 'salé',
     'description': 'Des chaussons dorés farcis de bœuf haché, d\'oignons et d\'épices, le grand classique des réunions de famille argentines.',
     'temps_preparation': 40, 'temps_cuisson': 25, 'nb_personnes': 6, 'difficulte': 'Moyen',
     'ingredients': ["500 g de bœuf haché", "2 oignons émincés", "2 oeufs durs", "60 g d'olives vertes", "1 cuillère à café de cumin", "1 cuillère à café de paprika", "12 disques de pâte à empanadas", "1 oeuf battu", "sel et poivre"],
     'etapes': ["Faire revenir les oignons puis le bœuf haché avec le cumin et le paprika.", "Laisser refroidir la farce, puis ajouter les oeufs durs et les olives en morceaux.", "Garnir les disques de pâte, replier et sceller le bord en formant le repulgue.", "Badigeonner d'oeuf battu et cuire 20 à 25 minutes à 200 degrés."],
     'tags': ['Boeuf', 'Four', 'Córdoba', 'National'], 'image_url': ''},
    {'titre': 'Alfajores au dulce de leche', 'pays': 'argentina', 'type_plat': 'sucré',
     'description': 'Deux biscuits fondants réunis par une couche généreuse de dulce de leche, souvent enrobés de noix de coco.',
     'temps_preparation': 40, 'temps_cuisson': 12, 'nb_personnes': 8, 'difficulte': 'Moyen',
     'ingredients': ["200 g de maïzena", "150 g de farine", "120 g de beurre", "80 g de sucre", "2 jaunes d'oeufs", "1 cuillère à café de levure chimique", "300 g de dulce de leche", "noix de coco râpée"],
     'etapes': ["Travailler le beurre et le sucre, ajouter les jaunes puis les farines et la levure.", "Étaler la pâte et découper des disques, puis cuire 10 à 12 minutes à 170 degrés.", "Laisser refroidir les biscuits avant de les garnir de dulce de leche.", "Assembler par deux et rouler les bords dans la noix de coco râpée."],
     'tags': ['Dulce de leche', 'Biscuit', 'Buenos Aires', 'National'], 'image_url': ''},

    # ── BRAZIL ─────────────────────────────────────────────────────────────────
    {'titre': 'Feijoada', 'pays': 'brazil', 'type_plat': 'salé',
     'description': 'Le plat national brésilien, un ragoût généreux de haricots noirs et de viandes de porc mijotées, servi avec du riz et des oranges.',
     'temps_preparation': 30, 'temps_cuisson': 150, 'nb_personnes': 8, 'difficulte': 'Moyen',
     'ingredients': ["500 g de haricots noirs", "300 g de travers de porc", "200 g de saucisse fumée", "200 g de lard fumé", "2 oignons émincés", "4 gousses d'ail", "2 feuilles de laurier", "huile", "sel et poivre"],
     'etapes': ["Faire tremper les haricots noirs la veille, puis les cuire avec le laurier.", "Faire revenir les viandes avec l'oignon et l'ail.", "Réunir les viandes et les haricots, couvrir d'eau et mijoter au moins 2 heures.", "Servir avec du riz blanc, du chou sauté et des quartiers d'orange."],
     'tags': ['Porc', 'Haricots noirs', 'Rio de Janeiro', 'National'], 'image_url': ''},
    {'titre': 'Brigadeiro', 'pays': 'brazil', 'type_plat': 'sucré',
     'description': 'Des truffes au chocolat et lait concentré roulées dans des vermicelles, incontournables des anniversaires brésiliens.',
     'temps_preparation': 15, 'temps_cuisson': 15, 'nb_personnes': 6, 'difficulte': 'Facile',
     'ingredients': ["400 g de lait concentré sucré", "4 cuillères à soupe de cacao en poudre", "30 g de beurre", "vermicelles de chocolat", "1 pincée de sel"],
     'etapes': ["Mélanger le lait concentré, le cacao et le beurre dans une casserole.", "Cuire à feu doux en remuant sans cesse jusqu'à ce que la pâte se décolle du fond.", "Laisser refroidir, puis former des petites boules avec les mains beurrées.", "Rouler chaque boule dans les vermicelles de chocolat."],
     'tags': ['Chocolat', 'Confiserie', 'São Paulo', 'Fête'], 'image_url': ''},

    # ── MEXICO ─────────────────────────────────────────────────────────────────
    {'titre': 'Tacos al pastor', 'pays': 'mexico', 'type_plat': 'salé',
     'description': 'Des tacos de porc mariné au piment et à l\'ananas, héritage de la cuisine de rue de Mexico, servis sur des tortillas de maïs.',
     'temps_preparation': 40, 'temps_cuisson': 30, 'nb_personnes': 4, 'difficulte': 'Moyen',
     'ingredients': ["600 g d'échine de porc en lamelles", "3 piments guajillo", "1/2 ananas", "2 gousses d'ail", "1 cuillère à soupe d'achiote", "1 oignon", "coriandre fraîche", "12 tortillas de maïs", "sel"],
     'etapes': ["Mixer les piments réhydratés, l'ail, l'achiote et un peu d'ananas pour faire la marinade.", "Faire mariner le porc au moins 3 heures.", "Saisir la viande à feu vif jusqu'à ce qu'elle soit dorée.", "Garnir les tortillas de porc, d'ananas grillé, d'oignon et de coriandre."],
     'tags': ['Porc', 'Piment', 'Mexico', 'National'], 'image_url': ''},
    {'titre': 'Churros', 'pays': 'mexico', 'type_plat': 'sucré',
     'description': 'Des beignets allongés et cannelés frits, roulés dans le sucre à la cannelle et trempés dans le chocolat chaud.',
     'temps_preparation': 20, 'temps_cuisson': 15, 'nb_personnes': 4, 'difficulte': 'Facile',
     'ingredients': ["250 ml d'eau", "150 g de farine", "30 g de beurre", "1 pincée de sel", "1 oeuf", "sucre", "cannelle", "huile pour la friture"],
     'etapes': ["Porter l'eau, le beurre et le sel à ébullition, puis ajouter la farine hors du feu.", "Incorporer l'oeuf pour obtenir une pâte lisse.", "Pocher la pâte en bâtonnets dans l'huile chaude et frire jusqu'à coloration.", "Rouler les churros dans le sucre à la cannelle et servir avec du chocolat."],
     'tags': ['Friture', 'Cannelle', 'Dessert', 'Populaire'], 'image_url': ''},

    # ── COLOMBIA ───────────────────────────────────────────────────────────────
    {'titre': 'Bandeja paisa', 'pays': 'colombia', 'type_plat': 'salé',
     'description': "Le plateau copieux d'Antioquia réunissant haricots rouges, riz, viande hachée, chicharrón, oeuf et banane plantain.",
     'temps_preparation': 40, 'temps_cuisson': 90, 'nb_personnes': 4, 'difficulte': 'Moyen',
     'ingredients': ["300 g de haricots rouges", "200 g de bœuf haché", "200 g de poitrine de porc", "200 g de riz", "4 oeufs", "2 bananes plantains", "2 chorizos", "avocat", "sel"],
     'etapes': ["Cuire les haricots rouges jusqu'à ce qu'ils soient tendres.", "Faire frire la poitrine de porc pour obtenir le chicharrón croustillant.", "Cuire le riz, saisir le bœuf haché et les chorizos.", "Dresser tous les éléments sur une grande assiette avec un oeuf frit et l'avocat."],
     'tags': ['Haricots', 'Porc', 'Medellín', 'National'], 'image_url': ''},
    {'titre': 'Natilla colombienne', 'pays': 'colombia', 'type_plat': 'sucré',
     'description': 'Une crème épaisse à la cannelle et à la panela, dessert traditionnel de Noël en Colombie.',
     'temps_preparation': 15, 'temps_cuisson': 25, 'nb_personnes': 6, 'difficulte': 'Facile',
     'ingredients': ["1 litre de lait", "150 g de panela râpée", "80 g de maïzena", "1 bâton de cannelle", "1 pincée de sel", "raisins secs", "noix de coco râpée"],
     'etapes': ["Diluer la maïzena dans un peu de lait froid.", "Chauffer le reste du lait avec la panela et la cannelle.", "Ajouter la maïzena diluée et remuer jusqu'à épaississement.", "Verser dans un moule, laisser prendre et décorer de noix de coco."],
     'tags': ['Crème', 'Panela', 'Cannelle', 'Noël'], 'image_url': ''},

    # ── ECUADOR ────────────────────────────────────────────────────────────────
    {'titre': 'Encebollado', 'pays': 'ecuador', 'type_plat': 'salé',
     'description': 'La soupe nationale équatorienne au thon et au manioc, relevée d\'oignons marinés et de coriandre.',
     'temps_preparation': 25, 'temps_cuisson': 40, 'nb_personnes': 4, 'difficulte': 'Moyen',
     'ingredients': ["500 g de thon frais", "400 g de manioc", "2 tomates", "2 oignons rouges", "1 citron", "coriandre fraîche", "1 cuillère à café de cumin", "sel et poivre"],
     'etapes': ["Cuire le thon dans un bouillon avec la tomate et le cumin.", "Cuire le manioc séparément jusqu'à ce qu'il soit tendre.", "Mariner l'oignon rouge avec le jus de citron et le sel.", "Servir le bouillon avec le thon émietté, le manioc, l'oignon mariné et la coriandre."],
     'tags': ['Thon', 'Soupe', 'Guayaquil', 'National'], 'image_url': ''},
    {'titre': 'Espumilla', 'pays': 'ecuador', 'type_plat': 'sucré',
     'description': 'Une meringue légère à la goyave, servie en cornet comme une glace, gourmandise des rues équatoriennes.',
     'temps_preparation': 20, 'temps_cuisson': 0, 'nb_personnes': 4, 'difficulte': 'Facile',
     'ingredients': ["3 blancs d'oeufs", "200 g de pulpe de goyave", "100 g de sucre", "1 pincée de sel", "vermicelles colorés"],
     'etapes': ["Monter les blancs en neige avec une pincée de sel.", "Ajouter le sucre progressivement pour obtenir une meringue ferme.", "Incorporer délicatement la pulpe de goyave.", "Dresser en cornet et décorer de vermicelles colorés."],
     'tags': ['Meringue', 'Goyave', 'Dessert', 'Rue'], 'image_url': ''},

    # ── PERU ───────────────────────────────────────────────────────────────────
    {'titre': 'Ceviche péruvien', 'pays': 'peru', 'type_plat': 'salé',
     'description': 'Le plat emblème du Pérou, du poisson cru mariné dans le jus de citron vert, relevé d\'oignon rouge et de piment aji.',
     'temps_preparation': 25, 'temps_cuisson': 0, 'nb_personnes': 4, 'difficulte': 'Facile',
     'ingredients': ["600 g de poisson blanc très frais", "jus de 8 citrons verts", "1 oignon rouge émincé", "1 piment aji limo", "coriandre fraîche", "1 patate douce", "maïs péruvien", "sel"],
     'etapes': ["Couper le poisson en cubes réguliers.", "Arroser du jus de citron vert et laisser mariner quelques minutes.", "Ajouter l'oignon rouge, le piment et la coriandre.", "Servir aussitôt avec la patate douce et le maïs."],
     'tags': ['Poisson', 'Citron vert', 'Lima', 'National'], 'image_url': ''},
    {'titre': 'Picarones', 'pays': 'peru', 'type_plat': 'sucré',
     'description': 'Des beignets en anneau à la courge et à la patate douce, nappés d\'un sirop de chancaca parfumé.',
     'temps_preparation': 40, 'temps_cuisson': 20, 'nb_personnes': 6, 'difficulte': 'Moyen',
     'ingredients': ["300 g de courge cuite", "200 g de patate douce cuite", "350 g de farine", "1 sachet de levure boulangère", "1 cuillère à café d'anis", "chancaca pour le sirop", "huile pour la friture"],
     'etapes': ["Mixer la courge et la patate douce, puis mélanger avec la farine, la levure et l'anis.", "Laisser lever la pâte environ 1 heure.", "Former des anneaux et les frire dans l'huile chaude.", "Napper de sirop de chancaca tiède avant de servir."],
     'tags': ['Beignet', 'Courge', 'Lima', 'Dessert'], 'image_url': ''},

    # ── CHILE ──────────────────────────────────────────────────────────────────
    {'titre': 'Pastel de choclo', 'pays': 'chile', 'type_plat': 'salé',
     'description': 'Une tourte rustique au maïs doux recouvrant une garniture de bœuf, poulet, oeuf et olives, plat estival chilien.',
     'temps_preparation': 40, 'temps_cuisson': 45, 'nb_personnes': 6, 'difficulte': 'Moyen',
     'ingredients': ["6 épis de maïs doux", "400 g de bœuf haché", "2 blancs de poulet", "2 oignons", "3 oeufs durs", "olives noires", "raisins secs", "1 cuillère à café de cumin", "basilic frais"],
     'etapes': ["Mixer le maïs avec le basilic et cuire jusqu'à épaississement.", "Faire revenir l'oignon, le bœuf et le poulet avec le cumin.", "Répartir la viande, les oeufs, les olives et les raisins dans un plat.", "Recouvrir de purée de maïs, saupoudrer de sucre et gratiner au four."],
     'tags': ['Maïs', 'Bœuf', 'Santiago', 'National'], 'image_url': ''},
    {'titre': 'Mote con huesillo', 'pays': 'chile', 'type_plat': 'sucré',
     'description': 'Une boisson dessert rafraîchissante à base de pêches séchées et de blé mote, vendue partout au Chili l\'été.',
     'temps_preparation': 15, 'temps_cuisson': 40, 'nb_personnes': 4, 'difficulte': 'Facile',
     'ingredients': ["200 g de pêches séchées", "200 g de blé mote cuit", "150 g de sucre", "1 bâton de cannelle", "1 litre d'eau"],
     'etapes': ["Faire tremper les pêches séchées quelques heures.", "Les cuire dans l'eau avec le sucre et la cannelle pour faire un sirop.", "Laisser refroidir le sirop au frais.", "Servir dans un grand verre avec le blé mote et une pêche."],
     'tags': ['Pêche', 'Boisson', 'Été', 'National'], 'image_url': ''},

    # ── URUGUAY ────────────────────────────────────────────────────────────────
    {'titre': 'Chivito', 'pays': 'uruguay', 'type_plat': 'salé',
     'description': 'Le sandwich national uruguayen au bœuf, jambon, fromage, oeuf et bacon, véritable institution gourmande.',
     'temps_preparation': 25, 'temps_cuisson': 15, 'nb_personnes': 2, 'difficulte': 'Facile',
     'ingredients': ["2 fines tranches de filet de bœuf", "2 pains à burger", "2 tranches de jambon", "2 tranches de mozzarella", "2 oeufs", "4 tranches de bacon", "tomate", "laitue", "mayonnaise"],
     'etapes': ["Saisir le filet de bœuf rapidement de chaque côté.", "Faire dorer le bacon et cuire les oeufs au plat.", "Toaster les pains et les tartiner de mayonnaise.", "Empiler le bœuf, le jambon, le fromage, le bacon, l'oeuf et les crudités."],
     'tags': ['Boeuf', 'Sandwich', 'Montevideo', 'National'], 'image_url': ''},
    {'titre': 'Chajá', 'pays': 'uruguay', 'type_plat': 'sucré',
     'description': 'Un gâteau aérien de génoise, meringue, crème chantilly et pêches, dessert emblématique de la ville de Paysandú.',
     'temps_preparation': 50, 'temps_cuisson': 25, 'nb_personnes': 8, 'difficulte': 'Difficile',
     'ingredients': ["1 génoise", "300 ml de crème fouettée", "200 g de meringue émiettée", "200 g de pêches au sirop", "100 g de dulce de leche", "sirop pour imbiber"],
     'etapes': ["Couper la génoise en couches et les imbiber de sirop.", "Tartiner de dulce de leche et de crème fouettée.", "Alterner avec les pêches et les éclats de meringue.", "Recouvrir de crème et de meringue, puis réserver au frais."],
     'tags': ['Meringue', 'Crème', 'Paysandú', 'National'], 'image_url': ''},

    # ── BOLIVIA ────────────────────────────────────────────────────────────────
    {'titre': 'Salteñas', 'pays': 'bolivia', 'type_plat': 'salé',
     'description': 'Des chaussons boliviens à la pâte légèrement sucrée, garnis d\'un ragoût juteux de viande, pomme de terre et oeuf.',
     'temps_preparation': 50, 'temps_cuisson': 25, 'nb_personnes': 6, 'difficulte': 'Difficile',
     'ingredients': ["400 g de bœuf en dés", "2 pommes de terre", "2 oeufs durs", "1 oignon", "olives", "1 cuillère à soupe de paprika", "gélatine", "12 disques de pâte", "sel"],
     'etapes': ["Cuire la viande avec l'oignon, le paprika et la gélatine pour un ragoût gélifié.", "Laisser prendre au froid pour obtenir une garniture juteuse.", "Garnir les disques de pâte, ajouter oeuf et olive, puis sceller en repulgue.", "Cuire 20 à 25 minutes à four chaud jusqu'à ce que la pâte soit dorée."],
     'tags': ['Boeuf', 'Four', 'La Paz', 'National'], 'image_url': ''},
    {'titre': 'Cuñapé', 'pays': 'bolivia', 'type_plat': 'sucré',
     'description': 'De petits pains moelleux au fromage et à la fécule de manioc, spécialité de la région de Santa Cruz.',
     'temps_preparation': 20, 'temps_cuisson': 20, 'nb_personnes': 6, 'difficulte': 'Facile',
     'ingredients': ["300 g de fécule de manioc", "250 g de fromage frais râpé", "1 oeuf", "50 g de beurre", "60 ml de lait", "1 pincée de sel"],
     'etapes': ["Mélanger la fécule, le fromage et le sel.", "Ajouter l'oeuf, le beurre et le lait pour former une pâte souple.", "Façonner des petites boules.", "Cuire 18 à 20 minutes à 200 degrés jusqu'à ce qu'ils soient dorés."],
     'tags': ['Fromage', 'Manioc', 'Santa Cruz', 'Goûter'], 'image_url': ''},

    # ── PARAGUAY ───────────────────────────────────────────────────────────────
    {'titre': 'Sopa paraguaya', 'pays': 'paraguay', 'type_plat': 'salé',
     'description': 'Malgré son nom, un pain de maïs salé au fromage et à l\'oignon, plat patrimonial du Paraguay.',
     'temps_preparation': 25, 'temps_cuisson': 45, 'nb_personnes': 8, 'difficulte': 'Moyen',
     'ingredients': ["300 g de farine de maïs", "250 g de fromage frais", "2 oignons", "4 oeufs", "250 ml de lait", "100 g de beurre", "sel"],
     'etapes': ["Faire suer les oignons dans le beurre.", "Mélanger la farine de maïs, le fromage, le lait et les oeufs.", "Incorporer les oignons et verser dans un moule beurré.", "Cuire environ 45 minutes à 180 degrés jusqu'à coloration."],
     'tags': ['Maïs', 'Fromage', 'Asunción', 'National'], 'image_url': ''},
    {'titre': 'Dulce de mamón', 'pays': 'paraguay', 'type_plat': 'sucré',
     'description': 'Une confiture de papaye verte confite dans un sirop parfumé, douceur traditionnelle paraguayenne.',
     'temps_preparation': 30, 'temps_cuisson': 120, 'nb_personnes': 8, 'difficulte': 'Moyen',
     'ingredients': ["1 kg de papaye verte", "800 g de sucre", "1 bâton de cannelle", "quelques clous de girofle", "1 litre d'eau", "jus d'un citron"],
     'etapes': ["Éplucher la papaye et la couper en morceaux.", "Préparer un sirop avec l'eau, le sucre et les épices.", "Plonger la papaye et cuire à feu doux jusqu'à ce qu'elle devienne translucide.", "Ajouter le jus de citron en fin de cuisson et laisser confire."],
     'tags': ['Papaye', 'Confiture', 'Cannelle', 'Tradition'], 'image_url': ''},

    # ── JAPAN ──────────────────────────────────────────────────────────────────
    {'titre': 'Ramen shoyu', 'pays': 'japan', 'type_plat': 'salé',
     'description': 'Un bol de nouilles dans un bouillon à la sauce soja, garni de porc chashu, d\'oeuf mollet et d\'oignons verts.',
     'temps_preparation': 30, 'temps_cuisson': 60, 'nb_personnes': 2, 'difficulte': 'Moyen',
     'ingredients': ["200 g de nouilles ramen", "1 litre de bouillon de volaille", "4 cuillères à soupe de sauce soja", "200 g de poitrine de porc", "2 oeufs mollets", "2 oignons verts", "nori", "huile de sésame"],
     'etapes': ["Braiser le porc lentement jusqu'à ce qu'il soit fondant.", "Parfumer le bouillon chaud avec la sauce soja et l'huile de sésame.", "Cuire les nouilles puis les disposer dans les bols.", "Verser le bouillon et garnir de porc, d'oeuf, d'oignons verts et de nori."],
     'tags': ['Nouilles', 'Porc', 'Tokyo', 'Populaire'], 'image_url': ''},
    {'titre': 'Dorayaki', 'pays': 'japan', 'type_plat': 'sucré',
     'description': 'Deux pancakes moelleux garnis de pâte de haricots rouges sucrée, douceur japonaise très appréciée.',
     'temps_preparation': 20, 'temps_cuisson': 15, 'nb_personnes': 4, 'difficulte': 'Facile',
     'ingredients': ["2 oeufs", "100 g de sucre", "1 cuillère à soupe de miel", "120 g de farine", "1/2 sachet de levure", "200 g de pâte de haricots rouges anko"],
     'etapes': ["Battre les oeufs avec le sucre et le miel.", "Incorporer la farine et la levure pour obtenir une pâte lisse.", "Cuire de petits pancakes à la poêle de chaque côté.", "Garnir une face de anko et refermer avec un second pancake."],
     'tags': ['Pancake', 'Anko', 'Goûter', 'Tradition'], 'image_url': ''},

    # ── SOUTH KOREA ────────────────────────────────────────────────────────────
    {'titre': 'Bibimbap', 'pays': 'south korea', 'type_plat': 'salé',
     'description': 'Un bol de riz coréen surmonté de légumes assortis, de bœuf mariné, d\'un oeuf et de pâte pimentée gochujang.',
     'temps_preparation': 35, 'temps_cuisson': 20, 'nb_personnes': 2, 'difficulte': 'Moyen',
     'ingredients': ["200 g de riz", "200 g de bœuf émincé", "1 carotte", "100 g d'épinards", "100 g de germes de soja", "1 courgette", "2 oeufs", "2 cuillères à soupe de gochujang", "huile de sésame"],
     'etapes': ["Mariner le bœuf dans la sauce soja et l'huile de sésame puis le saisir.", "Cuire séparément chaque légume et les assaisonner.", "Disposer le riz dans un bol et répartir les garnitures par dessus.", "Ajouter un oeuf au plat et le gochujang, puis mélanger avant de déguster."],
     'tags': ['Riz', 'Boeuf', 'Séoul', 'National'], 'image_url': ''},
    {'titre': 'Hotteok', 'pays': 'south korea', 'type_plat': 'sucré',
     'description': 'Des galettes briochées frites garnies d\'un coeur fondant de sucre brun, cannelle et cacahuètes, en-cas d\'hiver coréen.',
     'temps_preparation': 30, 'temps_cuisson': 15, 'nb_personnes': 4, 'difficulte': 'Moyen',
     'ingredients': ["300 g de farine", "1 sachet de levure boulangère", "180 ml de lait tiède", "100 g de cassonade", "1 cuillère à café de cannelle", "50 g de cacahuètes concassées", "huile"],
     'etapes': ["Préparer une pâte levée avec la farine, la levure et le lait, puis laisser reposer 1 heure.", "Mélanger la cassonade, la cannelle et les cacahuètes pour la garniture.", "Garnir des boules de pâte et les aplatir à la poêle huilée.", "Cuire de chaque côté jusqu'à ce qu'elles soient dorées et fondantes."],
     'tags': ['Galette', 'Cannelle', 'Séoul', 'Rue'], 'image_url': ''},

    # ── IRAN ───────────────────────────────────────────────────────────────────
    {'titre': 'Ghormeh sabzi', 'pays': 'iran', 'type_plat': 'salé',
     'description': 'Un ragoût iranien d\'herbes fraîches, de haricots rouges et d\'agneau, relevé de citron noir séché.',
     'temps_preparation': 30, 'temps_cuisson': 120, 'nb_personnes': 4, 'difficulte': 'Moyen',
     'ingredients': ["500 g d'agneau en dés", "1 bouquet de persil", "1 bouquet de coriandre", "100 g de feuilles de fenugrec", "200 g de haricots rouges", "2 citrons noirs séchés", "1 oignon", "curcuma", "sel"],
     'etapes': ["Faire revenir l'oignon et l'agneau avec le curcuma.", "Hacher et faire revenir les herbes jusqu'à ce qu'elles foncent.", "Réunir viande, herbes, haricots et citrons noirs, couvrir d'eau et mijoter 2 heures.", "Servir avec du riz basmati."],
     'tags': ['Agneau', 'Herbes', 'Téhéran', 'National'], 'image_url': ''},
    {'titre': 'Sholeh zard', 'pays': 'iran', 'type_plat': 'sucré',
     'description': 'Un riz au lait safrané parfumé à l\'eau de rose et à la cardamome, dessert iranien des grandes occasions.',
     'temps_preparation': 20, 'temps_cuisson': 60, 'nb_personnes': 6, 'difficulte': 'Moyen',
     'ingredients': ["200 g de riz", "200 g de sucre", "1 pincée de safran", "2 cuillères à soupe d'eau de rose", "1/2 cuillère à café de cardamome", "50 g d'amandes effilées", "pistaches et cannelle"],
     'etapes': ["Cuire le riz dans beaucoup d'eau jusqu'à ce qu'il soit très tendre.", "Ajouter le sucre, le safran infusé et la cardamome.", "Poursuivre la cuisson à feu doux jusqu'à une consistance crémeuse.", "Parfumer à l'eau de rose et décorer de cannelle et de pistaches."],
     'tags': ['Riz', 'Safran', "Eau de rose", 'Fête'], 'image_url': ''},

    # ── SAUDI ARABIA ───────────────────────────────────────────────────────────
    {'titre': 'Kabsa', 'pays': 'saudi arabia', 'type_plat': 'salé',
     'description': 'Le plat national saoudien, un riz épicé parfumé au loomi et à la cardamome, servi avec du poulet ou de l\'agneau.',
     'temps_preparation': 30, 'temps_cuisson': 75, 'nb_personnes': 6, 'difficulte': 'Moyen',
     'ingredients': ["1 poulet en morceaux", "500 g de riz basmati", "2 oignons", "3 tomates", "2 citrons noirs loomi", "1 cuillère à soupe de bahrat", "cardamome et clous de girofle", "sel"],
     'etapes': ["Faire revenir l'oignon et saisir le poulet avec les épices.", "Ajouter les tomates et les citrons noirs, couvrir d'eau et laisser mijoter.", "Retirer le poulet et cuire le riz dans le bouillon parfumé.", "Remettre le poulet sur le riz pour servir."],
     'tags': ['Poulet', 'Riz', 'Riyad', 'National'], 'image_url': ''},
    {'titre': 'Luqaimat', 'pays': 'saudi arabia', 'type_plat': 'sucré',
     'description': 'De petits beignets croustillants nappés de sirop de dattes, douceur appréciée pendant le Ramadan.',
     'temps_preparation': 25, 'temps_cuisson': 15, 'nb_personnes': 6, 'difficulte': 'Facile',
     'ingredients': ["250 g de farine", "1 sachet de levure boulangère", "1 cuillère à soupe de yaourt", "200 ml d'eau tiède", "sirop de dattes", "1 pincée de cardamome", "graines de sésame", "huile pour la friture"],
     'etapes': ["Préparer une pâte fluide et laisser lever environ 1 heure.", "Former des petites boules à l'aide de deux cuillères.", "Frire jusqu'à obtention d'une couleur dorée et croustillante.", "Napper de sirop de dattes et parsemer de sésame."],
     'tags': ['Beignet', 'Dattes', 'Ramadan', 'Tradition'], 'image_url': ''},

    # ── AUSTRALIA ──────────────────────────────────────────────────────────────
    {'titre': 'Meat pie', 'pays': 'australia', 'type_plat': 'salé',
     'description': 'La tourte individuelle au bœuf en sauce, en-cas emblématique consommé dans tout le pays.',
     'temps_preparation': 30, 'temps_cuisson': 50, 'nb_personnes': 4, 'difficulte': 'Moyen',
     'ingredients': ["500 g de bœuf haché", "1 oignon", "2 cuillères à soupe de farine", "300 ml de bouillon de bœuf", "1 cuillère à soupe de sauce Worcestershire", "pâte brisée", "pâte feuilletée", "1 oeuf"],
     'etapes': ["Faire revenir l'oignon et le bœuf haché.", "Saupoudrer de farine, mouiller au bouillon et laisser épaissir avec la sauce Worcestershire.", "Garnir des moules de pâte brisée avec la viande refroidie.", "Recouvrir de pâte feuilletée, dorer à l'oeuf et cuire 25 minutes à 200 degrés."],
     'tags': ['Boeuf', 'Tourte', 'Sydney', 'Populaire'], 'image_url': ''},
    {'titre': 'Lamington', 'pays': 'australia', 'type_plat': 'sucré',
     'description': 'Des cubes de génoise enrobés de glaçage au chocolat et roulés dans la noix de coco, gâteau iconique australien.',
     'temps_preparation': 30, 'temps_cuisson': 25, 'nb_personnes': 8, 'difficulte': 'Moyen',
     'ingredients': ["1 génoise nature", "200 g de sucre glace", "3 cuillères à soupe de cacao", "150 ml de lait", "20 g de beurre", "200 g de noix de coco râpée"],
     'etapes': ["Couper la génoise en cubes réguliers.", "Préparer un glaçage avec le sucre glace, le cacao, le lait et le beurre.", "Tremper chaque cube dans le glaçage.", "Rouler aussitôt dans la noix de coco et laisser sécher."],
     'tags': ['Chocolat', 'Noix de coco', 'Queensland', 'National'], 'image_url': ''},

    # ── GHANA ──────────────────────────────────────────────────────────────────
    {'titre': 'Jollof rice', 'pays': 'ghana', 'type_plat': 'salé',
     'description': 'Un riz mijoté dans une sauce tomate épicée, plat de fête partagé et célébré en Afrique de l\'Ouest.',
     'temps_preparation': 25, 'temps_cuisson': 50, 'nb_personnes': 6, 'difficulte': 'Moyen',
     'ingredients': ["500 g de riz", "4 tomates", "2 poivrons rouges", "1 oignon", "2 cuillères à soupe de concentré de tomate", "1 piment scotch bonnet", "1 cuillère à café de gingembre", "huile", "bouillon"],
     'etapes': ["Mixer les tomates, les poivrons, l'oignon et le piment.", "Faire réduire ce coulis dans l'huile avec le concentré de tomate.", "Ajouter le riz et le bouillon, puis couvrir.", "Laisser cuire à feu doux jusqu'à absorption complète du liquide."],
     'tags': ['Riz', 'Tomate', 'Accra', 'National'], 'image_url': ''},
    {'titre': 'Bofrot', 'pays': 'ghana', 'type_plat': 'sucré',
     'description': 'Des beignets ronds et moelleux légèrement parfumés à la muscade, en-cas de rue très populaire au Ghana.',
     'temps_preparation': 20, 'temps_cuisson': 20, 'nb_personnes': 6, 'difficulte': 'Facile',
     'ingredients': ["300 g de farine", "100 g de sucre", "1 sachet de levure boulangère", "1/2 cuillère à café de muscade", "200 ml d'eau tiède", "1 pincée de sel", "huile pour la friture"],
     'etapes': ["Mélanger la farine, le sucre, la levure, la muscade et le sel.", "Ajouter l'eau pour former une pâte épaisse et laisser lever 1 heure.", "Prélever des boules de pâte à la main.", "Frire dans l'huile chaude jusqu'à coloration dorée."],
     'tags': ['Beignet', 'Muscade', 'Accra', 'Rue'], 'image_url': ''},

    # ── NIGERIA ────────────────────────────────────────────────────────────────
    {'titre': 'Egusi soup', 'pays': 'nigeria', 'type_plat': 'salé',
     'description': 'Un ragoût épais aux graines de melon moulues, légumes verts et viandes, grand classique de la cuisine nigériane.',
     'temps_preparation': 30, 'temps_cuisson': 60, 'nb_personnes': 6, 'difficulte': 'Moyen',
     'ingredients': ["200 g de graines d'egusi moulues", "400 g de bœuf", "200 g d'épinards", "2 cuillères à soupe de crevettes séchées", "1 oignon", "2 cuillères à soupe d'huile de palme", "1 piment", "bouillon", "sel"],
     'etapes': ["Cuire la viande dans un bouillon assaisonné.", "Chauffer l'huile de palme et y ajouter l'oignon et l'egusi.", "Incorporer le bouillon, les crevettes et le piment, puis laisser mijoter.", "Ajouter les épinards en fin de cuisson et servir avec du fufu."],
     'tags': ['Egusi', 'Boeuf', 'Lagos', 'National'], 'image_url': ''},
    {'titre': 'Puff puff', 'pays': 'nigeria', 'type_plat': 'sucré',
     'description': 'Des beignets ronds et aériens, dorés et sucrés, incontournables des fêtes et des marchés nigérians.',
     'temps_preparation': 20, 'temps_cuisson': 20, 'nb_personnes': 6, 'difficulte': 'Facile',
     'ingredients': ["300 g de farine", "80 g de sucre", "1 sachet de levure boulangère", "1/4 de cuillère à café de muscade", "200 ml d'eau tiède", "1 pincée de sel", "huile pour la friture"],
     'etapes': ["Mélanger la farine, le sucre, la levure, la muscade et le sel.", "Ajouter l'eau pour obtenir une pâte fluide et laisser lever 1 heure.", "Façonner des boules à la main et les plonger dans l'huile chaude.", "Frire jusqu'à ce qu'elles soient bien dorées."],
     'tags': ['Beignet', 'Sucre', 'Lagos', 'Fête'], 'image_url': ''},

    # ── SENEGAL ────────────────────────────────────────────────────────────────
    {'titre': 'Thiéboudienne', 'pays': 'senegal', 'type_plat': 'salé',
     'description': 'Le plat national sénégalais, du riz cuit dans une sauce tomate avec du poisson et des légumes farcis au persil.',
     'temps_preparation': 40, 'temps_cuisson': 90, 'nb_personnes': 6, 'difficulte': 'Difficile',
     'ingredients': ["1 kg de poisson", "500 g de riz brisé", "4 tomates", "2 cuillères à soupe de concentré de tomate", "1 chou", "2 carottes", "1 manioc", "1 aubergine", "persil et ail", "huile"],
     'etapes': ["Farcir le poisson d'un hachis de persil, ail et piment.", "Faire revenir le poisson puis préparer une sauce avec tomate et concentré.", "Cuire les légumes dans la sauce, puis les réserver.", "Cuire le riz dans le bouillon parfumé et dresser avec le poisson et les légumes."],
     'tags': ['Poisson', 'Riz', 'Dakar', 'National'], 'image_url': ''},
    {'titre': 'Thiakry', 'pays': 'senegal', 'type_plat': 'sucré',
     'description': 'Un dessert frais à base de semoule de mil et de lait caillé sucré, parfumé à la vanille et à la fleur d\'oranger.',
     'temps_preparation': 20, 'temps_cuisson': 15, 'nb_personnes': 4, 'difficulte': 'Facile',
     'ingredients': ["250 g de semoule de mil", "500 ml de lait caillé", "100 g de sucre", "1 cuillère à café de vanille", "1 cuillère à soupe de fleur d'oranger", "raisins secs"],
     'etapes': ["Cuire la semoule de mil à la vapeur jusqu'à ce qu'elle soit tendre.", "Laisser refroidir la semoule.", "Mélanger le lait caillé avec le sucre, la vanille et la fleur d'oranger.", "Incorporer la semoule et les raisins, puis servir frais."],
     'tags': ['Mil', 'Lait caillé', 'Dakar', 'Dessert'], 'image_url': ''},

    # ── CAMEROON ───────────────────────────────────────────────────────────────
    {'titre': 'Ndolé', 'pays': 'cameroon', 'type_plat': 'salé',
     'description': 'Le plat national camerounais, un ragoût de feuilles de ndolé amer adoucies, d\'arachides, de viande et de crevettes.',
     'temps_preparation': 40, 'temps_cuisson': 75, 'nb_personnes': 6, 'difficulte': 'Difficile',
     'ingredients': ["500 g de feuilles de ndolé", "200 g d'arachides moulues", "400 g de bœuf", "200 g de crevettes", "2 oignons", "ail et gingembre", "1 cube de bouillon", "huile", "sel"],
     'etapes': ["Blanchir les feuilles de ndolé pour réduire leur amertume.", "Cuire la viande puis préparer une sauce à base d'arachides moulues.", "Ajouter les feuilles, les crevettes et l'assaisonnement.", "Laisser mijoter jusqu'à ce que la sauce épaississe et servir avec des plantains."],
     'tags': ['Arachide', 'Boeuf', 'Douala', 'National'], 'image_url': ''},
    {'titre': 'Beignets soufflés', 'pays': 'cameroon', 'type_plat': 'sucré',
     'description': 'Des beignets levés moelleux et légèrement sucrés, souvent servis au petit-déjeuner avec une bouillie de haricots.',
     'temps_preparation': 20, 'temps_cuisson': 20, 'nb_personnes': 6, 'difficulte': 'Facile',
     'ingredients': ["300 g de farine", "70 g de sucre", "1 sachet de levure boulangère", "200 ml d'eau tiède", "1 pincée de sel", "1 pincée de muscade", "huile pour la friture"],
     'etapes': ["Mélanger la farine, le sucre, la levure, le sel et la muscade.", "Ajouter l'eau pour former une pâte souple et laisser lever 1 heure.", "Prélever des boules de pâte à la main.", "Frire dans l'huile chaude jusqu'à coloration dorée."],
     'tags': ['Beignet', 'Sucre', 'Douala', 'Petit-déjeuner'], 'image_url': ''},

    # ── EGYPT ──────────────────────────────────────────────────────────────────
    {'titre': 'Koshari', 'pays': 'egypt', 'type_plat': 'salé',
     'description': 'Le plat de rue le plus populaire d\'Égypte, mélange de riz, lentilles, pâtes et pois chiches couvert d\'une sauce tomate épicée.',
     'temps_preparation': 30, 'temps_cuisson': 45, 'nb_personnes': 4, 'difficulte': 'Moyen',
     'ingredients': ["150 g de riz", "150 g de lentilles brunes", "100 g de macaronis", "150 g de pois chiches cuits", "3 tomates", "2 oignons", "1 cuillère à soupe de vinaigre", "ail et cumin", "huile"],
     'etapes': ["Cuire séparément le riz, les lentilles et les pâtes.", "Frire les oignons émincés jusqu'à ce qu'ils soient croustillants.", "Préparer une sauce tomate relevée à l'ail et au cumin.", "Dresser le riz, les lentilles, les pâtes et les pois chiches, puis napper de sauce et d'oignons frits."],
     'tags': ['Lentilles', 'Riz', 'Le Caire', 'National'], 'image_url': ''},
    {'titre': 'Basbousa', 'pays': 'egypt', 'type_plat': 'sucré',
     'description': 'Un gâteau de semoule imbibé de sirop parfumé, moelleux et fondant, dessert phare de la pâtisserie égyptienne.',
     'temps_preparation': 20, 'temps_cuisson': 35, 'nb_personnes': 8, 'difficulte': 'Facile',
     'ingredients': ["300 g de semoule fine", "150 g de sucre", "200 g de yaourt", "100 g de beurre fondu", "1 sachet de levure", "amandes", "sirop de sucre à la fleur d'oranger"],
     'etapes': ["Mélanger la semoule, le sucre, le yaourt, le beurre et la levure.", "Verser dans un moule et marquer des losanges.", "Cuire 30 à 35 minutes à 180 degrés jusqu'à coloration dorée.", "Arroser de sirop tiède dès la sortie du four."],
     'tags': ['Semoule', 'Sirop', 'Le Caire', 'Tradition'], 'image_url': ''},

    # ── SOUTH AFRICA ───────────────────────────────────────────────────────────
    {'titre': 'Bobotie', 'pays': 'south africa', 'type_plat': 'salé',
     'description': 'Le plat national sud-africain, un gratin de viande hachée épicée et légèrement sucrée recouvert d\'un flan doré.',
     'temps_preparation': 30, 'temps_cuisson': 50, 'nb_personnes': 6, 'difficulte': 'Moyen',
     'ingredients': ["700 g de bœuf haché", "2 oignons", "1 tranche de pain trempé dans le lait", "2 cuillères à soupe de curry", "50 g d'abricots secs", "2 cuillères à soupe de chutney", "3 oeufs", "200 ml de lait", "feuilles de laurier"],
     'etapes': ["Faire revenir l'oignon, ajouter la viande, le curry, le pain trempé, les abricots et le chutney.", "Verser la préparation dans un plat et lisser.", "Battre les oeufs avec le lait et verser sur la viande.", "Piquer de feuilles de laurier et cuire 30 minutes à 180 degrés."],
     'tags': ['Boeuf', 'Curry', 'Le Cap', 'National'], 'image_url': ''},
    {'titre': 'Malva pudding', 'pays': 'south africa', 'type_plat': 'sucré',
     'description': 'Un gâteau spongieux à l\'abricot nappé d\'une sauce crémeuse chaude, dessert réconfortant sud-africain.',
     'temps_preparation': 20, 'temps_cuisson': 40, 'nb_personnes': 8, 'difficulte': 'Facile',
     'ingredients': ["200 g de farine", "200 g de sucre", "2 oeufs", "1 cuillère à soupe de confiture d'abricot", "1 cuillère à soupe de vinaigre", "250 ml de lait", "200 ml de crème", "100 g de beurre"],
     'etapes': ["Battre les oeufs et le sucre, ajouter la confiture, le vinaigre et le lait.", "Incorporer la farine et verser dans un plat.", "Cuire environ 35 minutes à 180 degrés.", "Chauffer la crème et le beurre, puis verser sur le gâteau encore chaud."],
     'tags': ['Abricot', 'Gâteau', 'Le Cap', 'Dessert'], 'image_url': ''},

    # ── ALGERIA ────────────────────────────────────────────────────────────────
    {'titre': 'Couscous algérien', 'pays': 'algeria', 'type_plat': 'salé',
     'description': 'Le couscous traditionnel à la viande et aux légumes mijotés dans un bouillon parfumé, plat de partage par excellence.',
     'temps_preparation': 40, 'temps_cuisson': 90, 'nb_personnes': 6, 'difficulte': 'Moyen',
     'ingredients': ["500 g de semoule", "600 g d'agneau", "2 courgettes", "2 carottes", "1 navet", "200 g de pois chiches", "2 tomates", "1 oignon", "ras el hanout", "huile d'olive"],
     'etapes': ["Faire revenir l'agneau avec l'oignon, la tomate et les épices.", "Couvrir d'eau, ajouter les pois chiches et laisser mijoter.", "Cuire la semoule à la vapeur en plusieurs fois.", "Ajouter les légumes au bouillon, puis dresser la semoule, la viande et les légumes."],
     'tags': ['Agneau', 'Semoule', 'Alger', 'National'], 'image_url': ''},
    {'titre': 'Makroud', 'pays': 'algeria', 'type_plat': 'sucré',
     'description': 'Des losanges de semoule farcis à la pâte de dattes, frits puis trempés dans le miel, douceur emblématique du Maghreb.',
     'temps_preparation': 45, 'temps_cuisson': 20, 'nb_personnes': 8, 'difficulte': 'Moyen',
     'ingredients': ["400 g de semoule moyenne", "250 g de pâte de dattes", "100 g de beurre fondu", "1 cuillère à café de cannelle", "eau de fleur d'oranger", "miel", "huile pour la friture"],
     'etapes': ["Travailler la semoule avec le beurre et un peu d'eau de fleur d'oranger.", "Étaler la pâte, déposer un boudin de dattes et refermer.", "Couper en losanges puis frire jusqu'à coloration dorée.", "Tremper aussitôt dans le miel tiède."],
     'tags': ['Semoule', 'Dattes', 'Constantine', 'Fête'], 'image_url': ''},

    # ── MALI ───────────────────────────────────────────────────────────────────
    {'titre': 'Mafé', 'pays': 'mali', 'type_plat': 'salé',
     'description': 'Un ragoût onctueux à la pâte d\'arachide et à la viande, mijoté avec des légumes, grand classique malien.',
     'temps_preparation': 30, 'temps_cuisson': 75, 'nb_personnes': 6, 'difficulte': 'Moyen',
     'ingredients': ["600 g de bœuf", "150 g de pâte d'arachide", "2 tomates", "1 oignon", "1 patate douce", "2 carottes", "1 cube de bouillon", "ail", "huile", "sel"],
     'etapes': ["Faire revenir la viande avec l'oignon et l'ail.", "Ajouter la tomate puis délayer la pâte d'arachide avec de l'eau.", "Incorporer les légumes et laisser mijoter doucement.", "Cuire jusqu'à ce que la sauce épaississe et servir avec du riz."],
     'tags': ['Arachide', 'Boeuf', 'Bamako', 'National'], 'image_url': ''},
    {'titre': 'Dégué', 'pays': 'mali', 'type_plat': 'sucré',
     'description': 'Un dessert frais de perles de mil cuites mélangées à un lait fermenté sucré et parfumé, très apprécié au Sahel.',
     'temps_preparation': 20, 'temps_cuisson': 15, 'nb_personnes': 4, 'difficulte': 'Facile',
     'ingredients': ["250 g de perles de mil", "500 ml de lait fermenté", "80 g de sucre", "1 cuillère à café de vanille", "1 pincée de muscade"],
     'etapes': ["Cuire les perles de mil à la vapeur jusqu'à ce qu'elles soient tendres.", "Laisser refroidir complètement.", "Mélanger le lait fermenté avec le sucre, la vanille et la muscade.", "Incorporer les perles de mil et servir bien frais."],
     'tags': ['Mil', 'Lait fermenté', 'Bamako', 'Dessert'], 'image_url': ''},

    # ── DR CONGO ───────────────────────────────────────────────────────────────
    {'titre': 'Poulet à la moambe', 'pays': 'dr congo', 'type_plat': 'salé',
     'description': 'Le plat national congolais, du poulet mijoté dans une sauce onctueuse à la pulpe de noix de palme.',
     'temps_preparation': 25, 'temps_cuisson': 60, 'nb_personnes': 4, 'difficulte': 'Moyen',
     'ingredients': ["1 poulet en morceaux", "400 g de pulpe de noix de palme moambe", "2 tomates", "1 oignon", "1 piment", "ail", "1 cube de bouillon", "huile", "sel"],
     'etapes': ["Faire revenir le poulet avec l'oignon et l'ail.", "Ajouter la tomate puis la pulpe de moambe.", "Mouiller avec un peu d'eau, ajouter le piment et l'assaisonnement.", "Laisser mijoter jusqu'à ce que la sauce nappe et servir avec du riz ou du fufu."],
     'tags': ['Poulet', 'Moambe', 'Kinshasa', 'National'], 'image_url': ''},
    {'titre': 'Mikate', 'pays': 'dr congo', 'type_plat': 'sucré',
     'description': 'Des beignets ronds et moelleux légèrement sucrés, en-cas très répandu dans les rues congolaises.',
     'temps_preparation': 20, 'temps_cuisson': 20, 'nb_personnes': 6, 'difficulte': 'Facile',
     'ingredients': ["300 g de farine", "80 g de sucre", "1 sachet de levure boulangère", "1 banane mûre écrasée", "200 ml d'eau tiède", "1 pincée de sel", "huile pour la friture"],
     'etapes': ["Mélanger la farine, le sucre, la levure et le sel.", "Ajouter la banane et l'eau pour former une pâte épaisse, puis laisser lever.", "Prélever des boules de pâte à la main.", "Frire dans l'huile chaude jusqu'à ce qu'elles soient dorées."],
     'tags': ['Beignet', 'Banane', 'Kinshasa', 'Rue'], 'image_url': ''},

    # ── CROATIA ────────────────────────────────────────────────────────────────
    {'titre': 'Pašticada', 'pays': 'croatia', 'type_plat': 'salé',
     'description': 'Un bœuf braisé dalmate longuement mijoté dans une sauce au vin et aux pruneaux, servi avec des gnocchis.',
     'temps_preparation': 40, 'temps_cuisson': 180, 'nb_personnes': 6, 'difficulte': 'Difficile',
     'ingredients': ["1,2 kg de gîte de bœuf", "200 g de pruneaux", "2 carottes", "2 oignons", "250 ml de vin rouge", "2 cuillères à soupe de concentré de tomate", "clous de girofle", "lard", "huile"],
     'etapes': ["Larder et faire mariner le bœuf la veille dans le vin et les aromates.", "Saisir la viande puis la braiser avec les légumes et le concentré de tomate.", "Ajouter les pruneaux et laisser mijoter au moins 3 heures.", "Mixer la sauce et servir avec des gnocchis."],
     'tags': ['Boeuf', 'Vin', 'Dalmatie', 'National'], 'image_url': ''},
    {'titre': 'Kremšnita', 'pays': 'croatia', 'type_plat': 'sucré',
     'description': 'Un mille-feuille à la crème vanillée onctueuse pris entre deux feuilles de pâte feuilletée, fierté de Samobor.',
     'temps_preparation': 40, 'temps_cuisson': 25, 'nb_personnes': 8, 'difficulte': 'Moyen',
     'ingredients': ["2 plaques de pâte feuilletée", "1 litre de lait", "6 jaunes d'oeufs", "150 g de sucre", "80 g de maïzena", "1 gousse de vanille", "200 ml de crème fouettée", "sucre glace"],
     'etapes': ["Cuire les deux plaques de pâte feuilletée à blanc.", "Préparer une crème pâtissière à la vanille bien épaisse.", "Incorporer la crème fouettée à la crème refroidie.", "Garnir entre les deux feuilletages et saupoudrer de sucre glace."],
     'tags': ['Crème', 'Feuilletage', 'Samobor', 'Pâtisserie'], 'image_url': ''},

    # ── SLOVAKIA ───────────────────────────────────────────────────────────────
    {'titre': 'Bryndzové halušky', 'pays': 'slovakia', 'type_plat': 'salé',
     'description': 'Le plat national slovaque, des gnocchis de pomme de terre nappés de fromage de brebis bryndza et de lardons.',
     'temps_preparation': 30, 'temps_cuisson': 20, 'nb_personnes': 4, 'difficulte': 'Moyen',
     'ingredients': ["800 g de pommes de terre râpées", "250 g de farine", "1 oeuf", "200 g de fromage bryndza", "150 g de lardons", "ciboulette", "sel"],
     'etapes': ["Mélanger les pommes de terre râpées, la farine, l'oeuf et le sel.", "Former des petits gnocchis et les pocher dans l'eau bouillante.", "Faire dorer les lardons à la poêle.", "Mélanger les gnocchis égouttés avec le bryndza et parsemer de lardons."],
     'tags': ['Pomme de terre', 'Brebis', 'Bratislava', 'National'], 'image_url': ''},
    {'titre': 'Šúľance au pavot', 'pays': 'slovakia', 'type_plat': 'sucré',
     'description': 'De petits rouleaux de pâte de pomme de terre roulés dans le pavot moulu et le sucre, dessert traditionnel slovaque.',
     'temps_preparation': 30, 'temps_cuisson': 15, 'nb_personnes': 4, 'difficulte': 'Moyen',
     'ingredients': ["500 g de pommes de terre", "200 g de farine", "1 oeuf", "100 g de graines de pavot moulues", "80 g de sucre", "50 g de beurre fondu", "1 pincée de sel"],
     'etapes': ["Cuire les pommes de terre, les écraser et mélanger avec la farine et l'oeuf.", "Former de petits boudins et les pocher dans l'eau bouillante.", "Égoutter et arroser de beurre fondu.", "Rouler dans le mélange de pavot moulu et de sucre."],
     'tags': ['Pomme de terre', 'Pavot', 'Bratislava', 'Dessert'], 'image_url': ''},

    # ── IVORY COAST ────────────────────────────────────────────────────────────
    {'titre': 'Kedjenou de poulet', 'pays': 'ivory coast', 'type_plat': 'salé',
     'description': 'Un poulet mijoté à l\'étouffée avec des légumes et des épices, plat ivoirien traditionnellement cuit en cocotte fermée.',
     'temps_preparation': 25, 'temps_cuisson': 70, 'nb_personnes': 4, 'difficulte': 'Moyen',
     'ingredients': ["1 poulet en morceaux", "3 tomates", "2 oignons", "1 aubergine", "1 piment", "gingembre et ail", "1 feuille de laurier", "1 cube de bouillon", "huile", "sel"],
     'etapes': ["Disposer le poulet, les tomates, les oignons et l'aubergine dans une cocotte.", "Ajouter l'ail, le gingembre, le piment et l'assaisonnement.", "Couvrir hermétiquement et cuire à feu doux sans ajouter d'eau.", "Secouer la cocotte de temps en temps et servir avec de l'attiéké."],
     'tags': ['Poulet', 'Étouffée', 'Abidjan', 'National'], 'image_url': ''},
    {'titre': 'Dégué ivoirien', 'pays': 'ivory coast', 'type_plat': 'sucré',
     'description': 'Un dessert frais de couscous de mil mélangé à un lait caillé sucré et parfumé, populaire dans toute l\'Afrique de l\'Ouest.',
     'temps_preparation': 20, 'temps_cuisson': 15, 'nb_personnes': 4, 'difficulte': 'Facile',
     'ingredients': ["250 g de couscous de mil", "500 ml de lait caillé", "80 g de sucre", "1 cuillère à café de vanille", "1 pincée de muscade", "raisins secs"],
     'etapes': ["Cuire le couscous de mil à la vapeur jusqu'à ce qu'il soit tendre.", "Laisser refroidir.", "Mélanger le lait caillé avec le sucre, la vanille et la muscade.", "Incorporer le mil et les raisins, puis servir frais."],
     'tags': ['Mil', 'Lait caillé', 'Abidjan', 'Dessert'], 'image_url': ''},
]


class Command(BaseCommand):
    help = 'Charge les recettes générées par agent pour 29 pays manquants (v1)'

    def handle(self, *args, **options):
        created, updated = 0, 0
        for data in RECIPES:
            lookup = {'titre': data['titre'], 'pays': data['pays'], 'type_plat': data['type_plat']}
            defaults = {k: v for k, v in data.items() if k not in lookup}
            _, was_created = Recipe.objects.update_or_create(**lookup, defaults=defaults)
            if was_created:
                created += 1
            else:
                updated += 1
        self.stdout.write(self.style.SUCCESS(
            f'Done — {created} created, {updated} updated ({created + updated} total)'
        ))
