from django.core.management.base import BaseCommand
from apps.recipes.models import Recipe

RECIPES = [
    # ── BRAZIL ───────────────────────────────────────────────────────────────
    {
        'titre': 'Feijoada',
        'pays': 'brazil',
        'type_plat': 'salé',
        'description': 'Le plat national brésilien : ragoût de haricots noirs et de viandes de porc fumées, servi avec riz, chou sauté et orange.',
        'temps_preparation': 30, 'temps_cuisson': 180, 'nb_personnes': 8, 'difficulte': 'Moyen',
        'ingredients': ['500 g de haricots noirs secs', '300 g de lard fumé', '200 g de saucisse calabresa',
                        '2 jarrets de porc fumés', '1 oreille de porc (optionnel)', '3 gousses d\'ail',
                        '2 oignons', 'Laurier', 'Sel, poivre', 'Huile', 'Riz blanc, chou frisé, orange pour servir'],
        'etapes': ['Faire tremper les haricots noirs 12h. Égoutter.',
                   'Faire revenir oignon et ail dans l\'huile. Ajouter les viandes et les faire dorer.',
                   'Ajouter les haricots, couvrir d\'eau et porter à ébullition.',
                   'Ajouter le laurier et mijoter 2h30 à feu doux jusqu\'à ce que les haricots soient fondants.',
                   'Servir avec riz blanc, chou kale sauté à l\'ail et quartiers d\'orange.'],
        'tags': ['National', 'Mijoté', 'Porc', 'Rio'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Feijoada.jpg/800px-Feijoada.jpg',
    },
    {
        'titre': 'Brigadeiro',
        'pays': 'brazil',
        'type_plat': 'sucré',
        'description': 'Truffe au chocolat brésilienne : lait concentré sucré, cacao et beurre roulés dans des vermicelles de chocolat.',
        'temps_preparation': 10, 'temps_cuisson': 15, 'nb_personnes': 20, 'difficulte': 'Facile',
        'ingredients': ['1 boîte de lait concentré sucré (395 g)', '3 c. à soupe de cacao en poudre',
                        '1 c. à soupe de beurre', 'Vermicelles de chocolat pour enrober'],
        'etapes': ['Mélanger lait concentré, cacao et beurre dans une casserole.',
                   'Cuire à feu moyen en remuant constamment jusqu\'à ce que la préparation se détache du fond.',
                   'Verser sur un plat beurré. Laisser refroidir 30 min.',
                   'Former des petites boules avec les mains beurrées.',
                   'Rouler chaque boule dans les vermicelles de chocolat. Placer dans des caissettes.'],
        'tags': ['Chocolat', 'São Paulo', 'Fête', 'Sans cuisson complexe'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Brigadeiro.jpg/800px-Brigadeiro.jpg',
    },

    # ── ARGENTINA ────────────────────────────────────────────────────────────
    {
        'titre': 'Asado Argentin',
        'pays': 'argentina',
        'type_plat': 'salé',
        'description': 'Le rituel national argentin : grandes pièces de bœuf cuites lentement sur braise de bois, assaisonnées de chimichurri.',
        'temps_preparation': 20, 'temps_cuisson': 120, 'nb_personnes': 6, 'difficulte': 'Moyen',
        'ingredients': ['2 kg d\'entrecôte ou côtes de bœuf', 'Gros sel', '1 bouquet de persil plat',
                        '4 gousses d\'ail', '1 piment rouge', 'Origan', 'Vinaigre de vin rouge', 'Huile d\'olive'],
        'etapes': ['Préparer la braise avec du bois ou du charbon. Attendre que les braises soient blanches.',
                   'Saler généreusement les pièces de viande côté chair uniquement.',
                   'Poser la viande côté os sur la grille à hauteur modérée. Cuire 1h sans retourner.',
                   'Retourner et cuire encore 30 min côté chair.',
                   'Préparer le chimichurri : mixer persil, ail, piment, origan, vinaigre et huile. Servir à côté.'],
        'tags': ['Grill', 'Bœuf', 'Buenos Aires', 'Partage'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Asado_en_Argentina.JPG/800px-Asado_en_Argentina.JPG',
    },
    {
        'titre': 'Alfajores',
        'pays': 'argentina',
        'type_plat': 'sucré',
        'description': 'Biscuits sablés à la Maïzena fourrés de dulce de leche et enrobés de noix de coco râpée ou de chocolat.',
        'temps_preparation': 30, 'temps_cuisson': 12, 'nb_personnes': 20, 'difficulte': 'Facile',
        'ingredients': ['200 g de Maïzena', '100 g de farine', '150 g de beurre mou', '80 g de sucre glace',
                        '3 jaunes d\'œuf', '1 c. de cognac', 'Zeste de citron', '400 g de dulce de leche',
                        '100 g de noix de coco râpée'],
        'etapes': ['Mélanger Maïzena, farine et sel. Sabler avec le beurre.',
                   'Ajouter sucre glace, jaunes, cognac et zeste. Former une boule. Réfrigérer 30 min.',
                   'Étaler à 5 mm. Découper des ronds de 4 cm. Cuire 10–12 min à 180°C (sans coloration).',
                   'Laisser refroidir. Garnir un biscuit de dulce de leche et coiffer d\'un second.',
                   'Rouler les bords dans la noix de coco râpée.'],
        'tags': ['Biscuit', 'Dulce de leche', 'Goûter', 'Incontournable'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Alfajores_de_maicena.jpg/800px-Alfajores_de_maicena.jpg',
    },

    # ── MEXICO ────────────────────────────────────────────────────────────────
    {
        'titre': 'Tacos al Pastor',
        'pays': 'mexico',
        'type_plat': 'salé',
        'description': 'Le taco de rue mexicain par excellence : porc mariné aux épices et ananas, cuit à la broche, dans une tortilla de maïs.',
        'temps_preparation': 30, 'temps_cuisson': 30, 'nb_personnes': 4, 'difficulte': 'Moyen',
        'ingredients': ['600 g de porc (épaule)', '3 piments chipotle en adobo', '1 c. d\'origan',
                        '1 c. de cumin', '1 c. de paprika', '3 gousses d\'ail', '2 c. de vinaigre de cidre',
                        '1 tranche d\'ananas', 'Tortillas de maïs', 'Oignon blanc, coriandre, citron vert'],
        'etapes': ['Mixer chipotle, origan, cumin, paprika, ail et vinaigre pour la marinade.',
                   'Couper le porc en tranches fines. Mariner 4h minimum au frais.',
                   'Griller les tranches de porc à la poêle très chaude 3 min de chaque côté.',
                   'Griller également l\'ananas en dés.',
                   'Garnir les tortillas chaudes de viande, ananas, oignon haché, coriandre et jus de citron vert.'],
        'tags': ['Street food', 'Taco', 'Mexico City', 'Épicé'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Taco_de_pastor.jpg/800px-Taco_de_pastor.jpg',
    },
    {
        'titre': 'Tres Leches',
        'pays': 'mexico',
        'type_plat': 'sucré',
        'description': 'Gâteau imbibé de trois laits (entier, condensé, crème), ultra-moelleux, nappé de chantilly et cannelle.',
        'temps_preparation': 30, 'temps_cuisson': 35, 'nb_personnes': 12, 'difficulte': 'Facile',
        'ingredients': ['4 œufs', '200 g de sucre', '200 g de farine', '1 c. de levure',
                        '200 ml de lait entier', '200 ml de lait concentré sucré', '200 ml de crème liquide',
                        '300 ml de crème fouettée', 'Cannelle en poudre'],
        'etapes': ['Battre œufs et sucre jusqu\'à blanchissement. Incorporer farine et levure.',
                   'Cuire dans un moule 30 min à 180°C. Laisser refroidir 10 min.',
                   'Mélanger les trois laits. Piquer le gâteau partout avec une fourchette.',
                   'Verser le mélange de laits progressivement sur le gâteau. Réfrigérer 4h.',
                   'Napper de crème fouettée et saupoudrer de cannelle avant de servir.'],
        'tags': ['Moelleux', 'Dessert', 'Festif', 'Guadalajara'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Tres_leches_cake.jpg/800px-Tres_leches_cake.jpg',
    },

    # ── UNITED STATES ────────────────────────────────────────────────────────
    {
        'titre': 'BBQ Ribs (Travers de Porc)',
        'pays': 'united states',
        'type_plat': 'salé',
        'description': 'Travers de porc marinés et laqués au BBQ sauce américaine, fumés lentement jusqu\'à tendreté — le "fall off the bone".',
        'temps_preparation': 20, 'temps_cuisson': 180, 'nb_personnes': 4, 'difficulte': 'Moyen',
        'ingredients': ['1,5 kg de travers de porc (spare ribs)', '2 c. de paprika fumé', '1 c. de cumin',
                        '1 c. d\'ail en poudre', '1 c. de sucre brun', 'Sel, poivre',
                        '300 ml de sauce BBQ (ketchup, mélasse, Worcestershire, vinaigre, moutarde)'],
        'etapes': ['Mélanger les épices et le sucre brun pour le dry rub. Frotter les ribs.',
                   'Envelopper dans du papier alu. Cuire au four 2h30 à 150°C.',
                   'Préparer la sauce BBQ en mélangeant et cuisant 15 min à feu doux.',
                   'Sortir les ribs, badigeonner généreusement de sauce BBQ.',
                   'Passer sous le grill 10 min en retournant et laquant plusieurs fois.'],
        'tags': ['BBQ', 'Fumé', 'Kansas City', 'Grill'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/BBQ_Spare_Ribs.jpg/800px-BBQ_Spare_Ribs.jpg',
    },
    {
        'titre': 'New York Cheesecake',
        'pays': 'united states',
        'type_plat': 'sucré',
        'description': 'Le cheesecake new-yorkais : base de spéculoos beurrés, crème au fromage frais ultra-crémeuse et coulis de fraises.',
        'temps_preparation': 25, 'temps_cuisson': 60, 'nb_personnes': 10, 'difficulte': 'Moyen',
        'ingredients': ['200 g de biscuits Graham crackers ou spéculoos', '80 g de beurre fondu',
                        '800 g de cream cheese (Philadelphia)', '200 g de sucre', '4 œufs',
                        '200 ml de crème fraîche épaisse', '1 c. d\'extrait de vanille', '200 g de fraises (coulis)'],
        'etapes': ['Écraser les biscuits et mélanger avec le beurre fondu. Tasser dans un moule à charnière.',
                   'Battre cream cheese et sucre. Ajouter œufs un par un, puis crème et vanille.',
                   'Verser sur la base biscuitée. Cuire au bain-marie 55–60 min à 160°C.',
                   'Éteindre le four, laisser refroidir 1h porte entrouverte.',
                   'Réfrigérer 8h. Mixer les fraises en coulis et servir à côté.'],
        'tags': ['New York', 'Cream cheese', 'Dessert', 'Classique'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Cheesecake.jpg/800px-Cheesecake.jpg',
    },

    # ── CANADA ────────────────────────────────────────────────────────────────
    {
        'titre': 'Poutine',
        'pays': 'canada',
        'type_plat': 'salé',
        'description': 'Le plat culte québécois : frites croustillantes, fromage en grains (cheese curds) et sauce brune chaude.',
        'temps_preparation': 20, 'temps_cuisson': 30, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['1 kg de pommes de terre (Russet)', 'Huile de friture',
                        '300 g de fromage en grains (cheese curds ou mozarella en dés)',
                        '500 ml de fond de veau', '2 c. de farine', '1 c. de sauce Worcestershire', 'Sel'],
        'etapes': ['Couper les pommes de terre en frites épaisses. Rincer et bien sécher.',
                   'Préparer la sauce : faire un roux avec beurre et farine, ajouter le fond de veau et Worcestershire. Mijoter 10 min.',
                   'Frire les frites une première fois à 160°C, égoutter.',
                   'Frire une seconde fois à 190°C jusqu\'à dorure. Saler immédiatement.',
                   'Disposer les frites, couvrir de fromage en grains et napper de sauce brune très chaude.'],
        'tags': ['Québec', 'Street food', 'Réconfort', 'Incontournable'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Poutine_1.jpg/800px-Poutine_1.jpg',
    },
    {
        'titre': 'Butter Tarts',
        'pays': 'canada',
        'type_plat': 'sucré',
        'description': 'Tartelettes canadiennes au caramel beurré coulant — icône pâtissière de l\'Ontario.',
        'temps_preparation': 25, 'temps_cuisson': 20, 'nb_personnes': 12, 'difficulte': 'Facile',
        'ingredients': ['200 g de pâte brisée', '100 g de cassonade', '100 g de sirop de maïs (ou sirop d\'érable)',
                        '50 g de beurre fondu', '1 œuf', '1 c. de vanille', '1 pincée de sel',
                        '50 g de raisins secs (optionnel)'],
        'etapes': ['Étaler la pâte et foncer 12 moules à tartelette. Réfrigérer 15 min.',
                   'Mélanger cassonade, sirop, beurre fondu, œuf, vanille et sel.',
                   'Déposer quelques raisins dans chaque fond si désiré.',
                   'Verser l\'appareil aux 2/3 de chaque tartelette.',
                   'Cuire 18–20 min à 200°C. La garniture doit être légèrement coulante au centre.'],
        'tags': ['Ontario', 'Caramel', 'Pâtisserie', 'Sirop d\'érable'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Butter_tarts.jpg/800px-Butter_tarts.jpg',
    },

    # ── COLOMBIA ──────────────────────────────────────────────────────────────
    {
        'titre': 'Bandeja Paisa',
        'pays': 'colombia',
        'type_plat': 'salé',
        'description': 'L\'assiette montagnarde colombienne : haricots rouges, riz, chicharrón, chorizo, œuf au plat, avocat et arepa.',
        'temps_preparation': 30, 'temps_cuisson': 90, 'nb_personnes': 4, 'difficulte': 'Moyen',
        'ingredients': ['400 g de haricots rouges', '300 g de ventre de porc (chicharrón)', '4 chorizos',
                        '4 œufs', '2 avocats', '4 arepas de maïs', 'Riz blanc', '2 tomates', '1 oignon',
                        '3 gousses d\'ail', 'Cumin, sel'],
        'etapes': ['Cuire les haricots avec ail, oignon, tomates et cumin 1h30. Rectifier l\'assaisonnement.',
                   'Faire griller le ventre de porc en cubes à feu vif jusqu\'à croustillant (chicharrón).',
                   'Griller les chorizos à la poêle.',
                   'Cuire les œufs au plat et réchauffer les arepas à la poêle.',
                   'Dresser chaque assiette avec tous les éléments séparés. Servir avec avocat en tranches.'],
        'tags': ['Medellín', 'Festif', 'Complet', 'Antioquia'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Bandeja_paisa.jpg/800px-Bandeja_paisa.jpg',
    },
    {
        'titre': 'Buñuelos Colombianos',
        'pays': 'colombia',
        'type_plat': 'sucré',
        'description': 'Beignets de fromage frits et soufflés, croustillants dehors et fondants dedans — tradition de Noël colombienne.',
        'temps_preparation': 15, 'temps_cuisson': 15, 'nb_personnes': 6, 'difficulte': 'Facile',
        'ingredients': ['250 g de fromage blanc colombien (ou cottage cheese)',
                        '100 g de fécule de maïs', '50 g de farine', '1 œuf',
                        '2 c. de sucre', '1 c. de levure chimique', 'Huile de friture'],
        'etapes': ['Bien égoutter le fromage. Écraser et mélanger avec fécule, farine, œuf, sucre et levure.',
                   'Pétrir jusqu\'à obtenir une pâte souple. Former des boules de 3 cm.',
                   'Chauffer l\'huile à 170°C.',
                   'Frire les boules en petites quantités 5–6 min en les retournant.',
                   'Égoutter sur papier absorbant. Servir chauds.'],
        'tags': ['Beignet', 'Fromage', 'Noël', 'Bogotá'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Bu%C3%B1uelos_colombianos.jpg/800px-Bu%C3%B1uelos_colombianos.jpg',
    },

    # ── URUGUAY ───────────────────────────────────────────────────────────────
    {
        'titre': 'Chivito Uruguayen',
        'pays': 'uruguay',
        'type_plat': 'salé',
        'description': 'Le sandwich national uruguayen : fine escalope de bœuf, jambon, fromage, œuf, bacon, laitue et mayonnaise.',
        'temps_preparation': 15, 'temps_cuisson': 15, 'nb_personnes': 2, 'difficulte': 'Facile',
        'ingredients': ['2 fines escalopes de bœuf (lomo)', '2 tranches de jambon', '2 tranches de fromage',
                        '2 œufs', '4 tranches de bacon', '2 pains à burger', 'Laitue, tomate, oignon',
                        'Mayonnaise', 'Sel, poivre'],
        'etapes': ['Griller le bacon jusqu\'à croustillant. Réserver.',
                   'Cuire les escalopes assaisonnées 2 min de chaque côté sur plancha très chaude.',
                   'Poser le fromage sur la viande en fin de cuisson pour le faire fondre.',
                   'Cuire les œufs au plat.',
                   'Assembler dans le pain grillé : viande, jambon, œuf, bacon, laitue, tomate, mayo.'],
        'tags': ['Sandwich', 'Montevideo', 'Rapide', 'Street food'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Chivito_uruguayo.jpg/800px-Chivito_uruguayo.jpg',
    },
    {
        'titre': 'Pasta Frola',
        'pays': 'uruguay',
        'type_plat': 'sucré',
        'description': 'Tarte sablée uruguayenne garnie de confiture de membrillo (coing), avec une grille de pâte décorée.',
        'temps_preparation': 30, 'temps_cuisson': 35, 'nb_personnes': 8, 'difficulte': 'Facile',
        'ingredients': ['300 g de farine', '150 g de beurre', '100 g de sucre', '2 jaunes d\'œuf',
                        '1 c. de levure', 'Zeste de citron', '400 g de pâte de coing (membrillo)'],
        'etapes': ['Sabler farine, beurre et sucre. Ajouter jaunes, levure et zeste. Former une boule.',
                   'Diviser en 2/3 et 1/3. Réfrigérer 20 min.',
                   'Étaler les 2/3 dans un moule de 24 cm. Piquer le fond.',
                   'Étaler le membrillo en couche uniforme sur la pâte.',
                   'Former une grille avec le tiers restant. Cuire 30–35 min à 180°C.'],
        'tags': ['Tarte', 'Coing', 'Montevideo', 'Goûter'],
        'image_url': '',
    },

    # ── ECUADOR ───────────────────────────────────────────────────────────────
    {
        'titre': 'Ceviche Ecuatorien',
        'pays': 'ecuador',
        'type_plat': 'salé',
        'description': 'Ceviche de crevettes à l\'équatorienne : marinade de citron vert et orange, tomates et coriandre fraîche.',
        'temps_preparation': 20, 'temps_cuisson': 0, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['500 g de crevettes cuites', '4 citrons verts (jus)', '2 oranges (jus)',
                        '3 tomates', '1 oignon rouge', '1 bouquet de coriandre', '1 piment rouge',
                        'Sel, poivre', 'Chips de plantain et popcorn pour servir'],
        'etapes': ['Éplucher et déveiner les crevettes. Réserver dans un saladier.',
                   'Presser les citrons verts et les oranges sur les crevettes. Mariner 10 min.',
                   'Couper tomates et oignon rouge en petits dés. Émincer la coriandre.',
                   'Ajouter tomates, oignon, coriandre et piment au ceviche. Assaisonner.',
                   'Servir frais avec chips de plantain et popcorn traditionnellement.'],
        'tags': ['Frais', 'Guayaquil', 'Fruits de mer', 'Été'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Ceviche_de_camarones.jpg/800px-Ceviche_de_camarones.jpg',
    },
    {
        'titre': 'Colada Morada',
        'pays': 'ecuador',
        'type_plat': 'sucré',
        'description': 'Boisson-dessert équatorienne de la Toussaint : maïs violet, fruits tropicaux et épices chaudes, servie avec des guaguas de pan.',
        'temps_preparation': 20, 'temps_cuisson': 40, 'nb_personnes': 8, 'difficulte': 'Moyen',
        'ingredients': ['200 g de maïs violet moulu (maseca morada)', '2 L d\'eau', '200 g de sucre',
                        '2 bâtons de cannelle', '5 clous de girofle', '1 anis étoilé',
                        '200 g d\'ananas en dés', '200 g de fraises', '100 g de mûres', 'Zeste de citron'],
        'etapes': ['Infuser cannelle, clous et anis dans 1,5 L d\'eau bouillante 10 min. Filtrer.',
                   'Délayer le maïs violet dans 500 ml d\'eau froide sans grumeaux.',
                   'Verser le mélange de maïs dans l\'infusion chaude en fouettant.',
                   'Cuire à feu moyen en remuant 20 min jusqu\'à épaississement.',
                   'Ajouter sucre, fruits et zeste. Cuire encore 10 min. Servir chaud ou tiède.'],
        'tags': ['Boisson chaude', 'Toussaint', 'Fruits tropicaux', 'Quito'],
        'image_url': '',
    },

    # ── MOROCCO ───────────────────────────────────────────────────────────────
    {
        'titre': 'Tajine d\'Agneau aux Pruneaux',
        'pays': 'morocco',
        'type_plat': 'salé',
        'description': 'Tajine marocain sucré-salé : agneau confit aux épices ras el hanout, pruneaux caramélisés et amandes grillées.',
        'temps_preparation': 20, 'temps_cuisson': 90, 'nb_personnes': 4, 'difficulte': 'Moyen',
        'ingredients': ['1,2 kg d\'épaule d\'agneau', '200 g de pruneaux', '50 g d\'amandes mondées',
                        '2 oignons', '3 gousses d\'ail', '1 c. de ras el hanout', '1 c. de cannelle',
                        '1 c. de gingembre', 'Safran', '2 c. de miel', 'Huile d\'olive', 'Sel'],
        'etapes': ['Faire dorer les morceaux d\'agneau dans l\'huile avec oignons et ail.',
                   'Ajouter toutes les épices et suffisamment d\'eau pour couvrir à mi-hauteur.',
                   'Cuire à couvert à feu doux 1h en tajine ou cocotte.',
                   'Ajouter pruneaux et miel. Cuire encore 20 min.',
                   'Faire dorer les amandes à sec et parsemer sur le tajine. Servir avec couscous ou pain.'],
        'tags': ['Tajine', 'Marrakech', 'Sucré-salé', 'Festif'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Moroccan_Lamb_Tagine_with_Preserved_Lemon_and_Olives.jpg/800px-Moroccan_Lamb_Tagine_with_Preserved_Lemon_and_Olives.jpg',
    },
    {
        'titre': 'Cornes de Gazelle',
        'pays': 'morocco',
        'type_plat': 'sucré',
        'description': 'Pâtisserie marocaine fine en croissant : pâte légère fourrée d\'une pâte d\'amande à la fleur d\'oranger.',
        'temps_preparation': 60, 'temps_cuisson': 15, 'nb_personnes': 24, 'difficulte': 'Difficile',
        'ingredients': ['300 g de farine', '100 g de beurre fondu', '100 ml d\'eau de fleur d\'oranger',
                        '300 g d\'amandes en poudre', '150 g de sucre glace', '1 blanc d\'œuf',
                        '1 c. de cannelle', 'Eau de fleur d\'oranger (arôme)'],
        'etapes': ['Préparer la pâte d\'amande : mélanger amandes, sucre glace, blanc d\'œuf, cannelle et eau de fleur d\'oranger. Rouler en boudins de 6 cm.',
                   'Préparer la pâte extérieure : farine, beurre fondu, fleur d\'oranger et eau. Reposer 30 min.',
                   'Étaler finement et découper en rectangles de 8×6 cm.',
                   'Poser un boudin d\'amande, refermer en croissant en soudant les bords.',
                   'Cuire 12–15 min à 180°C. Saupoudrer légèrement de sucre glace.'],
        'tags': ['Pâtisserie', 'Amande', 'Fes', 'Thé'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Kaab_el_ghazal.jpg/800px-Kaab_el_ghazal.jpg',
    },

    # ── SENEGAL ───────────────────────────────────────────────────────────────
    {
        'titre': 'Thiéboudienne',
        'pays': 'senegal',
        'type_plat': 'salé',
        'description': 'Le plat national sénégalais : riz au poisson braisé et légumes dans une sauce tomate fumée au bois.',
        'temps_preparation': 30, 'temps_cuisson': 90, 'nb_personnes': 6, 'difficulte': 'Moyen',
        'ingredients': ['1 kg de riz brisé', '1,5 kg de poisson (thiof ou mérou)', '3 tomates',
                        '2 c. de concentré de tomate', '1 manioc', '2 carottes', '1 chou blanc',
                        '3 gousses d\'ail', '2 piments', 'Guedj (poisson fermenté séché)', 'Huile, sel'],
        'etapes': ['Préparer la farce nététu : mixer ail, piment et herbes. Farcir le poisson.',
                   'Faire revenir le poisson à l\'huile chaude jusqu\'à coloration. Réserver.',
                   'Faire une sauce tomate avec concentré, tomates fraîches et guedj dans la même huile.',
                   'Ajouter l\'eau, les légumes et le poisson. Cuire 30 min.',
                   'Retirer poisson et légumes. Cuire le riz dans le bouillon de cuisson 20 min.'],
        'tags': ['National', 'Dakar', 'Poisson', 'Festif'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Thieboudienne.jpg/800px-Thieboudienne.jpg',
    },
    {
        'titre': 'Thiakry',
        'pays': 'senegal',
        'type_plat': 'sucré',
        'description': 'Dessert sénégalais léger : semoule de mil ou couscous, crème de yaourt sucrée, raisins secs et noix de coco.',
        'temps_preparation': 15, 'temps_cuisson': 10, 'nb_personnes': 6, 'difficulte': 'Facile',
        'ingredients': ['300 g de couscous fin ou semoule de mil', '400 ml de yaourt nature',
                        '200 ml de crème fraîche', '100 g de sucre', '50 g de raisins secs',
                        '50 g de noix de coco râpée', '1 c. de vanille', 'Eau de fleur d\'oranger'],
        'etapes': ['Cuire le couscous à la vapeur ou à l\'eau selon le paquet. Laisser refroidir.',
                   'Mélanger yaourt, crème fraîche, sucre, vanille et eau de fleur d\'oranger.',
                   'Incorporer le couscous refroidi à la crème.',
                   'Ajouter raisins secs et noix de coco. Bien mélanger.',
                   'Réfrigérer 1h. Servir frais dans des verres ou coupelles.'],
        'tags': ['Frais', 'Dakar', 'Dessert léger', 'Mil'],
        'image_url': '',
    },

    # ── NIGERIA ───────────────────────────────────────────────────────────────
    {
        'titre': 'Jollof Rice',
        'pays': 'nigeria',
        'type_plat': 'salé',
        'description': 'Le riz tomate fétiche ouest-africain : riz cuit dans une sauce de tomates, poivrons et épices, légèrement fumé.',
        'temps_preparation': 20, 'temps_cuisson': 50, 'nb_personnes': 6, 'difficulte': 'Moyen',
        'ingredients': ['500 g de riz long grain', '400 g de tomates concassées', '2 poivrons rouges',
                        '2 oignons', '3 gousses d\'ail', '1 c. de curry', '1 c. de thym',
                        '1 c. de paprika fumé', '500 ml de bouillon de poulet', 'Huile végétale', 'Sel'],
        'etapes': ['Mixer tomates, poivrons et oignon pour obtenir une purée.',
                   'Faire revenir la purée dans l\'huile chaude 20 min jusqu\'à réduction et légère coloration.',
                   'Ajouter curry, thym, paprika et bouillon. Porter à ébullition.',
                   'Ajouter le riz lavé, couvrir hermétiquement et cuire à feu très doux 25 min.',
                   'Découvrir les 5 dernières minutes pour obtenir la croûte légèrement fumée du fond.'],
        'tags': ['Lagos', 'Ouest-africain', 'Riz', 'Festif'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Jollof_Rice.jpg/800px-Jollof_Rice.jpg',
    },
    {
        'titre': 'Puff Puff',
        'pays': 'nigeria',
        'type_plat': 'sucré',
        'description': 'Beignets ronds et sucrés nigérians, légers et moelleux, parfumés à la noix de muscade — le snack de rue africain.',
        'temps_preparation': 15, 'temps_cuisson': 15, 'nb_personnes': 6, 'difficulte': 'Facile',
        'ingredients': ['300 g de farine', '7 g de levure sèche', '150 ml d\'eau tiède',
                        '100 g de sucre', '1 pincée de muscade', '1 pincée de sel', 'Huile de friture'],
        'etapes': ['Dissoudre la levure dans l\'eau tiède avec 1 c. de sucre. Laisser mousser 5 min.',
                   'Mélanger farine, sucre, sel et muscade. Verser la levure.',
                   'Pétrir pour obtenir une pâte lisse et collante. Laisser lever 1h.',
                   'Chauffer l\'huile à 170°C. Déposer des boules de pâte à la cuillère.',
                   'Frire 3–4 min en retournant jusqu\'à dorure uniforme. Égoutter et servir.'],
        'tags': ['Beignet', 'Lagos', 'Street food', 'Snack'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Puff_puff.jpg/800px-Puff_puff.jpg',
    },

    # ── EGYPT ─────────────────────────────────────────────────────────────────
    {
        'titre': 'Koshari',
        'pays': 'egypt',
        'type_plat': 'salé',
        'description': 'Le street food national égyptien : riz, lentilles, macaronis, sauce tomate épicée et oignons frits croustillants.',
        'temps_preparation': 20, 'temps_cuisson': 50, 'nb_personnes': 4, 'difficulte': 'Moyen',
        'ingredients': ['200 g de riz', '150 g de lentilles vertes', '150 g de macaronis',
                        '400 g de tomates concassées', '3 oignons', '3 gousses d\'ail',
                        '1 c. de cumin', '1 c. de vinaigre', 'Piment rouge', 'Huile de friture', 'Sel'],
        'etapes': ['Cuire les lentilles à l\'eau 20 min. Cuire le riz séparément. Cuire les macaronis al dente.',
                   'Émincer les oignons et les frire dans l\'huile jusqu\'à brun croustillant. Égoutter.',
                   'Préparer la sauce : faire revenir ail, ajouter tomates, vinaigre et épices. Cuire 20 min.',
                   'Mélanger riz et lentilles dans un plat. Ajouter les macaronis dessus.',
                   'Napper généreusement de sauce tomate et couvrir d\'oignons frits.'],
        'tags': ['Le Caire', 'Végétarien', 'Street food', 'National'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Koshary_3.jpg/800px-Koshary_3.jpg',
    },
    {
        'titre': 'Om Ali',
        'pays': 'egypt',
        'type_plat': 'sucré',
        'description': 'Pudding de pain égyptien : feuilletés brisés imbibés de lait sucré, noix et raisins, gratinés à la crème.',
        'temps_preparation': 15, 'temps_cuisson': 25, 'nb_personnes': 6, 'difficulte': 'Facile',
        'ingredients': ['200 g de pâte feuilletée cuite ou pain de mie grillé', '500 ml de lait entier',
                        '100 ml de crème liquide', '100 g de sucre', '50 g de noix mélangées',
                        '50 g de raisins secs', '50 g de noix de coco râpée', '1 c. de vanille'],
        'etapes': ['Émietter la pâte feuilletée en morceaux dans un plat à gratin.',
                   'Ajouter noix, raisins et noix de coco.',
                   'Chauffer lait, crème, sucre et vanille jusqu\'à frémissement.',
                   'Verser le mélange lait-crème sur la pâte en couvrant uniformément.',
                   'Cuire au four à 180°C 20–25 min jusqu\'à gratin doré. Servir chaud.'],
        'tags': ['Pudding', 'Le Caire', 'Réconfort', 'Festif'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Om_Ali.jpg/800px-Om_Ali.jpg',
    },

    # ── CAMEROON ──────────────────────────────────────────────────────────────
    {
        'titre': 'Ndolé',
        'pays': 'cameroon',
        'type_plat': 'salé',
        'description': 'Le plat national camerounais : feuilles de ndolé (amarante amère) mijotées avec crevettes, arachides et viande.',
        'temps_preparation': 30, 'temps_cuisson': 60, 'nb_personnes': 6, 'difficulte': 'Moyen',
        'ingredients': ['500 g de feuilles de ndolé (ou épinards en substitut)', '300 g de bœuf',
                        '200 g de crevettes séchées', '100 g de pâte d\'arachide', '2 oignons',
                        '3 gousses d\'ail', 'Crevettes fraîches (optionnel)', 'Huile de palme', 'Sel, piment'],
        'etapes': ['Faire bouillir les feuilles 2 fois en changeant l\'eau pour réduire l\'amertume.',
                   'Faire revenir oignons et ail dans l\'huile de palme.',
                   'Ajouter le bœuf coupé en cubes et les crevettes séchées.',
                   'Incorporer la pâte d\'arachide diluée dans un peu d\'eau chaude.',
                   'Ajouter les feuilles égouttées. Mijoter 30 min à feu doux. Servir avec plantain ou miondo.'],
        'tags': ['National', 'Douala', 'Arachide', 'Festif'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Ndole.jpg/800px-Ndole.jpg',
    },
    {
        'titre': 'Beignets de Banane Plantain',
        'pays': 'cameroon',
        'type_plat': 'sucré',
        'description': 'Beignets sucrés de banane plantain mûre frits, enrobés de sucre — snack de rue incontournable au Cameroun.',
        'temps_preparation': 10, 'temps_cuisson': 15, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['3 bananes plantain bien mûres (peau noire)', '100 g de farine',
                        '1 œuf', '50 g de sucre', '1 pincée de cannelle', 'Huile de friture'],
        'etapes': ['Écraser les bananes plantain en purée lisse.',
                   'Ajouter farine, œuf, sucre et cannelle. Mélanger en pâte homogène.',
                   'Chauffer l\'huile à 170°C.',
                   'Déposer des cuillères de pâte dans l\'huile et frire 3–4 min de chaque côté.',
                   'Égoutter sur papier absorbant. Saupoudrer de sucre. Servir chauds.'],
        'tags': ['Plantain', 'Yaoundé', 'Street food', 'Rapide'],
        'image_url': '',
    },

    # ── SOUTH AFRICA ──────────────────────────────────────────────────────────
    {
        'titre': 'Bobotie',
        'pays': 'south africa',
        'type_plat': 'salé',
        'description': 'Plat national sud-africain Cape Malay : bœuf haché épicé aux raisins, couvert d\'un flan œuf-lait.',
        'temps_preparation': 20, 'temps_cuisson': 50, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['600 g de bœuf haché', '2 oignons', '2 gousses d\'ail', '2 c. de curry en poudre',
                        '1 c. de curcuma', '50 g de raisins secs', '2 tranches de pain de mie',
                        '100 ml de lait', '2 œufs', 'Feuilles de laurier', 'Sel, poivre'],
        'etapes': ['Tremper le pain dans le lait. Presser et réserver le lait.',
                   'Faire revenir oignons et ail. Ajouter la viande, le curry et le curcuma.',
                   'Incorporer le pain émietté et les raisins secs. Assaisonner.',
                   'Transvaser dans un plat à gratin. Piquer les feuilles de laurier.',
                   'Battre œufs et lait réservé. Verser sur la viande. Cuire 35 min à 180°C.'],
        'tags': ['Cape Malay', 'Le Cap', 'Sucré-salé', 'National'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Bobotie.jpg/800px-Bobotie.jpg',
    },
    {
        'titre': 'Melktert (Tarte au Lait)',
        'pays': 'south africa',
        'type_plat': 'sucré',
        'description': 'Tarte au lait sud-africaine : crème custard douce à la cannelle dans un fond de pâte sablée.',
        'temps_preparation': 25, 'temps_cuisson': 30, 'nb_personnes': 8, 'difficulte': 'Facile',
        'ingredients': ['200 g de pâte sablée', '500 ml de lait entier', '2 œufs', '80 g de sucre',
                        '40 g de Maïzena', '20 g de beurre', '1 c. d\'extrait de vanille', 'Cannelle en poudre'],
        'etapes': ['Foncer un moule de 24 cm avec la pâte sablée. Cuire à blanc 15 min à 180°C.',
                   'Chauffer le lait avec la vanille jusqu\'à frémissement.',
                   'Battre œufs et sucre. Ajouter la Maïzena.',
                   'Verser le lait chaud sur les œufs en fouettant. Remettre sur feu jusqu\'à épaississement.',
                   'Incorporer le beurre. Verser dans le fond de tarte refroidi. Saupoudrer de cannelle.'],
        'tags': ['Tarte', 'Cannelle', 'Cape Town', 'Afrikaner'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Melktert.jpg/800px-Melktert.jpg',
    },

    # ── ALGERIA ───────────────────────────────────────────────────────────────
    {
        'titre': 'Couscous Algerien au Poulet',
        'pays': 'algeria',
        'type_plat': 'salé',
        'description': 'Le couscous du vendredi algérien : semoule fine à la vapeur, bouillon de légumes parfumé et poulet mijoté.',
        'temps_preparation': 30, 'temps_cuisson': 90, 'nb_personnes': 6, 'difficulte': 'Moyen',
        'ingredients': ['500 g de couscous fin', '1 poulet fermier découpé', '3 carottes', '2 courgettes',
                        '1 navet', '2 tomates', '1 oignon', '1 c. de ras el hanout', '1 c. de curcuma',
                        '1 bâton de cannelle', 'Pois chiches cuits', 'Huile', 'Sel'],
        'etapes': ['Faire revenir le poulet avec oignon et épices dans la marmite à couscous.',
                   'Ajouter carottes, navets, tomates et couvrir d\'eau. Porter à ébullition.',
                   'Mettre le couscous dans le panier vapeur au-dessus du bouillon. Cuire 20 min.',
                   'Ajouter courgettes et pois chiches dans le bouillon. Cuire encore 20 min.',
                   'Rouler le couscous avec un peu d\'huile. Dresser avec le bouillon et la viande.'],
        'tags': ['Vendredi', 'Alger', 'Famille', 'Vapeur'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Couscous_algerien.jpg/800px-Couscous_algerien.jpg',
    },
    {
        'titre': 'Makroud',
        'pays': 'algeria',
        'type_plat': 'sucré',
        'description': 'Gâteau de semoule algérien fourré de pâte de dattes et imbibé de miel — spécialité de Biskra.',
        'temps_preparation': 45, 'temps_cuisson': 25, 'nb_personnes': 20, 'difficulte': 'Moyen',
        'ingredients': ['400 g de semoule fine', '150 g de beurre fondu', '150 ml d\'eau de fleur d\'oranger',
                        '1 c. de levure', '300 g de dattes dénoyautées', '1 c. de cannelle',
                        '200 g de miel', 'Huile de friture'],
        'etapes': ['Mélanger semoule, beurre fondu, eau de fleur d\'oranger et levure. Former une pâte.',
                   'Préparer la farce : mixer dattes et cannelle en pâte lisse.',
                   'Étaler la pâte de semoule. Déposer un boudin de dattes. Rouler et couper en losanges.',
                   'Frire à 170°C jusqu\'à dorure ou cuire au four 20 min à 180°C.',
                   'Tremper dans le miel chaud dès la sortie. Laisser égoutter sur grille.'],
        'tags': ['Dattes', 'Biskra', 'Miel', 'Ramadan'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Makroud.jpg/800px-Makroud.jpg',
    },

    # ── IVORY COAST ───────────────────────────────────────────────────────────
    {
        'titre': 'Attiéké au Poisson Braisé',
        'pays': 'ivory coast',
        'type_plat': 'salé',
        'description': 'Semoule de manioc ivoirienne (attiéké) servie avec poisson braisé aux épices et sauce tomate-oignon.',
        'temps_preparation': 20, 'temps_cuisson': 30, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['400 g d\'attiéké (semoule de manioc fermentée)', '600 g de poisson entier (tilapia ou bar)',
                        '2 tomates', '2 oignons', '2 piments', '3 gousses d\'ail',
                        'Jus de citron', 'Huile végétale', 'Sel, bouillon en cube'],
        'etapes': ['Mariner le poisson avec ail, citron, piment et sel 30 min.',
                   'Griller le poisson sur braise ou au four grill 15 min de chaque côté.',
                   'Préparer la sauce oignon-tomate : faire revenir oignons, tomates et piment 15 min.',
                   'Réchauffer l\'attiéké à la vapeur ou au micro-ondes avec un peu d\'eau.',
                   'Servir l\'attiéké chaud avec le poisson braisé et la sauce par-dessus.'],
        'tags': ['Abidjan', 'Poisson', 'Manioc', 'Quotidien'],
        'image_url': '',
    },
    {
        'titre': 'Alloco',
        'pays': 'ivory coast',
        'type_plat': 'sucré',
        'description': 'Bananes plantain mûres frites en tranches épaisses, croustillantes dehors et fondantes dedans — snack de rue ivoirien.',
        'temps_preparation': 5, 'temps_cuisson': 10, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['3 bananes plantain bien mûres (peau jaune-noire)', 'Huile végétale pour friture',
                        'Piment en poudre (optionnel)', 'Sel'],
        'etapes': ['Éplucher les bananes plantain et couper en tranches obliques de 1,5 cm.',
                   'Chauffer l\'huile à 170°C dans une poêle.',
                   'Frire les tranches par petits lots 3–4 min de chaque côté jusqu\'à dorure.',
                   'Égoutter sur papier absorbant.',
                   'Saupoudrer de sel et de piment selon goût. Servir chaud.'],
        'tags': ['Plantain', 'Abidjan', 'Street food', 'Rapide'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Alloco.jpg/800px-Alloco.jpg',
    },

    # ── GHANA ─────────────────────────────────────────────────────────────────
    {
        'titre': 'Fufu et Soupe d\'Arachide',
        'pays': 'ghana',
        'type_plat': 'salé',
        'description': 'Fufu de manioc et plantain pilés servi avec une soupe d\'arachide au poulet épicée — plat festif ghanéen.',
        'temps_preparation': 30, 'temps_cuisson': 60, 'nb_personnes': 4, 'difficulte': 'Moyen',
        'ingredients': ['500 g de manioc pelé', '2 bananes plantain mûres', '1 poulet découpé',
                        '200 g de pâte d\'arachide', '3 tomates', '2 oignons', '2 piments',
                        '3 gousses d\'ail', 'Gingembre frais', 'Sel, bouillon'],
        'etapes': ['Cuire le manioc et les plantains à l\'eau 30 min. Égoutter.',
                   'Piler en alternance dans un mortier jusqu\'à obtenir une pâte lisse et élastique. Former des boules.',
                   'Faire revenir poulet avec oignons, ail et gingembre.',
                   'Diluer la pâte d\'arachide dans le bouillon. Ajouter tomates et piment. Cuire 30 min.',
                   'Servir le fufu dans la soupe. Manger avec les doigts en arrachant des morceaux de fufu.'],
        'tags': ['Accra', 'Festif', 'Arachide', 'Partage'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Fufu_and_groundnut_soup.jpg/800px-Fufu_and_groundnut_soup.jpg',
    },
    {
        'titre': 'Kelewele',
        'pays': 'ghana',
        'type_plat': 'sucré',
        'description': 'Cubes de plantain frit épicé au gingembre et piment — street food ghanéen servi le soir dans les rues d\'Accra.',
        'temps_preparation': 10, 'temps_cuisson': 10, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['3 bananes plantain mûres', '1 c. de gingembre frais râpé', '1 piment rouge émincé',
                        '1 c. de clous de girofle en poudre', '1 c. de sel', 'Huile de friture'],
        'etapes': ['Éplucher les plantains et couper en cubes de 3 cm.',
                   'Mélanger gingembre, piment, clou de girofle et sel. Enrober les cubes.',
                   'Laisser mariner 10 min.',
                   'Chauffer l\'huile à 175°C. Frire les cubes 4–5 min jusqu\'à dorure.',
                   'Égoutter. Servir chaud comme snack du soir.'],
        'tags': ['Accra', 'Épicé', 'Street food', 'Soir'],
        'image_url': '',
    },

    # ── JAPAN ─────────────────────────────────────────────────────────────────
    {
        'titre': 'Ramen Tonkotsu',
        'pays': 'japan',
        'type_plat': 'salé',
        'description': 'Ramen de Fukuoka au bouillon de porc crémeux et riche, chashu, œuf mariné et champignons.',
        'temps_preparation': 30, 'temps_cuisson': 240, 'nb_personnes': 4, 'difficulte': 'Difficile',
        'ingredients': ['1 kg d\'os de porc (carcasses)', '4 portions de nouilles ramen',
                        '400 g de ventre de porc (chashu)', '4 œufs', '100 ml de sauce soja',
                        '50 ml de mirin', '50 ml de saké', 'Champignons noirs séchés',
                        'Maïs, graines de sésame, oignon vert pour garnir'],
        'etapes': ['Blanchir les os 5 min, rincer. Cuire dans 3 L d\'eau à gros bouillon 4h.',
                   'Braiser le ventre de porc dans soja, mirin et saké 2h. Trancher fin.',
                   'Faire bouillir les œufs 7 min. Mariner dans la sauce restante 12h.',
                   'Cuire les nouilles selon paquet. Égoutter.',
                   'Dresser : bouillon chaud, nouilles, tranches de chashu, demi-œuf, garnitures.'],
        'tags': ['Fukuoka', 'Bouillon', 'Umami', 'Hiver'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Ramen_soup.jpg/800px-Ramen_soup.jpg',
    },
    {
        'titre': 'Mochi',
        'pays': 'japan',
        'type_plat': 'sucré',
        'description': 'Gâteaux de riz gluant à la pâte d\'azuki — emblème de la nouvelle année japonaise, texture unique moelleuse et élastique.',
        'temps_preparation': 20, 'temps_cuisson': 10, 'nb_personnes': 8, 'difficulte': 'Moyen',
        'ingredients': ['200 g de farine de riz gluant (shiratamako)', '180 ml d\'eau',
                        '50 g de sucre', '200 g de pâte d\'azuki (anko)', 'Fécule de pomme de terre pour le plan de travail'],
        'etapes': ['Mélanger farine de riz gluant, eau et sucre jusqu\'à pâte lisse.',
                   'Cuire au micro-ondes 2 min, remuer, cuire encore 1 min. Répéter jusqu\'à pâte translucide.',
                   'Verser sur plan de travail fariné (fécule). Laisser tiédir légèrement.',
                   'Diviser en 16 portions. Aplatir chaque portion en disque.',
                   'Déposer une boule d\'anko au centre. Refermer en pincant bien. Servir frais.'],
        'tags': ['Tokyo', 'Riz gluant', 'Azuki', 'Nouvel An'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Mochi_confection.jpg/800px-Mochi_confection.jpg',
    },

    # ── SOUTH KOREA ───────────────────────────────────────────────────────────
    {
        'titre': 'Bibimbap',
        'pays': 'south korea',
        'type_plat': 'salé',
        'description': 'Le riz mélangé coréen : bol de riz chaud, légumes sautés, bœuf, œuf et sauce gochujang — mélanger avant de déguster.',
        'temps_preparation': 30, 'temps_cuisson': 20, 'nb_personnes': 2, 'difficulte': 'Moyen',
        'ingredients': ['300 g de riz coréen', '200 g de bœuf haché', '1 courgette', '1 carotte',
                        '100 g d\'épinards', '100 g de champignons shiitake', '2 œufs',
                        'Sauce soja, huile de sésame, ail', '2 c. de gochujang (pâte de piment)'],
        'etapes': ['Cuire le riz. Mariner le bœuf avec soja, ail et huile de sésame.',
                   'Faire sauter chaque légume séparément avec un peu d\'ail et soja.',
                   'Cuire le bœuf à la poêle. Cuire les œufs au plat (jaune coulant).',
                   'Disposer le riz dans un bol, arrangersur le dessus les légumes par couleur, le bœuf et l\'œuf.',
                   'Servir avec gochujang à côté. Mélanger vigoureusement avant de manger.'],
        'tags': ['Séoul', 'Complet', 'Épicé', 'Bol'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Dolsot-bibimbap.jpg/800px-Dolsot-bibimbap.jpg',
    },
    {
        'titre': 'Hotteok',
        'pays': 'south korea',
        'type_plat': 'sucré',
        'description': 'Crêpe épaisse coréenne fourrée de cassonade, cannelle et noix — street food d\'hiver de Séoul.',
        'temps_preparation': 90, 'temps_cuisson': 15, 'nb_personnes': 6, 'difficulte': 'Moyen',
        'ingredients': ['300 g de farine', '100 g de farine de riz gluant', '7 g de levure',
                        '200 ml de lait tiède', '1 c. de sucre', '1 pincée de sel',
                        '100 g de cassonade', '1 c. de cannelle', '50 g de noix hachées', 'Huile'],
        'etapes': ['Mélanger farines, levure, lait, sucre et sel. Pétrir 5 min. Lever 1h.',
                   'Préparer la farce : cassonade, cannelle et noix.',
                   'Diviser la pâte en 12 boules. Aplatir chaque boule dans la paume.',
                   'Déposer 1 c. de farce au centre. Refermer hermétiquement.',
                   'Cuire dans une poêle huilée, écraser légèrement. 3 min par côté jusqu\'à doré.'],
        'tags': ['Séoul', 'Street food', 'Hiver', 'Cannelle'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Korean.food-Hotteok-01.jpg/800px-Korean.food-Hotteok-01.jpg',
    },

    # ── IRAN ──────────────────────────────────────────────────────────────────
    {
        'titre': 'Ghormeh Sabzi',
        'pays': 'iran',
        'type_plat': 'salé',
        'description': 'Le ragoût d\'herbes iranien : agneau aux herbes frites (persil, coriandre, fenugrec), haricots rouges et citron séché.',
        'temps_preparation': 30, 'temps_cuisson': 150, 'nb_personnes': 4, 'difficulte': 'Moyen',
        'ingredients': ['600 g d\'agneau', '200 g de persil plat', '100 g de coriandre',
                        '50 g de fenugrec frais', '100 g d\'épinards', '200 g de haricots rouges',
                        '3 citrons séchés (omani lemons)', 'Curcuma, sel, poivre', 'Huile végétale'],
        'etapes': ['Hacher finement toutes les herbes et les faire frire dans l\'huile 20 min jusqu\'à foncées et parfumées.',
                   'Faire revenir l\'agneau avec le curcuma.',
                   'Ajouter les herbes frites, les haricots trempés et les citrons séchés percés.',
                   'Couvrir d\'eau et mijoter 2h à feu doux.',
                   'Servir avec riz persan au safran.'],
        'tags': ['Téhéran', 'Herbes', 'Mijoté', 'Festif'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Ghormeh_sabzi_2.jpg/800px-Ghormeh_sabzi_2.jpg',
    },
    {
        'titre': 'Zoolbia et Bamieh',
        'pays': 'iran',
        'type_plat': 'sucré',
        'description': 'Beignets de Ramadan iraniens : zoolbia spiralés et bamieh en rosette, frits et trempés dans un sirop de rose.',
        'temps_preparation': 20, 'temps_cuisson': 20, 'nb_personnes': 8, 'difficulte': 'Moyen',
        'ingredients': ['200 g de farine', '100 g de fécule de maïs', '200 ml de yaourt',
                        '1 c. de levure', 'Eau de rose', 'Huile de friture',
                        '300 g de sucre', '200 ml d\'eau', '2 c. d\'eau de rose', 'Safran'],
        'etapes': ['Préparer le sirop : sucre, eau, safran et eau de rose. Cuire 10 min. Refroidir.',
                   'Mélanger farine, fécule, yaourt et levure en pâte fluide. Reposer 30 min.',
                   'Chauffer l\'huile à 175°C.',
                   'Pour les zoolbia : verser en spirale dans l\'huile avec une poche à douille.',
                   'Frire jusqu\'à dorure, égoutter, tremper 2 min dans le sirop froid.'],
        'tags': ['Ramadan', 'Sirop de rose', 'Safran', 'Téhéran'],
        'image_url': '',
    },

    # ── AUSTRALIA ─────────────────────────────────────────────────────────────
    {
        'titre': 'Meat Pie Australien',
        'pays': 'australia',
        'type_plat': 'salé',
        'description': 'Le pie australien : croûte feuilletée croustillante fourrée de bœuf haché en sauce brune — snack des stades et des bakeries.',
        'temps_preparation': 25, 'temps_cuisson': 40, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['2 rouleaux de pâte feuilletée', '500 g de bœuf haché', '1 oignon',
                        '200 ml de bouillon de bœuf', '2 c. de sauce Worcestershire',
                        '2 c. de farine', '1 c. de sauce tomate', '1 jaune d\'œuf (dorure)', 'Sel, poivre'],
        'etapes': ['Faire revenir oignon et bœuf haché. Ajouter la farine et cuire 2 min.',
                   'Ajouter bouillon, Worcestershire et sauce tomate. Mijoter 15 min jusqu\'à épaississement.',
                   'Foncer 4 moules individuels avec la pâte feuilletée.',
                   'Remplir de farce refroidie. Couvrir avec un disque de pâte. Sceller les bords.',
                   'Dorer au jaune d\'œuf. Cuire 25 min à 200°C.'],
        'tags': ['Sydney', 'Stade', 'Bakery', 'Rapide'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Meat_pies_Australia.jpg/800px-Meat_pies_Australia.jpg',
    },
    {
        'titre': 'Pavlova',
        'pays': 'australia',
        'type_plat': 'sucré',
        'description': 'Meringue géante croustillante dehors et fondante dedans, garnie de crème chantilly et fruits de la passion.',
        'temps_preparation': 20, 'temps_cuisson': 90, 'nb_personnes': 8, 'difficulte': 'Moyen',
        'ingredients': ['4 blancs d\'œuf', '220 g de sucre en poudre', '1 c. de Maïzena',
                        '1 c. de vinaigre blanc', '300 ml de crème entière', '1 c. de sucre glace',
                        '3 fruits de la passion', '200 g de fraises', '150 g de kiwi'],
        'etapes': ['Monter les blancs en neige ferme. Incorporer le sucre cuillerée par cuillerée.',
                   'Plier délicatement Maïzena et vinaigre.',
                   'Former un disque de 22 cm sur papier sulfurisé avec creux au centre.',
                   'Cuire 90 min à 120°C. Laisser refroidir four éteint porte entrouverte.',
                   'Garnir de crème fouettée sucrée et de fruits frais. Servir immédiatement.'],
        'tags': ['Sydney', 'Meringue', 'Été', 'Festif'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Pavlova_dessert.jpg/800px-Pavlova_dessert.jpg',
    },

    # ── SAUDI ARABIA ──────────────────────────────────────────────────────────
    {
        'titre': 'Kabsa',
        'pays': 'saudi arabia',
        'type_plat': 'salé',
        'description': 'Le plat national saoudien : riz basmati aux épices, poulet ou agneau, raisins secs et amandes grillées.',
        'temps_preparation': 20, 'temps_cuisson': 75, 'nb_personnes': 6, 'difficulte': 'Moyen',
        'ingredients': ['500 g de riz basmati', '1 poulet entier découpé', '2 oignons', '4 tomates',
                        '3 gousses d\'ail', '1 c. de cardamome', '1 c. de cannelle', '1 c. de clou de girofle',
                        '1 c. de cumin', '50 g de raisins secs', '50 g d\'amandes grillées', 'Sel'],
        'etapes': ['Faire revenir poulet avec oignons et ail. Réserver.',
                   'Préparer la sauce : tomates mixées avec toutes les épices. Cuire 15 min.',
                   'Remettre le poulet, ajouter l\'eau. Mijoter 40 min.',
                   'Retirer le poulet. Cuire le riz basmati dans le bouillon de cuisson 20 min.',
                   'Dresser le riz, poser le poulet dessus, parsemer de raisins et amandes.'],
        'tags': ['Riyad', 'National', 'Festif', 'Riz épicé'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Kabsa_Dinner.jpg/800px-Kabsa_Dinner.jpg',
    },
    {
        'titre': 'Luqaimat',
        'pays': 'saudi arabia',
        'type_plat': 'sucré',
        'description': 'Petites boules de pâte levée frites, enrobées de sirop de dattes et sésame — douceur de Ramadan du Golfe.',
        'temps_preparation': 15, 'temps_cuisson': 15, 'nb_personnes': 6, 'difficulte': 'Facile',
        'ingredients': ['200 g de farine', '7 g de levure sèche', '150 ml d\'eau tiède',
                        '1 c. de sucre', '1 pincée de safran infusé', 'Huile de friture',
                        '100 g de sirop de dattes (dibs)', 'Graines de sésame'],
        'etapes': ['Dissoudre la levure et le sucre dans l\'eau tiède avec le safran infusé.',
                   'Mélanger avec la farine pour former une pâte fluide. Laisser lever 1h.',
                   'Chauffer l\'huile à 175°C.',
                   'Déposer des petites boules de pâte à la cuillère et frire 3–4 min jusqu\'à dorure.',
                   'Égoutter. Napper immédiatement de sirop de dattes et parsemer de sésame.'],
        'tags': ['Ramadan', 'Dattes', 'Golfe', 'Douceur'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Luqaimat.jpg/800px-Luqaimat.jpg',
    },

    # ── CROATIA ───────────────────────────────────────────────────────────────
    {
        'titre': 'Cevapi',
        'pays': 'croatia',
        'type_plat': 'salé',
        'description': 'Petites saucisses de bœuf et agneau grillées, servies dans du lepinja (pain pita) avec kajmak et oignon haché.',
        'temps_preparation': 20, 'temps_cuisson': 15, 'nb_personnes': 4, 'difficulte': 'Facile',
        'ingredients': ['400 g de bœuf haché', '200 g d\'agneau haché', '3 gousses d\'ail',
                        '1 c. de bicarbonate', '1 c. de paprika', 'Sel, poivre',
                        '4 pains pita (lepinja)', '200 g de kajmak ou crème épaisse', '1 oignon blanc haché'],
        'etapes': ['Mélanger bœuf, agneau, ail écrasé, bicarbonate, paprika, sel et poivre.',
                   'Façonner en petites saucisses de 6 cm, sans moule, à la main.',
                   'Laisser reposer 30 min au frais.',
                   'Griller sur barbecue ou plancha bien chaude 6–8 min en retournant régulièrement.',
                   'Servir dans le lepinja grillé avec kajmak et oignon haché abondant.'],
        'tags': ['Grill', 'Zagreb', 'Balkan', 'Street food'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/%C4%86evap%C4%87i%C4%87i.jpg/800px-%C4%86evap%C4%87i%C4%87i.jpg',
    },
    {
        'titre': 'Kremsnita (Millefeuille Croate)',
        'pays': 'croatia',
        'type_plat': 'sucré',
        'description': 'Gâteau crème légendaire de Samobor : deux couches de pâte feuilletée avec une épaisse crème pâtissière vanille.',
        'temps_preparation': 30, 'temps_cuisson': 30, 'nb_personnes': 12, 'difficulte': 'Moyen',
        'ingredients': ['2 feuilles de pâte feuilletée (30×40 cm)', '1 L de lait entier',
                        '150 g de sucre', '8 jaunes d\'œuf', '80 g de Maïzena',
                        '1 c. de vanille', '300 ml de crème fouettée', 'Sucre glace'],
        'etapes': ['Cuire les feuilles de feuilletage à 200°C 20 min. Laisser refroidir.',
                   'Chauffer le lait avec la vanille.',
                   'Battre jaunes et sucre, ajouter la Maïzena. Verser le lait chaud en fouettant.',
                   'Cuire jusqu\'à crème épaisse. Laisser refroidir puis incorporer la crème fouettée.',
                   'Poser une feuille de feuilletage, étaler la crème épaisse, couvrir de la seconde feuille. Saupoudrer de sucre glace.'],
        'tags': ['Samobor', 'Crème', 'Classique', 'Café'],
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Kremsnita.jpg/800px-Kremsnita.jpg',
    },
]


class Command(BaseCommand):
    help = 'Charge les recettes Coupe du Monde 2026 (BR, AR, MX, US, CA, CO, UY, EC, MA, SN, NG, EG, CM, ZA, DZ, CI, GH, JP, KR, IR, AU, SA, HR)'

    def handle(self, *args, **options):
        created, updated = 0, 0
        for data in RECIPES:
            obj, was_created = Recipe.objects.update_or_create(
                titre=data['titre'],
                pays=data['pays'],
                type_plat=data.get('type_plat', 'salé'),
                defaults=data,
            )
            if was_created:
                created += 1
            else:
                updated += 1
        self.stdout.write(self.style.SUCCESS(
            f'Done — {created} created, {updated} updated ({created + updated} total)'
        ))
