# Generated by Django 6.0.3 on 2026-03-07 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='matches.match')),
                ('recette_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions_a', to='recipes.recipe')),
                ('recette_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions_b', to='recipes.recipe')),
            ],
        ),
    ]
