# Generated by Django 6.0.3 on 2026-08-05 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
