from django.core.management.base import BaseCommand
from apps.beers.models import Beer

BEERS = [
    {
        'nom': 'Fuller\'s London Pride',
        'brasserie': 'Fuller, Smith & Turner',
        'pays': 'england',
        'region': 'Londres',
        'equipe': '',
        'style': 'Pale Ale',
        'description': 'La bière emblématique des pubs londoniens depuis 1959. Notes de biscuit, caramel et houblon fruité — la vraie Ale anglaise.',
        'degre_alcool': '4.7',
        'image_url': '',
        'generated_by': 'manual',
    },
    {
        'nom': 'Kronenbourg 1664',
        'brasserie': 'Brasserie Kronenbourg',
        'pays': 'france',
        'region': 'Alsace',
        'equipe': '',
        'style': 'Lager',
        'description': 'La bière française la plus exportée dans le monde depuis 1952. Légère, maltée et rafraîchissante — née à Strasbourg.',
        'degre_alcool': '5.0',
        'image_url': '',
        'generated_by': 'manual',
    },
    {
        'nom': 'Paulaner Weissbier',
        'brasserie': 'Paulaner Brauerei',
        'pays': 'germany',
        'region': 'Bavière',
        'equipe': '',
        'style': 'Hefeweizen',
        'description': 'La grande bière de blé bavaroise depuis 1634. Trouble, dorée, avec des arômes de banane et de clou de girofle — incontournable à l\'Oktoberfest.',
        'degre_alcool': '5.5',
        'image_url': '',
        'generated_by': 'manual',
    },
    {
        'nom': 'Estrella Damm',
        'brasserie': 'S.A. Damm',
        'pays': 'spain',
        'region': 'Catalogne',
        'equipe': '',
        'style': 'Pale Lager',
        'description': 'La bière méditerranéenne de Barcelone depuis 1876. Légère et désaltérante, brassée à l\'orge et au maïs. Parfaite avec des tapas.',
        'degre_alcool': '5.4',
        'image_url': '',
        'generated_by': 'manual',
    },
    {
        'nom': 'Moretti',
        'brasserie': 'Birra Moretti (Heineken)',
        'pays': 'italy',
        'region': 'Udine',
        'equipe': '',
        'style': 'Lager',
        'description': 'La bière italienne au moustachu célèbre depuis 1859. Dorée, légèrement houblonnée, parfaite accompagnement des pizzas et pâtes.',
        'degre_alcool': '4.6',
        'image_url': '',
        'generated_by': 'manual',
    },
    {
        'nom': 'Super Bock',
        'brasserie': 'Super Bock Group',
        'pays': 'portugal',
        'region': 'Porto',
        'equipe': '',
        'style': 'Pale Lager',
        'description': 'La bière nationale portugaise par excellence depuis 1927. Légère et rafraîchissante, incontournable dans les tascas de Lisbonne et Porto.',
        'degre_alcool': '5.2',
        'image_url': '',
        'generated_by': 'manual',
    },
    {
        'nom': 'Heineken',
        'brasserie': 'Heineken N.V.',
        'pays': 'netherlands',
        'region': 'Amsterdam',
        'equipe': '',
        'style': 'Pale Lager',
        'description': 'La bière néerlandaise la plus connue au monde depuis 1873. Légère, propre et pétillante — symbole de la convivialité mondiale.',
        'degre_alcool': '5.0',
        'image_url': '',
        'generated_by': 'manual',
    },
    {
        'nom': 'Leffe Blonde',
        'brasserie': 'AB InBev (brassée à Leuven)',
        'pays': 'belgium',
        'region': 'Namur',
        'equipe': '',
        'style': 'Bière d\'abbaye',
        'description': 'La bière d\'abbaye belge fondée en 1240. Dorée, ronde et légèrement épicée — la référence des bières d\'abbaye dans le monde.',
        'degre_alcool': '6.6',
        'image_url': '',
        'generated_by': 'manual',
    },
    {
        'nom': 'Carlsberg',
        'brasserie': 'Carlsberg Group',
        'pays': 'denmark',
        'region': 'Copenhague',
        'equipe': '',
        'style': 'Pale Lager',
        'description': 'La bière danoise fondée en 1847 par J.C. Jacobsen. Propre et équilibrée — celle qui se dit "probablement la meilleure bière du monde".',
        'degre_alcool': '5.0',
        'image_url': '',
        'generated_by': 'manual',
    },
    {
        'nom': 'Erdinger Weissbier',
        'brasserie': 'Erdinger Weissbräu',
        'pays': 'austria',
        'region': 'Erding',
        'equipe': '',
        'style': 'Hefeweizen',
        'description': 'Grande bière de blé bavaroise d\'Erding. Trouble, avec des notes de levure, de banane et d\'agrumes — parfaite après un effort.',
        'degre_alcool': '5.3',
        'image_url': '',
        'generated_by': 'manual',
    },
    {
        'nom': 'Feldschlösschen',
        'brasserie': 'Feldschlösschen Getränke',
        'pays': 'switzerland',
        'region': 'Rheinfelden',
        'equipe': '',
        'style': 'Lager',
        'description': 'La bière suisse la plus populaire depuis 1876. Légère, propre et dorée — brassée dans le château de Rheinfelden au bord du Rhin.',
        'degre_alcool': '4.8',
        'image_url': '',
        'generated_by': 'manual',
    },
    {
        'nom': 'Tennent\'s Lager',
        'brasserie': 'Tennent\'s / C&C Group',
        'pays': 'scotland',
        'region': 'Glasgow',
        'equipe': '',
        'style': 'Lager',
        'description': 'La bière nationale écossaise depuis 1885, brassée à Glasgow. Légère et légèrement maltée — fidèle compagne des supporters des Tartan Army.',
        'degre_alcool': '4.0',
        'image_url': '',
        'generated_by': 'manual',
    },
    {
        'nom': 'Żywiec',
        'brasserie': 'Browar Żywiec (Heineken)',
        'pays': 'poland',
        'region': 'Żywiec',
        'equipe': '',
        'style': 'Pale Lager',
        'description': 'La bière polonaise premium depuis 1856, brassée dans les Carpates. Légère, maltée et légèrement houblonnée.',
        'degre_alcool': '5.6',
        'image_url': '',
        'generated_by': 'manual',
    },
    {
        'nom': 'Efes Pilsen',
        'brasserie': 'Anadolu Efes',
        'pays': 'turkey',
        'region': 'Istanbul',
        'equipe': '',
        'style': 'Pilsner',
        'description': 'La bière turque la plus populaire depuis 1969. Légère, dorée et rafraîchissante — brassée à Istanbul sur les rives du Bosphore.',
        'degre_alcool': '5.0',
        'image_url': '',
        'generated_by': 'manual',
    },
    {
        'nom': 'Lvivske',
        'brasserie': 'Carlsberg Ukraine',
        'pays': 'ukraine',
        'region': 'Lviv',
        'equipe': '',
        'style': 'Pale Lager',
        'description': 'La bière ukrainienne historique brassée à Lviv depuis 1715. Dorée et légèrement maltée — symbole de la fierté nationale ukrainienne.',
        'degre_alcool': '4.7',
        'image_url': '',
        'generated_by': 'manual',
    },
]


class Command(BaseCommand):
    help = 'Charge les bières des équipes européennes WC 2026 manquantes'

    def handle(self, *args, **options):
        created, updated = 0, 0
        for data in BEERS:
            obj, was_created = Beer.objects.update_or_create(
                nom=data['nom'],
                pays=data['pays'],
                defaults=data,
            )
            if was_created:
                created += 1
            else:
                updated += 1
        self.stdout.write(self.style.SUCCESS(
            f'Done — {created} created, {updated} updated ({created + updated} total)'
        ))
